### ISSUE TITLE
[sprite] some things look wrong

### ISSUE THREAD

**Issue by water111** [open-goal/jak-project#1050]
- [ ] the things that poke out of the sun
- [ ] the mist on misty island looks weird
- [ ] the blue eco in rock village near the boulder appears behind the waterfall
- [ ] (maybe) the blue eco is too bright

**Comment by water111** [comment]
Blending:
![image](https://user-images.githubusercontent.com/48171810/148663472-fb1030b0-0ba1-4e5c-afc7-118e9cf78a9d.png)

**Comment by ManDude** [comment]
> the things that poke out of the sun

This might not be a bug. It seems like the corona has a random appearance and this is replicated in our version. Game screenshots:

Bright:
![image](https://user-images.githubusercontent.com/7569514/148663872-70876a03-1711-4452-9b6b-ba17bc05e8de.png)
Brightest:
![image](https://user-images.githubusercontent.com/7569514/148663881-bd4b4876-a65b-4f2e-a886-11a29e2fd9d6.png)

> the blue eco in rock village near the boulder appears behind the waterfall

Also happens in the game:
![image](https://user-images.githubusercontent.com/7569514/148663964-05628d05-f6bf-418a-8f77-50181aacdcce.png)

**Comment by water111** [comment]
The brightness, blue eco appearing behind stuff, and sun are all believed to be like that in the original game.
With the changes in https://github.com/open-goal/jak-project/pull/1185 the other issues are fixed: 
![image](https://user-images.githubusercontent.com/48171810/154858588-250be08a-16f8-44e8-9c4f-b904dbcfac86.png)
![image](https://user-images.githubusercontent.com/48171810/154858618-b32b9901-c9ff-4449-aac0-5b65c0564bc0.png)
