### ISSUE TITLE
[collision] punch glitch

### ISSUE THREAD

**Issue by water111** [open-goal/jak-project#1095]
This issue will collect all information about the punch glitch.

**Comment by ManDude** [comment]
got it in sandover when punching off this ledge
![image](https://user-images.githubusercontent.com/7569514/150470705-3fbefc38-18da-400c-8427-c2cbd89b9db9.png)

also got it in the entrance to the temple around here
![image](https://user-images.githubusercontent.com/7569514/150471841-81beb918-a875-4b28-bfc9-c1f818a60069.png)


and inside in here
![image](https://user-images.githubusercontent.com/7569514/150471598-bf478797-7076-40b7-abfb-02b8dea9509f.png)


Couldn't replicate consistently.

**Comment by ManDude** [comment]
happens quite often at the area where you grab the sentinel cell
![image](https://user-images.githubusercontent.com/7569514/150473582-079d280f-e7ca-450d-b8c8-73476ede3689.png)

**Comment by water111** [comment]
Worth nothing that all these were before the `vector+!` and `vector-!` fix, and `(-> *target* control trans w)` was 0. (I don't think it will fix it, but it will definitely change the collision geometry slightly)

**Comment by water111** [comment]
The issue is the `acos` in `logic-target.gc`. In PCSX2/PS2 it can never quite return 0.0.  But on PC it does, and it causes `0/0` instead of `0/very-small-number`. This is used as the input to a `slerp` and it ends up setting the output quaternion to `0 0 0 0`. Over the next 2 frames, this completely breaks the `dir-targ` and `unknown-quaternion00` and the target/camera rotation matrix ends up being identity. This sudden change rotates jak's velocity so it is entirely in the global x direction.

My understanding is that this should only happen when the dir-targ aligns with jak's velocity exactly. It _may_ only be catastrophic if the camera is also aligned so that pushing forward on the stick will move jak in this direction.

I don't think the location has anything to do with it. It's possible that it only happens on ground that's perfectly level but I don't know. Instead, I think it tends to happen in places where people are lined up well with the camera and punching in/out of the camera exactly.

To fix in our port, we have a few options:
- mess with the rounding options. I confirmed that using PCSX2's defaults prevents `acos` from returning 0.0
- hack this particular case to return a small number instead of 0.

**Comment by water111** [comment]
I added a hack specific to `acos` in `trigonometry.gc`. Nobody has reported a punch glitch in over 3 weeks so I think we got it.
