### ISSUE TITLE
[camera] mysteries

### ISSUE THREAD

**Issue by water111** [open-goal/jak-project#1101]
There are a few tiny issues with the camera that don't have a good explanation yet.

- [ ] There are sometimes spline overflow errors. I haven't been able to find any cause/pattern in them, and I don't really know what they mean.
- [x] The scout fly on the outside of the fj temple has a little hole that camera has to pass through. It completely fails to do this correctly.
- [x] When walking around the outside near that scout fly, you can move the camera with the joysticks, but only by a tiny amount. 

As usual, the problem might be bones :)

**Comment by ManDude** [comment]
I've seen the spline errors on PS2 as well fwiw.
