### ISSUE TITLE
Provide non-avx2 versions of functions in game

### ISSUE THREAD

**Issue by water111** [open-goal/jak-project#1135]
We originally required only AVX for `goalc`, but some of  c++ code uses AVX2/FMA intrinsics, so running the game now requires AVX2 + FMA.

We should have non-AVX2 versions of these - anything older than haswell doesn't support avx2.  Sandy bridge is likely fast enough, but only has AVX.

**Comment by doctashay** [comment]
This one's for all the folks like me who use decade old CPUs!
