### ISSUE TITLE
Fix buildcache for Windows + clang-cl

### ISSUE THREAD

**Issue by xTVaser** [open-goal/jak-project#1158]
The cache isn't working properly for the clang-cl variant for some reason
![image](https://user-images.githubusercontent.com/13153231/153729516-eb1edc4a-fb23-4c71-8a5a-9b6a85f3f993.png)

Additionally, we should probably switch from `nmake` if possible.  Ninja would likely be faster.

**Comment by water111** [comment]
pretty sure this is working now, feel free to reopen if I'm wrong.
