### ISSUE TITLE
[graphics] msaa toggle

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#1173]
I totally meant to do this but it slipped my mind. There should be a way to toggle it on/off (I believe `glEnable(GL_MULTISAMPLING)` or something exists)

**Comment by Jakjm** [comment]
https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glEnable.xhtml
Yep looks like it!

**Comment by Jakjm** [comment]
I've tried to address this with  #1176, but I don't think it's quite working - I can still feel a bit of lag when collecting a powercell, whereas commenting out `glfwWindowHint(GLFW_SAMPLES, 4);` from opengl.cpp seems to make it much smoother (but then obviously we wouldn't be able to toggle the antialiasing on or off). So I think my changes might need an adjustment.
