### ISSUE TITLE
[build] all builds AVX, even if the user has AVX2

### ISSUE THREAD

**Issue by water111** [open-goal/jak-project#1183]
Our theory is that some github actions machines have AVX2, some don't. So building with `-march=native` fills our cache with AVX2 stuff that gets used by non-AVX2 machines.

The current workaround is to just make everything AVX.  But our fast AVX2 implementations are then never used.  It's probably not the end of the world (it's 200us slower/frame for me) but it's sad to spend the time writing fast AVX2 stuff and then not use it because of build system issues.

**Comment by xTVaser** [comment]
I think this theory is inaccurate.  Github runners use the following Azure instances https://docs.microsoft.com/en-us/azure/virtual-machines/dv2-dsv2-series#dsv2-series which are either icelake/skylake/haswell/broadwell.

All support AVX2.

**Comment by water111** [comment]
you're right. I think the real problem was AVX-512.  The icelake CPU supports it, but broadwell doesn't. I think we could set `avx2` explicitly and it would be fine on github.

That said, I don't think we should actually do this - it will make the releases require avx2. I'm going to leave this open just as a reminder to add some documentation/flags so users could compile their own release with avx2 support, if they want.

**Comment by water111** [comment]
let's just stick with plain AVX for now.
