### ISSUE TITLE
[game] Yellow eco fails to target finalboss

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#1216]
This works in the original game.

![image](https://user-images.githubusercontent.com/7569514/156491090-0745cd6a-3bf5-4be5-9a0f-9c0e063c61bc.png)
![image](https://user-images.githubusercontent.com/7569514/156491140-5d05e6ce-a520-4831-8946-05a01ff29521.png)

**Comment by Zedb0T** [comment]
This appears to be resolved now on master.

**Comment by ManDude** [comment]
it is fixed
