### ISSUE TITLE
[game] Incorrect title screen camera behavior

### ISSUE THREAD

**Issue by towai** [open-goal/jak-project#1238]
Don't know if this is how this should be categorized but it's a thing I noticed a while ago, however minor. Would be moderately surprised if this hasn't been noticed already, but I figure there should probably be an issue about it either way.
The game's behavior on PS2 works like this: When you hit start to open the main menu, the camera stops moving immediately.
In OpenGOAL, it will keep going until it hits a particular point and then stop, spamming a complaint about loader stall on art logo-intro-2 (or logo-loop if it's about to loop) [spool-part]. (note - the points where the camera stops are not consistent).

note: if you pause right away at the title screen on PS2, the camera will actually progress for a second or two until it hits this frame:
![image](https://user-images.githubusercontent.com/12366892/158748980-26aa5cd6-8223-4a1e-8d48-eac17c847bd6.png)
Pausing any time after that will just make it halt immediately. Pausing right away in OpenGOAL gives this exact same frame. This one spams "loader stall on lock" instead.

**Comment by ManDude** [comment]
I think this might be related to audio syncing, so we could wait until we have audio implemented to double check this.

**Comment by Zedb0T** [comment]
I was going to create a separate issue to document this - however I think this is related so I will document it below.

On current builds you can not preform the traditional blue sage cutscene skip due to the camera either not despawning or spawning too soon or something. May be related to this and have to wait. (Or not be an issue at all and just how openGOAL will run)

**Comment by Zedb0T** [comment]
> 

As of the most recent merge this is working as it does on original hardware :D

**Comment by ManDude** [comment]
As I suspected, this is fixed now that audio is implemented.
