### ISSUE TITLE
progress menu "rotate" effect doesn't look right

### ISSUE THREAD

**Issue by water111** [open-goal/jak-project#1253]
for example, when changing language. Going right looks wrong, but left looks correct.

**Comment by ManDude** [comment]
also happens when scrolling through levels (the effect is vertical this time)

**Comment by ManDude** [comment]
Going left isn't correct either. (These are like 2 frames apart)
![image](https://user-images.githubusercontent.com/7569514/160219379-02f095db-e26a-4ddd-b540-91fcbecf78ff.png)
![image](https://user-images.githubusercontent.com/7569514/160219382-405ba1bb-98b9-48a9-8e30-9d574eb9885a.png)

**Comment by ManDude** [comment]
Only happens in the new menu code.

**Comment by ManDude** [comment]
this is fixed in #1281
