### ISSUE TITLE
[shrub] bad time of day color on some rings in lpc

### ISSUE THREAD

**Issue by water111** [open-goal/jak-project#1265]
![image](https://user-images.githubusercontent.com/48171810/160941279-c822a760-992b-4917-a267-50cc92dec1b7.png)

I confirmed that bad color is from time of day colors, not base colors.

**Comment by water111** [comment]
I spent many hours looking at this - still no idea :disappointed:

**Comment by Hat-Kid** [comment]
Fixed by #2488
