### ISSUE TITLE
[Releases] [0.0.7] Have Extractor.exe place files in out\data\iso_data\jak1 in release builds on windows

### ISSUE THREAD

**Issue by Zedb0T** [open-goal/jak-project#1332]
Currently it places them in out\data\extracted_iso
With the files in this location, if you run goalc and run (mi) you get an error as it cant find the data from the iso.

If it places them in out\data\iso_data\jak1 then goalc.exe can run (mi) and find the files correctly.

Currently a user can just manually move it though as a temporary fix 👍.

**Comment by water111** [comment]
this is a good idea. I think I wanted to do this originally, but I don't remember why I didn't do it.
