### ISSUE TITLE
[hint] abrupt stop sometimes

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#1336]
This makes things like hints just stop abruptly (the audio stops or the text disappears).

**Comment by ManDude** [comment]
Happens to both entity ambients and hints spawned by other processes.

**Comment by ManDude** [comment]
I remember why I thought this was an entity issue - it doesn't happen when the "all actors" option is enabled, and is also affected by the camera position.

**Comment by ManDude** [comment]
The option makes `is-object-visible?` in `level` always return true (and also some hack for actor entities).

**Comment by water111** [comment]
> it doesn't happen when the "all actors" option is enabled

It turns out it was triggered by actors being killed in the background, so this makes sense.
