### ISSUE TITLE
[game] Closing the gk.exe window does not terminate the process when `-boot` flag is provided

### ISSUE THREAD

**Issue by xTVaser** [open-goal/jak-project#1362]
The process continues to run when the window is closed:
![image](https://user-images.githubusercontent.com/13153231/169401974-e7341d49-4b0f-4335-9552-1be676bf2b10.png)

This is in `-boot` mode.  It works properly without this flag

**Comment by ManDude** [comment]
I do not have this issue.

**Comment by ManDude** [comment]
Nevermind, I thought with "gk.exe" window you meant the console and not the OpenGL window.

**Comment by ManDude** [comment]
Looks like this is caused by the Deci2Server waiting forever until the REPL connects to it, so when the game wants the Deci2 thread to die, it has to wait until this ends, which it never does.
