### ISSUE TITLE
[Game] [deci2server] On windows you are unable to run multiple instances of Gk.exe at the same time

### ISSUE THREAD

**Issue by Zedb0T** [open-goal/jak-project#1383]
gproto: proto open at socket 1
kernel: RPC port #0 started [DEB1]
kernel: RPC port #1 started [DEB2]
kernel: RPC port #2 started [DEB3]
kernel: RPC port #3 started [DEB4]
kernel: RPC port #4 started [DEB5]
kernel: RPC port #5 started [DEB6]
[XSocketServer:8112] failed to bind
Assertion failed: 'false'
        Message: [DECI2] Server not initialized even if protocols are ready, aborting
        Source: D:\a\jak-project\jak-project\game\runtime.cpp:90
        Function: void __cdecl (anonymous namespace)::deci2_runner(SystemThreadInterface &)

**Comment by water111** [comment]
will be fixed in #1385
