### ISSUE TITLE
[constant crash] [game] [release 0.1.3] Using the in game debug menus save option can create a garbage save under certain circumstances

### ISSUE THREAD

**Issue by Zedb0T** [open-goal/jak-project#1425]
This will cause gk.exe to always crash on boot.

Corrupted save file for debugging purposes:

Tested with a regenerated fresh settings file so the issue is almost certainly in the save file

**Comment by Zedb0T** [comment]
Github wouldn't let me upload the corrupt save so its in the discord in #github https://discord.com/channels/756287461377703987/756288277111111811/983501608019193946

**Comment by ManDude** [comment]
`bank0.bin` here is 0 bytes. That will for sure crash the game whenever it's gonna try to fetch anything from the "memory card."
