### ISSUE TITLE
Process hangs when closed during certain cutscenes

### ISSUE THREAD

**Issue by xTVaser** [open-goal/jak-project#1430]
Play the cutscene at `citadel-start` and attempt to close the game.  For me, this results in a consistent hang and a process that never closes.

**Comment by ManDude** [comment]
I think it happens here:
```cpp

            while (gMusicFade) {
              DelayThread(1000);
            }
```
The vblank handler stops running when you close the window, so `gMusicFade` will never get updated. If I make these loops just not run ever, there is no issue.

**Comment by ManDude** [comment]
Well patching that didn't fix it completely, so, looking at it further, it might also be getting stuck in the `SleepThread()` a little further down in `LoadMusic` which calls `SuspendThread()` which then waits on `waitForDispatch()` forever.

**Comment by water111** [comment]
`IOP_Kernel::shutdown` will run `dispatchAll` in a loop to get the IOP threads to finish, so the load should eventually continue and that thread will get woken up.

**Comment by ManDude** [comment]
It looks like something is causing that to not happen properly, though. I put a breakpoint in `LoadMusic`, it gets hit when I close the game (fade got cancelled quickly with no problems), calls `SleepThread` and then never wakes up.

**Comment by ManDude** [comment]
`SleepThread()` sets `started` to `false` on the calling thread, so the `dispatchAll` won't run on it.

**Comment by water111** [comment]
The `SleepThread` sets a "sleep" status on the thread so it won't be woken up until something replies to the `SendMbx` done earlier.

**Comment by water111** [comment]
The reply should come from the `case LOAD_MUSIC` in `iso.cpp`, one of those `SendMbx`, or the `ReturnMessage`

**Comment by ManDude** [comment]
Hmm, maybe it's related to how music doesn't load until the current stream is paused or stopped. I commented out a few overlord hacks, and `case LOAD_MUSIC` doesn't get past this:

```cpp
        case LOAD_MUSIC: {
          // if there's an in progress vag command, try again.
          if (in_progress_vag_command && !in_progress_vag_command->paused) {
            SendMbx(iso_mbx, msg_from_mbx);
            break;
          }
```

So we could either make this work even while a stream is playing (which would be cool), or make all streams stop when the game is killed.

**Comment by ManDude** [comment]
Ok I made the game just load music while a stream is playing and... I didn't notice any issues? It seemed almost too easy.
