### ISSUE TITLE
Default keyboard controls are enforced with no way to disable them

### ISSUE THREAD

**Issue by xTVaser** [open-goal/jak-project#1431]
Currently the analog controls are properly skipped if a pad is detected:
- https://github.com/open-goal/jak-project/blob/ecb2781a8968cd126ebb8c697411014768e317a5/game/system/newpad.cpp#L126-L165

But the face buttons and such are not:
- https://github.com/open-goal/jak-project/blob/ecb2781a8968cd126ebb8c697411014768e317a5/game/system/newpad.cpp#L200-L225

This is really annoying if you are doing something like typing into a debug window.  I was going to quickly fix this, but I wasn't sure if we had a game config setup for the C++ side yet, or how that will interact through the game's settings -- as that is probably where we want to enable/disable things like this.

**Comment by ManDude** [comment]
I'm not sure what the issue is here. Is it that typing in imgui also does inputs in the game? You can look at the code that handles keyboard input (probably somewhere in `Display.cpp`) but I have no idea how you can tell if you're typining in an imgui window or not.

Also keyboard inputs *should* be enabled regardless of if a controller is plugged in. I've never heard of any software where one disabled the other, it doesn't make sense.

**Comment by doctashay** [comment]
You may be able to use `ImGui::IsItemActive()` and/or `ImGui::TempInputIsActive(ImGui::GetActiveID())` to tell if you're typing in an imgui debug window specifically, although I haven't used ImGui in a while.

**Comment by xTVaser** [comment]
> Also keyboard inputs should be enabled regardless of if a controller is plugged in. I've never heard of any software where one disabled the other, it doesn't make sense.

Well they currently aren't (in full) because of the code I linked above, so i guess thats something that needs to change.

What I'd like to see is exactly as I described, the ability to opt-out of keyboard controls for the reasons I described.

**Comment by ManDude** [comment]
Manually unbinding controls is one thing, automatically disabling an input device because a controller is detected is another.

Fwiw you can use `pc-pad-utils.gc` to remap keyboard mappings and it should saved/loaded to a file. This system is pending a bit of a rewrite though.

**Comment by xTVaser** [comment]
I'm not proposing we automatically disable input devices based on another -- that is what the current code does (in part) that was previously approved and merged, as you can see above.

**Comment by ManDude** [comment]
Hmm okay I was misunderstanding this. Well, in any case you can actually rebind the non-analog buttons with that code file. Imo the best option here is to just not accept keyboard input if we're in an imgui menu.

**Comment by xTVaser** [comment]
If that is easy to do, then it would be a welcomed addition.  But I have a feeling it will be a pain / overly complicated for what is ultimately just a debugging use-case.

I was mostly using ImGui as an example of the problem.  Putting that aside, personally, I would want to completely unbind the keyboard controls for other reasons as well.

I will look into that code file, as you said it seems to not cover the analog buttons, and it also doesn't seem to have the ability to unbind -- only apply new bindings
