### ISSUE TITLE
[runtime] make fullscreen settings actually work properly

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#1456]
This is such a pain to get working.

**Comment by AlphaNERD-** [comment]
That and language settings. When you boot up the game, the main menu is in english despite me previously setting the language to german. Once i've loaded my savegame, the language setting is applied properly.

**Comment by AlphaNERD-** [comment]
Ooooh, so the game loaded the language from the PS2 BIOS settings, right?

**Comment by ManDude** [comment]
The startup language is determined by BIOS, yes. And we just use English always right now. Maybe eventually we can set the default based on system language. Eventually it will just load from the global settings as well.
