### ISSUE TITLE
Spaces or ampersands (&) in path breaks extractor

### ISSUE THREAD

**Issue by vaguerant** [open-goal/jak-project#1467]
```
Successfully built all 1293 targets in 137.873s
'C:\Games\PC\Jak' is not recognized as an internal or external command,
operable program or batch file.
'Daxter\data\..' is not recognized as an internal or external command,
operable program or batch file.
```
Everybody gets one guess what the folder is called.

**Comment by ManDude** [comment]
Might be the space actually... we should surround the command with quotes.

**Comment by vaguerant** [comment]
Yep, can confirm. Right after filing, I renamed the folder to `Jak and Daxter` and got
```
Successfully built all 1293 targets in 110.562s
'C:\Scott\Games\PC\Jak' is not recognized as an internal or external command,
operable program or batch file.
```
The ampersand does have meaning, it's trying to run two separate commands, so both are breaking, but yeah, quotes should fix both issues,
