### ISSUE TITLE
[game] hide "vibration" toggle as it does nothing

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#1474]
Fun fact: In the original game it's also meant to vibrate the controller whenever you enable it! But sadly it's slightly wrong so you never get this.

**Comment by dante3732** [comment]
> Fun fact: In the original game it's also meant to vibrate the controller whenever you enable it! But sadly it's slightly wrong so you never get this.

I test now on pcsx2 and vibration work good. If i disable it in settings, it don't work.

**Comment by ManDude** [comment]
That's not really what I meant.
