### ISSUE TITLE
Bluetooth controller support

### ISSUE THREAD

**Issue by coreybruce** [open-goal/jak-project#1476]
Hi just wanted to ask if you could add Bluetooth controller support like for xbox controllers for example as the game does not detect them but will detect usb wired controllers

**Comment by ManDude** [comment]
Bluetooth controllers are supported. Make sure you don't have something else plugged in.

**Comment by MojoJojoDojo** [comment]
Why this is closed? there seems to be a legit issue with bluetooth controllers....
I can run other emulators/games fine with bluetooth but not this...

**Comment by coreybruce** [comment]
> Bluetooth controllers are supported. Make sure you don't have something else plugged in.

Clearly not, my Xbox controller doesn't work on the game? Why is this closed?

**Comment by coreybruce** [comment]
> Why this is closed? there seems to be a legit issue with bluetooth controllers.... I can run other emulators/games fine with bluetooth but not this...

No idea, not sure if they have fix this yet or not but from my testing when I made this report only wired controllers worked

**Comment by MojoJojoDojo** [comment]
> > Why this is closed? there seems to be a legit issue with bluetooth controllers.... I can run other emulators/games fine with bluetooth but not this...
> 
> No idea, not sure if they have fix this yet or not but from my testing when I made this report only wired controllers worked

If you are using Linux you need to install xpadneo , it wont work without it.

**Comment by coreybruce** [comment]
Don't need to anymore, my controller works out of the box also I use my Xbox controller on Steam and no Steam games so it's a issue on here not my system

**Comment by ManDude** [comment]
Because, like I said, bluetooth controllers *are* supported. I can use mine just fine.

But even if they weren't, there isn't much we can do about it. Third-party libraries are used for handling controllers, etc.

**Comment by coreybruce** [comment]
Is there anything needed that it's missing?

**Comment by JefferyPLol** [comment]
I run the game through steam and that makes my ds4 works fine with bluetooth so you could try that. However every time I've run the game without steam my ds4 only works with a usb connection.

**Comment by RinMaru** [comment]
BT works fine for me so its your system bud

**Comment by water111** [comment]
It should work for controllers that glfw supports and have an entry in the sdl game controller db. So some controllers might not work. If you want to add more, you can add to glfw and the sdl controller list.

**Comment by coreybruce** [comment]
Ok but are you guys using Linux also? Also has anything changed since the version I tested on and should I got pull and recompile if anything was fixed? 

I'll also try it through steam and see if it works

**Comment by Hat-Kid** [comment]
I'm on Arch and both my DualShock 4 and DualSense controllers work with Bluetooth out of the box without using Steam Input or any other software methods.

**Comment by coreybruce** [comment]
Alright I've downloaded the latest version but how does the extractor tool work again sorry?

**Comment by Hat-Kid** [comment]
`./extractor <iso-file>` or `./extractor -f <extracted-iso-folder>`

**Comment by coreybruce** [comment]
Thank you! i was having a issue with extractor but I realized it was because even tho I renamed the iso file to have no spaces I left one in by accident, I know you can do "" for a file with spaces but that was my fault there.

Hmm no with the latest release my xbox controller is still not being detected detected in the game and non steam games like sm64ex, alive_reversing and many others I have compiled on my own can see and use my controller just fine out of the box without needing xpadneo driver on Manjaro. Does this project use SDL2 for controllers at all?

**Comment by MojoJojoDojo** [comment]
> I run the game through steam and that makes my ds4 works fine with bluetooth so you could try that. However every time I've run the game without steam my ds4 only works with a usb connection.

I guess its not xbox controller specific then.
But yeah you have to install xpadneo for some reason to get it to work with an xbox one controller.
I think this issue should be reopened then.

**Comment by coreybruce** [comment]
Yeah I think it should also the game shouldn't also require xpadneo to be installed for xbox controllers but also seems to be affecting playstation controllers if people are reporting a issue also

**Comment by meunierd** [comment]
I'm unable to use my 8bitdo SF30 which works on... basically everything.
