### ISSUE TITLE
Failed to build on Manjaro

### ISSUE THREAD

**Issue by coreybruce** [open-goal/jak-project#1477]
Hi I just wanted to get some help compiling this on Manjaro also you were missing the dependency doxygen in the Arch dependencies mentioned.

Here is my log also

```
cmake -B build && cmake --build build -j 8
-- GCC detected! Adding compile flags
Code Coverage build is disabled!
-- Found Doxygen: /usr/bin/doxygen (found version "1.9.3") found components: doxygen missing components: dot
-- Found Doxygen: /usr/bin/doxygen (found version "1.9.3") found components: doxygen 
-- Including X11 support
-- The ASM_NASM compiler identification is unknown
-- Didn't find assembler
CMake Error at game/CMakeLists.txt:4 (enable_language):
  No CMAKE_ASM_NASM_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "ASM_NASM" or the CMake cache entry CMAKE_ASM_NASM_COMPILER to the
  full path to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!
See also "/mnt/Storage/projects/jak-project/build/CMakeFiles/CMakeOutput.log".
See also "/mnt/Storage/projects/jak-project/build/CMakeFiles/CMakeError.log".
``` 
Is there anything else missing?

**Comment by Masamune3210** [comment]
you need nasm, or a assembler compatible with its output

**Comment by coreybruce** [comment]
I already have nasm installed so whats the problem then?

**Comment by Masamune3210** [comment]
Its either not correctly set up or not on your path or something else that is keeping cmake from being able to call it, its hard to tell and you would probably know the best how your system works since its gentoo so its kinda hard to give advice much

**Comment by coreybruce** [comment]
Haha have your coffee first :P

**Comment by coreybruce** [comment]
I will double check but I am pretty sure I installed nasm 

I compiled it on Arm64 Manjaro but got a different error

```
compress/zstd_decompress.c.o
[  7%] Building C object third-party/zstd/CMakeFiles/libzstd_static.dir/lib/decompress/zstd_decompress_block.c.o
[  7%] Linking CXX shared library libfmt.so
[  7%] Built target fmt
[  7%] Linking C static library liblibzstd_static.a
[  7%] Built target libzstd_static
make: *** [Makefile:146: all] Error 2
[corey@corey-pi4 jak-project]$ 
```

**Comment by Ziemas** [comment]
Only x86 is supported, so building on ARM wont work. (unless you're cross compiling for x86 I guess)

**Comment by coreybruce** [comment]
Yeah that's fair enough, I just wanted to test but will it support Arm64 later on?

> Only x86 is supported, so building on ARM wont work. (unless you're cross compiling for x86 I guess)

Back to the issue tho do you have any idea what's happening with the ```No CMAKE_ASM_NASM_COMPILER could be found.``` error? I cant seem to find anything that can help me

**Comment by water111** [comment]
Probably `nasm` is not installed. If you run `which nasm`, does it find anything?

**Comment by Ziemas** [comment]
> Yeah that's fair enough, I just wanted to test but will it support Arm64 later on?

Requires that someone writes an ARM backend for the goal compiler.

**Comment by coreybruce** [comment]
> Probably `nasm` is not installed. If you run `which nasm`, does it find anything?

![image](https://user-images.githubusercontent.com/8393780/174447915-a90fb1b5-c65b-44a3-a7a0-2d258c03d7f6.png)

```
which nasm                                                      
/usr/bin/nasm
```

**Comment by water111** [comment]
```
Tell CMake where to find the compiler by setting either the environment
  variable "ASM_NASM" or the CMake cache entry CMAKE_ASM_NASM_COMPILER to the
  full path to the compiler, or to the compiler name if it is in the PATH.
```
you could set `ASM_NASM` to point to `/usr/bin/nasm`

**Comment by coreybruce** [comment]
Oh ok how do I do that?

**Comment by coreybruce** [comment]
did a cmake clean and tried again and got this error instead

```
[ 22%] Building C object third-party/zydis/CMakeFiles/Zydis.dir/src/FormatterBase.c.o
At global scope:
cc1plus: note: unrecognized command-line option ‘-Wno-implicit-int-float-conversion’ may have been intended to silence earlier diagnostics
[ 22%] Linking CXX static library libcubeb.a
[ 22%] Built target cubeb
[ 23%] Building C object third-party/zydis/CMakeFiles/Zydis.dir/src/FormatterIntel.c.o
[ 23%] Linking C shared library libZydis.so
[ 23%] Built target Zydis
[ 23%] Linking CXX shared library libimgui.so
[ 23%] Built target imgui
make: *** [Makefile:146: all] Error 2
```

**Comment by water111** [comment]
the error happened earlier - the `note` is just a warning and can be ignored. Can you run make again and post the output?

**Comment by coreybruce** [comment]
Sure
 
```
cmake -B build && cmake --build build -j 8
-- GCC detected! Adding compile flags
Code Coverage build is disabled!
-- Found Doxygen: /usr/bin/doxygen (found version "1.9.3") found components: doxygen missing components: dot
-- Found Doxygen: /usr/bin/doxygen (found version "1.9.3") found components: doxygen 
-- Including X11 support
-- Configuring done
-- Generating done
-- Build files have been written to: /mnt/Storage/projects/jak-project/build
Consolidate compiler generated dependencies of target fmt
Consolidate compiler generated dependencies of target Zycore
Consolidate compiler generated dependencies of target replxx
Consolidate compiler generated dependencies of target libzstd_static
Consolidate compiler generated dependencies of target lzokay
Consolidate compiler generated dependencies of target gtest
Consolidate compiler generated dependencies of target speex
Consolidate compiler generated dependencies of target glfw
[  0%] Building CXX object third-party/lzokay/CMakeFiles/lzokay.dir/lzokay.cpp.o
[  1%] Built target fmt
[  2%] Built target gtest
[  3%] Built target Zycore
[  8%] Built target libzstd_static
[  8%] Built target speex
[ 10%] Built target replxx
[ 15%] Built target glfw
Consolidate compiler generated dependencies of target Zydis
Consolidate compiler generated dependencies of target cubeb
Consolidate compiler generated dependencies of target imgui
[ 16%] Generating API documentation with Doxygen
[ 16%] Built target docs
[ 19%] Built target cubeb
[ 22%] Built target Zydis
[ 23%] Built target imgui
/mnt/Storage/projects/jak-project/third-party/cubeb/cubeb/include/cubeb/cubeb.h:188: warning: Member cubeb_channel_layout (typedef) of file cubeb.h is not documented.
/mnt/Storage/projects/jak-project/third-party/cubeb/cubeb/include/cubeb/cubeb.h:166: warning: Member cubeb_channel (enumeration) of file cubeb.h is not documented.
/mnt/Storage/projects/jak-project/third-party/cubeb/cubeb/include/cubeb/cubeb.h:436: warning: argument 'user' of command @param is not found in the argument list of cubeb_device_changed_callback(void *user_ptr)
/mnt/Storage/projects/jak-project/third-party/cubeb/cubeb/include/cubeb/cubeb.h:436: warning: The following parameter of cubeb_device_changed_callback(void *user_ptr) is not documented:
  parameter 'user_ptr'
[ 23%] Building CXX object game/sound/CMakeFiles/sound.dir/989snd/player.cpp.o
[ 23%] Building CXX object game/sound/CMakeFiles/sound.dir/989snd/midi_handler.cpp.o
[ 23%] Building CXX object game/sound/CMakeFiles/sound.dir/989snd/ame_handler.cpp.o
[ 25%] Building CXX object game/sound/CMakeFiles/sound.dir/989snd/blocksound_handler.cpp.o
[ 25%] Building CXX object game/sound/CMakeFiles/sound.dir/989snd/musicbank.cpp.o
[ 25%] Built target doc
[ 25%] Built target clangformat
[ 25%] Building CXX object game/sound/CMakeFiles/sound.dir/989snd/sfxblock.cpp.o
[ 25%] Building CXX object game/sound/CMakeFiles/sound.dir/989snd/loader.cpp.o
/mnt/Storage/projects/jak-project/third-party/lzokay/lzokay.cpp: In member function ‘void lzokay::DictImpl::Match3Impl::init()’:
/mnt/Storage/projects/jak-project/third-party/lzokay/lzokay.cpp:342:27: error: no matching function for call to ‘begin(uint16_t [16384])’
  342 |       std::fill(std::begin(chain_sz), std::end(chain_sz), 0);
      |                 ~~~~~~~~~~^~~~~~~~~~
In file included from /usr/include/c++/12.1.0/bits/algorithmfwd.h:39,
                 from /usr/include/c++/12.1.0/bits/stl_algo.h:59,
                 from /usr/include/c++/12.1.0/algorithm:61,
                 from /mnt/Storage/projects/jak-project/third-party/lzokay/lzokay.cpp:3:
/usr/include/c++/12.1.0/initializer_list:90:5: note: candidate: ‘template<class _Tp> constexpr const _Tp* std::begin(initializer_list<_Tp>)’
   90 |     begin(initializer_list<_Tp> __ils) noexcept
      |     ^~~~~
/usr/include/c++/12.1.0/initializer_list:90:5: note:   template argument deduction/substitution failed:
/mnt/Storage/projects/jak-project/third-party/lzokay/lzokay.cpp:342:27: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘uint16_t*’ {aka ‘short unsigned int*’}
  342 |       std::fill(std::begin(chain_sz), std::end(chain_sz), 0);
      |                 ~~~~~~~~~~^~~~~~~~~~
/mnt/Storage/projects/jak-project/third-party/lzokay/lzokay.cpp:342:47: error: no matching function for call to ‘end(uint16_t [16384])’
  342 |       std::fill(std::begin(chain_sz), std::end(chain_sz), 0);
      |                                       ~~~~~~~~^~~~~~~~~~
/usr/include/c++/12.1.0/initializer_list:101:5: note: candidate: ‘template<class _Tp> constexpr const _Tp* std::end(initializer_list<_Tp>)’
  101 |     end(initializer_list<_Tp> __ils) noexcept
      |     ^~~
/usr/include/c++/12.1.0/initializer_list:101:5: note:   template argument deduction/substitution failed:
/mnt/Storage/projects/jak-project/third-party/lzokay/lzokay.cpp:342:47: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘uint16_t*’ {aka ‘short unsigned int*’}
  342 |       std::fill(std::begin(chain_sz), std::end(chain_sz), 0);
      |                                       ~~~~~~~~^~~~~~~~~~
/mnt/Storage/projects/jak-project/third-party/lzokay/lzokay.cpp: In member function ‘void lzokay::DictImpl::Match2Impl::init()’:
/mnt/Storage/projects/jak-project/third-party/lzokay/lzokay.cpp:373:27: error: no matching function for call to ‘begin(uint16_t [65536])’
  373 |       std::fill(std::begin(head), std::end(head), UINT16_MAX);
      |                 ~~~~~~~~~~^~~~~~
/usr/include/c++/12.1.0/initializer_list:90:5: note: candidate: ‘template<class _Tp> constexpr const _Tp* std::begin(initializer_list<_Tp>)’
   90 |     begin(initializer_list<_Tp> __ils) noexcept
      |     ^~~~~
/usr/include/c++/12.1.0/initializer_list:90:5: note:   template argument deduction/substitution failed:
/mnt/Storage/projects/jak-project/third-party/lzokay/lzokay.cpp:373:27: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘uint16_t*’ {aka ‘short unsigned int*’}
  373 |       std::fill(std::begin(head), std::end(head), UINT16_MAX);
      |                 ~~~~~~~~~~^~~~~~
/mnt/Storage/projects/jak-project/third-party/lzokay/lzokay.cpp:373:43: error: no matching function for call to ‘end(uint16_t [65536])’
  373 |       std::fill(std::begin(head), std::end(head), UINT16_MAX);
      |                                   ~~~~~~~~^~~~~~
/usr/include/c++/12.1.0/initializer_list:101:5: note: candidate: ‘template<class _Tp> constexpr const _Tp* std::end(initializer_list<_Tp>)’
  101 |     end(initializer_list<_Tp> __ils) noexcept
      |     ^~~
/usr/include/c++/12.1.0/initializer_list:101:5: note:   template argument deduction/substitution failed:
/mnt/Storage/projects/jak-project/third-party/lzokay/lzokay.cpp:373:43: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘uint16_t*’ {aka ‘short unsigned int*’}
  373 |       std::fill(std::begin(head), std::end(head), UINT16_MAX);
      |                                   ~~~~~~~~^~~~~~
/mnt/Storage/projects/jak-project/third-party/lzokay/lzokay.cpp: In member function ‘void lzokay::DictImpl::advance(lzokay::State&, uint32_t&, uint32_t&, uint32_t*, bool)’:
/mnt/Storage/projects/jak-project/third-party/lzokay/lzokay.cpp:486:35: error: no matching function for call to ‘begin(uint32_t [34])’
  486 |       for (auto posit = std::begin(best_pos) + 2, offit = best_off + 2;
      |                         ~~~~~~~~~~^~~~~~~~~~
/usr/include/c++/12.1.0/initializer_list:90:5: note: candidate: ‘template<class _Tp> constexpr const _Tp* std::begin(initializer_list<_Tp>)’
   90 |     begin(initializer_list<_Tp> __ils) noexcept
      |     ^~~~~
/usr/include/c++/12.1.0/initializer_list:90:5: note:   template argument deduction/substitution failed:
/mnt/Storage/projects/jak-project/third-party/lzokay/lzokay.cpp:486:35: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘uint32_t*’ {aka ‘unsigned int*’}
  486 |       for (auto posit = std::begin(best_pos) + 2, offit = best_off + 2;
      |                         ~~~~~~~~~~^~~~~~~~~~
/mnt/Storage/projects/jak-project/third-party/lzokay/lzokay.cpp:487:29: error: no matching function for call to ‘end(uint32_t [34])’
  487 |            posit != std::end(best_pos); ++posit, ++offit) {
      |                     ~~~~~~~~^~~~~~~~~~
/usr/include/c++/12.1.0/initializer_list:101:5: note: candidate: ‘template<class _Tp> constexpr const _Tp* std::end(initializer_list<_Tp>)’
  101 |     end(initializer_list<_Tp> __ils) noexcept
      |     ^~~
/usr/include/c++/12.1.0/initializer_list:101:5: note:   template argument deduction/substitution failed:
/mnt/Storage/projects/jak-project/third-party/lzokay/lzokay.cpp:487:29: note:   mismatched types ‘std::initializer_list<_Tp>’ and ‘uint32_t*’ {aka ‘unsigned int*’}
  487 |            posit != std::end(best_pos); ++posit, ++offit) {
      |                     ~~~~~~~~^~~~~~~~~~
/mnt/Storage/projects/jak-project/third-party/lzokay/lzokay.cpp:487:52: error: ‘offit’ was not declared in this scope; did you mean ‘off_t’?
  487 |            posit != std::end(best_pos); ++posit, ++offit) {
      |                                                    ^~~~~
      |                                                    off_t
/mnt/Storage/projects/jak-project/third-party/lzokay/lzokay.cpp:436:25: warning: unused parameter ‘best_off’ [-Wunused-parameter]
  436 |                uint32_t best_off[MaxMatchByLengthLen], bool skip) {
      |                ~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
make[2]: *** [third-party/lzokay/CMakeFiles/lzokay.dir/build.make:76: third-party/lzokay/CMakeFiles/lzokay.dir/lzokay.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:2197: third-party/lzokay/CMakeFiles/lzokay.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 25%] Building CXX object game/sound/CMakeFiles/sound.dir/989snd/vagvoice.cpp.o
[ 26%] Building CXX object game/sound/CMakeFiles/sound.dir/989snd/util.cpp.o
[ 26%] Building CXX object game/sound/CMakeFiles/sound.dir/common/synth.cpp.o
[ 26%] Building CXX object game/sound/CMakeFiles/sound.dir/common/voice.cpp.o
[ 26%] Building CXX object game/sound/CMakeFiles/sound.dir/common/envelope.cpp.o
[ 26%] Building CXX object game/sound/CMakeFiles/sound.dir/sndshim.cpp.o
[ 27%] Building CXX object game/sound/CMakeFiles/sound.dir/sdshim.cpp.o
[ 27%] Linking CXX static library libsound.a
[ 27%] Built target sound
make: *** [Makefile:146: all] Error 2
```

**Comment by Hat-Kid** [comment]
You should be able to add `#include <array>` to `lzokay.cpp` for now to fix that particular error. The version of `lzokay` in this repo is a bit older and breaks on newer versions of GCC or Clang.

**Comment by coreybruce** [comment]
Yep can confirm that allowed it to compile

**Comment by Hat-Kid** [comment]
> So where is the binary and extractor binary?

They should be in the `build` directory. The extractor is in `build/decompiler` and the runtime is in `build/game` (called `gk`).

**Comment by Hat-Kid** [comment]
The project is x86_64 only.

**Comment by coreybruce** [comment]
Oh so it doesn't support 32bit x86 either? but why doesn't it support 32bit x86?

**Comment by ManDude** [comment]
Because we make use of 64-bit registers, instructions and and addressing space.

**Comment by coreybruce** [comment]
Ah I see, I know I have already sort of asked but like other projects like RE3 or Devilutionx which can compile for multiple architectures with no issues, will this project ever get that kind of code changes to do that later on?

**Comment by ManDude** [comment]
If someone else wants to do it, sure. But we're not planning on it.

**Comment by coreybruce** [comment]
Ok thanks for the update

**Comment by xTVaser** [comment]
The fix to the lzokay library has been merged into master https://github.com/open-goal/jak-project/pull/1530 

So the actual underlying build issue appears to be resolved https://github.com/open-goal/jak-project/issues/1477#issuecomment-1159754272

Closing as there doesn't seem to be an outstanding issue here anymore?  Feel free to re-open if im mistaken.

**Comment by coreybruce** [comment]
> Because we make use of 64-bit registers, instructions and and addressing space.

Are you guys using assembly? shouldn't the OS manage the pointers and registers?

**Comment by water111** [comment]
This question keeps coming up so I'll give a real answer for why it's not easy for this project to support other architectures.

- all of the GOAL code (about 400,000 lines) is compiled with a compiler that we wrote, which only targets x86_64 https://github.com/open-goal/jak-project/tree/master/goalc/emitter https://github.com/open-goal/jak-project/tree/master/goalc/regalloc
- GOAL has its own implementation of threads and stuff like `throw`/`catch`. Context switching to change threads is inherently processor specific. The original game did this for MIPS processors and we rewrote it for x86_64. https://github.com/open-goal/jak-project/blob/master/goal_src/jak1/kernel/gkernel.gc https://github.com/open-goal/jak-project/blob/master/goal_src/jak1/kernel/gstate.gc 
- There's some assembly functions that let us call GOAL code from C++ https://github.com/open-goal/jak-project/blob/master/game/kernel/asm_funcs.asm
- There's a few places where I used x86-specific intrinsics for graphics stuff https://github.com/open-goal/jak-project/blob/master/game/graphics/opengl_renderer/background/background_common.cpp#L323
- GOAL loads code at runtime and we wrote our own dynamic linker. This has to be processor specific https://github.com/open-goal/jak-project/blob/master/game/kernel/jak1/klink.cpp

**Comment by coreybruce** [comment]
Wait so why did you write your own compiler instead of using a mature compile like GCC? you've made it harder for yourself and is modular. This would allow you to easily port it to different architectures with far less work as it's already done in GCC

**Comment by Biggamer11** [comment]
As someone who is a software engineer for a living this is just stupid, a word of advice is restandardize on GCC or something that is mature.

**Comment by water111** [comment]
The game is written in GOAL, which is a custom programming language developed by naughty dog and not supported by gcc or clang or any existing compiler.  Did you even look at the code or read the first sentences of the readme? It's all a custom lisp language and the point of the project was to port this custom language to x86.

**Comment by coreybruce** [comment]
We're just figuring out how it all works and just asking questions on how it all works to get a better understanding. Would it have to use this custom language to work?

**Comment by Biggamer11** [comment]
Sorry if I misunderstood something, I’m getting this secondhand from @coreybruce. But can’t this be reimplement in something like c++, I’m looking for answers mostly I’m not here to troll

**Comment by Hat-Kid** [comment]
The point of the project is to port Naughty Dog's custom language to x86, not to port the game's codebase to C++.

**Comment by coreybruce** [comment]
Yeah @Biggamer11 has a lot more skills when it comes to this but I am also just wanting to help and ask questions as this is a awesome project and wish to help improve anyways I can :)

**Comment by Biggamer11** [comment]
What about transpiler to convert it to code to something intermediate to be compiled on gcc that way you could possibly have something that can use the custom language and have portablity

**Comment by water111** [comment]
Understandable, but please take a few moments to read some code or the readme first.
In case you haven't seen what the game code looks like, here is the game's main:
https://github.com/open-goal/jak-project/blob/master/goal_src/jak1/engine/game/main.gc

There's 400,000 lines of this type of code in jak 1, and we think that jak 2 will be about 1 million lines. Porting it to C++ is not very easy because there are a ton of weird features in their language that C++ doesn't support.  It is, of course, technically possible to reimplement all their stuff in C++ but we'd have to rework a lot of the engine to actually be possible in C++.

I decided not to try porting it to C++ because:
- I think it would be much more effort overall
- I wanted to write a compiler
- I wanted to figure out why Naughty Dog wrote their own language and see what it would be like

**Comment by coreybruce** [comment]
What features in C++ would you need exactly?

**Comment by xTVaser** [comment]
On the topic of using an IR / transpiler (like LLVM).  This question has been asked before a few times, here was the response that is hopefully informative:
> I definitely thought about using LLVM, but decided against it for two reasons - it's a little bit annoying to set up and use, and it wasn't clear how to make it do what I wanted in all cases.  In GOAL, several registers are used for very specific things. There is a "symbol table" register that always points to the symbol table, a "process" register that always points to the currently running process, and in OpenGOAL, an "offset" register that always points to the base of memory (so OpenGOAL "pointers" are actually 32-bit offsets from the 64-bit memory address).  The other challenge is that OpenGOAL code has its own object file format that can be loaded / unloaded at runtime.  For a number of reasons, the format used by shared libraries on Linux won't work, and it seemed like a challenge to add a custom object file format to LLVM.  I mostly just copied the file format used in GOAL.

**Comment by coreybruce** [comment]
I'm passionate about this game and I apologize if it comes across as confrontational. It wasn’t my intention. Best of luck to your project and wish it success.

**Comment by water111** [comment]
GOAL's weird features that don't map well to c++ are:
- coroutines (technically supported in c++20, but wasn't widely supported when the project was started)
- tagged pointers
- 128-bit bitfields
- nonlocal control flow (jump from the middle of one function to another)
- well-defined behavior when type-punning
- lisp-style symbol table (can iterate over all global variables/functions or get them by name)
- compacting garbage collection for stacks
- ability to copy a threads stack
- ability to reset a thread's stack to the beginning and start again
- ability to temporarily run functions on another thread's stack
- inline assembly
- runtime type system with types and functions as runtime objects
- being able to store things other than methods in vtables
- ability to load code at runtime with a multi-threaded linker
- ability to edit code in a single file and replace that file in the running game, without dropping any frames
- ability to easily embed objects with complex data structures (trees, linked lists, runtime type information) into files
- compile-time macros that can do stuff like "convert the first 8 characters of a string into a uint64". 

some of these could be solved with clever c++, but these aren't the sort of problems I'm interested in solving.

In the end our objective isn't to make jak and daxter playable on as many computers as possible - it's more about the tools they used to develop the game.

**Comment by water111** [comment]
> I'm passionate about this game and I apologize if it comes across as confrontational. It wasn’t my intention. Best of luck to your project and wish it success.

no worries - we're aware that our approach isn't the best for everyone's use case, but it's a tradeoff that we're happy with.
