### ISSUE TITLE
[sound] No sound in EndeavourOS with i3wm.

### ISSUE THREAD

**Issue by VenerableCrow** [open-goal/jak-project#1478]
Basically, i load the game and it runs perfectly except the sound, wich is missing entirely.

**Comment by Hat-Kid** [comment]
Are you on the release build? What audio backend do you use? If you use Pipewire, make sure you also have a `pipewire-pulse` package and use the latest release.

**Comment by VenerableCrow** [comment]
> Are you on the release build? What audio backend do you use? If you use Pipewire, make sure you also have a `pipewire-pulse` package and use the latest release.

My bad, i was using the 0.1.4, once downloaded the 0.1.5 everything went smooth, thanks for the port btw.
