### ISSUE TITLE
couldnt locate decompiler executable in out/build/release/bin/decompiler

### ISSUE THREAD

**Issue by SkullWolfSteam** [open-goal/jak-project#1483]
### Describe the Bug

G:\Jak PROJECT>task extract-jak1
←[35mtask: Couldn't locate decompiler executable in './out/build/Release/bin/decompiler'
←[0m←[31mtask: precondition not met
←[0m
G:\Jak PROJECT>

### How To Reproduce

i just tried to do it after doing the previous steps then moving the folder from my f drive to the USB drive as some idiot locked up my f drive so i cant open commandprompts on it so i moved it there tried to extract my jak 1 iso and got that stupid error? note i got the iso from vims vault so it should be good

### Expected Behavior

when i go to do the  g/jak project>task extract-jak1 like it says it should allow me to do it instead of not locating some decomp;lier executable in ./out/build/release/bin/decomplier'

### Operating System

windows 10 pro

### OpenGOAL Version

Release

### Game Version

NTSC 1.0 (black label)

**Comment by ManDude** [comment]
It looks like you're building from source. Make sure you followed the instructions correctly and that you actually moved all the folders properly.

**Comment by SAlesci** [comment]
It might not be that obvious, but are you sure the compiled code has been placed in the correct path? Talking about the build/**_release_**/bin part, depending on the configuration of your compiler the folder might not be "**_release_**" but something else.

**Comment by SkullWolfSteam** [comment]
in the end i just figured out i could just use a already built ver instead of building from source and got that to work just fine (i didn't know it was a thing till after i posted this bug for the building from source ver)
