### ISSUE TITLE
150FPS slow motion

### ISSUE THREAD

**Issue by nameonascreen** [open-goal/jak-project#1492]
### Describe the Bug

Prolly more ways to reproduce this, but after roll jumping jak will go into a slow motion state

### How To Reproduce

Set Framelimiter to 150FPS
Roll Jump and continue moving in any direction

### Expected Behavior

after a roll jump jak should be moving at his normal speed

### Operating System

Windows 11

### OpenGOAL Version

Release

### Game Version

NTSC 1.0 (black label)

**Comment by Brent-Hickey** [comment]
Target.gc converts jak's velocity using (-> *display* seconds-per-frame). I've noticed that if I adjust seconds-per-frame to match the 60fps version this problem goes away. I'm checking if it breaks other stuff 

The roll jump walk squish in particular is from this area. unknown-float01 is jak's xz velocity
```(until (ja-done? 0)
                 (suspend)
                 (ja :num! (seek! max (/ (* (fmax 20480.0 (-> self control unknown-float01)) (-> *display* seconds-per-frame))
                                        (/ (-> *TARGET-bank* run-up-cycle-dist) (-> *TARGET-bank* run-cycle-length))
                                        )
                                 )
                     )
                 )```
