### ISSUE TITLE
Need help getting started, can't run test.sh?

### ISSUE THREAD

**Issue by BitGrub** [open-goal/jak-project#1501]
### Describe the Bug

Disclaimers: I am running this on Windows11 through WSL2 Ubuntu. All dependencies listed have been installed. I am a complete noob, and also pretty stupid. 

Anyway, here's what my CLI looks like, starting from a manually created "build" directory inside the cloned github:

> ➜  build git:(master) cmake -DCMAKE_SHARED_LINKER_FLAGS="-fuse-ld=lld" -DCMAKE_EXE_LINKER_FLAGS="-fuse-ld=lld" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ ..
> -- The C compiler identification is Clang 10.0.0
> -- The CXX compiler identification is Clang 10.0.0
> -- Check for working C compiler: /usr/bin/clang
> -- Check for working C compiler: /usr/bin/clang -- works
> -- Detecting C compiler ABI info
> -- Detecting C compiler ABI info - done
> -- Detecting C compile features
> -- Detecting C compile features - done
> -- Check for working CXX compiler: /usr/bin/clang++
> -- Check for working CXX compiler: /usr/bin/clang++ -- works
> -- Detecting CXX compiler ABI info
> -- Detecting CXX compiler ABI info - done
> -- Detecting CXX compile features
> -- Detecting CXX compile features - done
> -- GCC detected! Adding compile flags
> Code Coverage build is disabled!
> -- Looking for pthread.h
> -- Looking for pthread.h - found
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD
> -- Performing Test CMAKE_HAVE_LIBC_PTHREAD - Failed
> -- Looking for pthread_create in pthreads
> -- Looking for pthread_create in pthreads - not found
> -- Looking for pthread_create in pthread
> -- Looking for pthread_create in pthread - found
> -- Found Threads: TRUE
> -- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY
> -- Performing Test COMPILER_HAS_HIDDEN_VISIBILITY - Success
> -- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY
> -- Performing Test COMPILER_HAS_HIDDEN_INLINE_VISIBILITY - Success
> -- Performing Test COMPILER_HAS_DEPRECATED_ATTR
> -- Performing Test COMPILER_HAS_DEPRECATED_ATTR - Success
> -- Check if compiler accepts -pthread
> -- Check if compiler accepts -pthread - yes
> -- Looking for include file pulse/pulseaudio.h
> -- Looking for include file pulse/pulseaudio.h - not found
> -- Looking for include file alsa/asoundlib.h
> -- Looking for include file alsa/asoundlib.h - not found
> -- Looking for include file jack/jack.h
> -- Looking for include file jack/jack.h - not found
> -- Looking for include file sndio.h
> -- Looking for include file sndio.h - not found
> -- Looking for include file aaudio/AAudio.h
> -- Looking for include file aaudio/AAudio.h - not found
> -- Looking for include file AudioUnit/AudioUnit.h
> -- Looking for include file AudioUnit/AudioUnit.h - not found
> -- Looking for include file audioclient.h
> -- Looking for include file audioclient.h - not found
> -- Looking for include files windows.h, mmsystem.h
> -- Looking for include files windows.h, mmsystem.h - not found
> -- Looking for include file SLES/OpenSLES.h
> -- Looking for include file SLES/OpenSLES.h - not found
> -- Looking for include file sys/soundcard.h
> -- Looking for include file sys/soundcard.h - found
> -- Looking for include file android/log.h
> -- Looking for include file android/log.h - not found
> -- Looking for include file sys/audioio.h
> -- Looking for include file sys/audioio.h - not found
> -- Looking for include file kai.h
> -- Looking for include file kai.h - not found
> -- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
> -- Could NOT find Doxygen (missing: DOXYGEN_EXECUTABLE)
> -- Including X11 support
> -- Found X11: /usr/include
> -- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so
> -- Looking for XOpenDisplay in /usr/lib/x86_64-linux-gnu/libX11.so;/usr/lib/x86_64-linux-gnu/libXext.so - found
> -- Looking for gethostbyname
> -- Looking for gethostbyname - found
> -- Looking for connect
> -- Looking for connect - found
> -- Looking for remove
> -- Looking for remove - found
> -- Looking for shmat
> -- Looking for shmat - found
> -- The ASM_NASM compiler identification is NASM
> -- Found assembler: /usr/bin/nasm
> -- Found Git: /usr/bin/git (found version "2.25.1")
> -- Found Python: /usr/bin/python3.8 (found version "3.8.10") found components: Interpreter
> no rapidjson, download
> -- Configuring done
> -- Generating done
> -- Build files have been written to: /home/BitGrub/Downloads/jak-project/build
> ➜  build git:(master) ls
> .   CMakeCache.txt  CTestTestfile.cmake    Makefile  bin                  common      exports  goalc  third-party
> ..  CMakeFiles      DartConfiguration.tcl  Testing   cmake_install.cmake  decompiler  game     lib    tools
> ➜  build git:(master) cd ..
> **➜  jak-project git:(master) ./test.sh
> ./test.sh: line 6: /home/BitGrub/Downloads/jak-project/build/goalc-test: No such file or directory**
> ➜  jak-project git:(master) cd build
> ➜  build git:(master) ls
> .   CMakeCache.txt  CTestTestfile.cmake    Makefile  bin                  common      exports  goalc  third-party
> ..  CMakeFiles      DartConfiguration.tcl  Testing   cmake_install.cmake  decompiler  game     lib    tools

### How To Reproduce

Happens every time. If I follow the instructions for the "significantly slower, slow-code generating, and having worse warning messaging" method, I can run test.sh just fine (all tests come up positive)

### Expected Behavior

Sorry for clogging up your issues with a help request post. I'm just incredibly curious/excited to try this out

### Operating System

Windows 11 22000.739, Ubuntu 20.04.4

### OpenGOAL Version

Compiled from source

### Game Version

PAL

**Comment by ManDude** [comment]
The shell files are for linux. The windows version uses the batch files.

**Comment by BitGrub** [comment]
> The shell files are for linux. The windows version uses the batch files.

I agree

**Comment by xTVaser** [comment]
What are you hoping to achieve -- just play the game?  If so you just need to download the latest release https://github.com/open-goal/jak-project/releases and drag your ISO onto `extractor.exe` and once it finishes, run `gk.exe`

Note that the current latest release at the time of writing does not support the PAL version yet.

**Comment by ManDude** [comment]
Yeah... I'm not sure we really care about making the shell files work on a linux VM inside Windows, or vice versa.

**Comment by BitGrub** [comment]
To be honest I'm more interested in getting it running (compiling and building it) than actually playing it, I've already got the PS3 release for that. Curiosity and all that.

The PAL thing is a (temporary) bummer, but I'm sure I can source an NTSC version, thanks for letting me know.

Last question, is there a way to force building with AVX2 instructions or is that actually (still?) broken at the moment?

**Comment by xTVaser** [comment]
The performance difference between AVX and AVX2 at the moment is probably negligible, but if you're interested in it, it's possible.

We don't have an easy switch to flip as far as I know.  You'd have to dig into the CMake (atleast the root cmake file) to override some flags.

**Comment by water111** [comment]
building with AVX2 is supported, just change `-mavx` in `CMakeLists.txt` to `-mavx2`. But the performance difference is quite small.  But as vaser said, it's probably not really worth it.
