### ISSUE TITLE
Hanging on these two ledges(maybe more?) cause the camera to bug out. 

### ISSUE THREAD

**Issue by deepsea1** [open-goal/jak-project#1510]
### Describe the Bug

Hanging on these two ledges in Forbidden Jungle seem to cause the camera to bug out

https://user-images.githubusercontent.com/34739772/174786629-43feedc4-570d-40e2-8dba-c71cb951759d.mp4

### How To Reproduce

this is in the first half of the temple. when you first enter it. the effect seems to worsen on higher fps although happens on 60FPS.

### Expected Behavior

your camera will start spinning uncontrollably

### Operating System

Windows 10

### OpenGOAL Version

Release

### Game Version

NTSC 1.0 (black label)

**Comment by ManDude** [comment]
Doesn't seem to be our fault.
