### ISSUE TITLE
[subtitle editor] Crash when the current or base language != 0

### ISSUE THREAD

**Issue by towai** [open-goal/jak-project#1519]
Issue is described in https://github.com/open-goal/jak-project/pull/1516#issuecomment-1163009240

**Comment by xTVaser** [comment]
I could be wrong -- but im pretty sure this isn't specifically if it's `!= 0` it's if the value doesn't have subtitles defined for it yet.

The editor uses the files as a source of truth, so you need to atleast make an empty file first.  The solution is to change these fields to dropdowns

**Comment by towai** [comment]
> I could be wrong -- but im pretty sure this isn't specifically because it's `!= 0` it's if the value doesn't have subtitles defined for it yet.
> 
> The editor uses the files as a source of truth, so you need to atleast make an empty file (with the `language-id` definition) first.  The solution is to change these fields to dropdowns

right, I kind of figured that was also part of the cause. ideally the drop-down would also contain some string constant associated with each language to tell you which it is, because I have no idea what language "1" or "2" is (even though you could look in the file, it would be nice)

**Comment by ManDude** [comment]
Wouldn't recommend snooping in the filenames simply because they're not actually standardized and you can call them whatever you want.

**Comment by xTVaser** [comment]
> because I have no idea what language "1" or "2" is (could do this by looking at the filename and getting the two-letter language code)

A separate issue imo, this can be solved by adding a feature to setup a new file using the following enum - https://github.com/open-goal/jak-project/blob/master/goal_src/pc/pckernel-h.gc#L78

Though it would probably take less time to just initialize an empty file for each
