### ISSUE TITLE
2 Powercells Are Impossible To Obtain

### ISSUE THREAD

**Issue by EliteZalba** [open-goal/jak-project#1524]
### Describe the Bug

The 1st powercell that is impossible to obtain is the 1st powercell in the Precursor Basin, obtained by herding all of the moles into their hole.  The moles can be herded, seemingly correctly, but they don't ever burrow back into their hole.  I've seen playthroughs online where there is quite a bit of tolerance with how close the mole has to be to burrow back into the hole, but in my current playthrough, they will literally walk dead center over the hole, without burrowing.

The 2nd powercell that is impossible to obtain is the 7th (2nd to last) in the Volcanic Crater.  The powercell description is hidden, but it is the powercell contained in a metal box that is located 180 degrees behind the opening to Spider Cave.  It requires entering Spider Cave, filling up on a yellow eco vent, and shooting a projectile at the metal box to break it open and reveal the powercell.  The bug is regarding the hitbox of the metal crate.  There is an invisible barrier directly in front of the metal box that prevents any yellow eco projectiles from making contact with and breaking open the metal box.

*Not sure which OpenGOAL version it is, but I followed the windows setup guide exactly on 6/19/22.  I'm assuming this is the released version. 

### How To Reproduce

The steps to reproduce the behavior are simply by attempting to obtain the respective powercells.  Attempting to herd the moles should show that they don't burrow back into their hole, and attempting to fill up on a yellow eco vent and shooting a projectile at the metal crate in the Volcanic Crater should reveal the barrier blocking the yellow eco projectiles from hitting the metal box.

### Expected Behavior

Precursor Basin powercell: forcing a mole to walk very near to or directly over the hole won't trigger the burrow animation.

Volcanic Crater powercell: shooting a yellow eco vent projectile at the metal box will result in the yellow eco projectile being blocked by an invisible barrier, and the metal box will remain unbroken.

### Operating System

Windows 10, Version 21H2, OS Build 19044.1766

### OpenGOAL Version

Release

### Game Version

NTSC 1.0 (black label)

**Comment by djak250** [comment]
I just completed the mole mission, on steam deck. It was difficult but they did eventually find their way home. For what it's worth.

**Comment by gsilver0** [comment]
I had no issues with the mole mission.

**Comment by BreakPoints** [comment]
Sounds like a 150FPS bug, was able to grab all 100 power cells in a pre 150FPS build.

**Comment by Kringuskrang** [comment]
I ran into a similar issue. On the last flying lurker, the power cell is tracked to the lurker as soon as you kill it, playing the power cell dropping "cutscene" and making it continue to fly the course of the lurker. The only way to escape is to close the game, I've tried resetting multiple times, I've tried using the cutscene skip in debug mode, unsure of any other way to get the cell without quitting.

**Comment by NessieNep** [comment]
I was able to get both of those powercells (though they took a lot of effort and patience. You just have to hit the box above where you would normally be able to afaik. As for the mole, a lot of patience and luck tbh).

The powercell I'm unable to get no matter what atm is the one in the basin where you have to kill the flying lurkers. I kill the last one and the power cell pops out but it still takes the same AI path as the last lurker killed and the cutscene follows it in an unskippable endless loop. This effectively soft locks the game and I have to restart.

**Comment by jmaloy97** [comment]
I was able to get all 101 power cells at a consistent 75 fps. The moles in the Precursor Basin had to be lead to the right angle for them to go in, but they went in just fine.
