### ISSUE TITLE
Game crash

### ISSUE THREAD

**Issue by Salvok27** [open-goal/jak-project#1528]
### Describe the Bug

when i start gk.exe the game starts quietly but only where there is jack dragging the naughtydog logo or when i am in the first level when samos crosses the portal i do 2 steps and the game closes

### How To Reproduce

the game starts and closes

### Expected Behavior

when I start the game

### Operating System

windows 10

### OpenGOAL Version

Release

### Game Version

PAL

**Comment by ManDude** [comment]
Does anything appear on the console?

Also, PAL isn't properly supported right now.

**Comment by Zedb0T** [comment]
@Salvok27 Can you try with a fresh installation of the newest version? 

PAL Support has been added in the newest version

**Comment by water111** [comment]
Is this still happening on the latest version?

**Comment by ManDude** [comment]
Well... idk. Hard to fix a bug when the person reporting doesn't cooperate lol.
