### ISSUE TITLE
api-ms-win-core-file-l1-2-2.dll missing on windows 8.1

### ISSUE THREAD

**Issue by BoxDrawer** [open-goal/jak-project#1529]
### Describe the Bug

When using the extractor from the releases (tried with v0.1.6 and v0.1.9) it says that api-ms-win-core-file-l1-2-2.dll is missing.

It may be related to this SDK issue:
https://stackoverflow.com/questions/69943334/newer-windows-sdks-cause-api-ms-win-core-file-l1-2-2-dll-missing-on-windows-7-8

### How To Reproduce

Try to use the extractor with windows 7/8/8.1

### Expected Behavior

The program shuld run normally as in windows 10 and 11.

### Operating System

Windows 8.1

### OpenGOAL Version

Release

### Game Version

NTSC 1.0 (black label)

**Comment by water111** [comment]
the project only supports windows 10 and newer, unfortunately.

**Comment by ManDude** [comment]
I did try to see if I could make it win7 compatible, but evidently it didn't work and sadly I have no clue how to fix that.
