### ISSUE TITLE
Can't Change Resolution in Fullscreen Mode

### ISSUE THREAD

**Issue by perrinpagess** [open-goal/jak-project#1537]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

When in fullscreen or borderless mode, the display native resolution is always used for rendering. Selecting a resolution from the menu does nothing.

### How To Reproduce

Enable fullscreen or borderless mode and attempt to set the resolution. 

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

When in fullscreen or borderless mode, the game is rendered at the selected resolution then scaled to native resolution. 

### Operating System

Windows 11

### OpenGOAL Version

0.1.9

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

No

**Comment by ManDude** [comment]
Known. Requires #1197 

In the meantime, use something like VSR in your gpu.

**Comment by perrinpagess** [comment]
I think we misunderstand each other. I mean running the game at a lower resolution then scaling to native. Is it something that requires separate screen and render buffer, too?
