### ISSUE TITLE
Flying Lurker Quest ends with Endless Looping cutscene.

### ISSUE THREAD

**Issue by NessieNep** [open-goal/jak-project#1541]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

The powercell I'm unable to get no matter what atm is the one in the basin where you have to kill the flying lurkers. I kill the last one and the power cell pops out but it still takes the same AI path as the last lurker killed and the cutscene follows it in an unskippable endless loop. This effectively soft locks the game and I have to restart.

### How To Reproduce

Try completing the basin lurker mission via killing all of the flying lurkers. If it works normally, try on a high refresh rate monitor (I use a 200hz monitor).

### Does this problem occur on original hardware or PCSX2?

Didn't check

### Expected Behavior

The cutscene not looping and the player being able to get the powercell for that mission.

### Operating System

Windows

### OpenGOAL Version

1.6 and 1.9 release versions

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

Yes

**Comment by Zedb0T** [comment]
This is a known issue with the experimental 150 FPS setting, there is currently a PR merged into main that will make the default the stable 60 FPS again until some of these bugs get ironed out.
