### ISSUE TITLE
[150FPS] Lower than 150FPS causes game to run too fast

### ISSUE THREAD

**Issue by BreakPoints** [open-goal/jak-project#1543]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

The new option to limit the framerate doesn't actually limit the framerate but does adjust the speed of the game. This makes the game run 2 or 3 times faster than it should depending having 100FPS or 60FPS set.

### How To Reproduce

Launch game on high refresh monitor and make sure FPS is set to any option other than 150FPS in settings.

### Does this problem occur on original hardware or PCSX2?

Not needed, bug is obvious

### Expected Behavior

Game to run at normal speeds at FPS other than 150.

### Operating System

Windows 10 21H2 (shouldn't be OS specific)

### OpenGOAL Version

0.1.10

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

Yes

**Comment by ManDude** [comment]
You need to press the "apply" button in the frame limiter options to match the frame rate you have picked.

**Comment by BreakPoints** [comment]
Probably best I made an issue for this because I'm sure others will run into this problem as by default, without changing any settings my game was running at 3 times speed.

Having to manipulate FPS settings between two different menus is not obvious. Maybe the main menu option should automatically set the frame limit to the same FPS and apply when it is changed.

**Comment by ManDude** [comment]
Yes, the feature is still in development and having different menus that affect different things helps with debugging and figuring out what is or isn't wrong.
