### ISSUE TITLE
SFX not working when changing language

### ISSUE THREAD

**Issue by OngakuGH** [open-goal/jak-project#1544]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Each time I try to change the language, the game stops to reproduce any sfx sounds (like voices or menu sounds)

### How To Reproduce

Change the language inside the game menu. (Sound options -> language)

### Does this problem occur on original hardware or PCSX2?

Not needed, bug is obvious

### Expected Behavior

The audio should still work for each language.

### Operating System

Windows 10

### OpenGOAL Version

v0.1.10

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

Yes

**Comment by ManDude** [comment]
oops
