### ISSUE TITLE
[Graphics] V-sync does not cap to monitors frequency

### ISSUE THREAD

**Issue by BreakPoints** [open-goal/jak-project#1557]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

When v-sync is enabled and running at 150FPS, the game still appears to be outputting at 150FPS on a 144Hz monitor rather than 144FPS, as I believe it did in the past.

### How To Reproduce

Enable v-sync and an FPS mode above that of your monitor then use the frametime plot to confirm the framerate.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

V-sync should limit the game to the monitors refresh rate.

### Operating System

Windows 10 21H2

### OpenGOAL Version

0.1.12

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

Yes

**Comment by ManDude** [comment]
The game can't run at 144FPS. 150FPS mode means 150FPS.

**Comment by BreakPoints** [comment]
Yes but can the presentation of frames be limited to hit V-sync through discarding?

Feel free to close the issue if it is not useful

**Comment by BreakPoints** [comment]
This seems to have been fixed by #1643, the game will now cap to 144FPS in 150FPS mode in exclusive fullscreen + V-sync
