### ISSUE TITLE
0SUBTIT.TXT has reached a size that causes an assert fail on link

### ISSUE THREAD

**Issue by towai** [open-goal/jak-project#1565]
I've been continuing to add subtitles to hub 3 as I go through a relatively leisurely-paced 100% run for that purpose. Tonight I reached the end of Lava Tube and subtitled the cutscene that plays there. After I saved, the game closed with an assertion fail at ~~klink.cpp:563~~ klink.cpp:255:
https://github.com/open-goal/jak-project/blob/944edd59386ef677824afa992364155b3c2c225f/game/kernel/common/klink.cpp#L249-L256
This happens on every launch until you remove or comment out enough stuff and remake the text segment using the repl.

My 0SUBTIT.TXT is 122 KB (125,424 bytes). If I add ***a single character*** to line 2650, 2651 or 2654 of my 
[game_subtitle_en.gd](https://github.com/open-goal/jak-project/files/8990373/game_subtitle_en.gd.txt) and remake it, the game won't launch. That and adding a Clear Screen instruction both result in the same change in size (up to 125,440 bytes).
Not every addition or removal of a character results in the file changing size, either (hence the ends of those particular lines). I'm assuming that's because some things are padded for byte alignment to make lookups easier, or that sort of thing.

**Comment by ManDude** [comment]
Increase the heap size in `subtitle.gc`.

**Comment by towai** [comment]
yeah, that seems obvious now. i'm not sure i'd even ever looked at that file. after i'm done with this go round, english needs another pass through each level of the game looking at the files to get any subtitles that haven't been encountered, but i think 192K should be plenty of space.

**Comment by ManDude** [comment]
Yep, set it to 192K for now.
