### ISSUE TITLE
Extractor not Opening

### ISSUE THREAD

**Issue by JojoFreestar** [open-goal/jak-project#1574]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Im trying to run the extractor to get the iso but the extractor when clicked wont open. I have tried running it as administrator but nothing seems to work.

### How To Reproduce

https://www.youtube.com/watch?v=nB_24yXVKtc

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

extractor opens

### Operating System

windows 10

### OpenGOAL Version

v0.1.12

### Game Version

PAL

### Are you using a high refresh-rate monitor (>60Hz)

Yes

**Comment by Zedb0T** [comment]
Drag the iso onto the extractor, you are just opening it without passing it any arguments.

**Comment by Zedb0T** [comment]
Taken from #rules in the opengoal discord:

 How to dump your Jak and Daxter Disc 
https://pcsx2.net/guides/basic-setup/#dumping-ps2-discs-via-imgburn

 Ask for help in help-and-questions
Or watch these helpful videos:
How to Install - https://www.youtube.com/watch?v=yQBKCnS5MDY
