### ISSUE TITLE
Multidraw graphics crash

### ISSUE THREAD

**Issue by Schatteneis** [open-goal/jak-project#1577]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

playing the intro sequence crashes the video driver

### How To Reproduce

play the intro sequence, at about a minute and 8 seconds in the driver crashes

### Does this problem occur on original hardware or PCSX2?

Not needed, bug is obvious

### Expected Behavior

the driver should not crash

### Operating System

Axyl Linux (Arch based)

### OpenGOAL Version

0.1.12 and 870be7151a836d9a85f0c570f49564ad8c9ae782

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

No

**Comment by Schatteneis** [comment]
seems like this issue isn't limited to arch Linux, i tried it with Linux mint and the driver crashes there too. the driver crashes when the sage says "careful research" and the camera pans. going to the beach near the village also crashes the driver...
i assume it's an driver crash because when it happens the screen turns black, then the previous frame with messed up colors

**Comment by ManDude** [comment]
What gpu do you have? Does the issue happen if you go to the top bar > Windows > Render Debug and turn on "use old multidraw"?

**Comment by Schatteneis** [comment]
i have an RX 480 Nitro and j already happen to have reinstalled windows to
try it out on there

ManDude ***@***.***> schrieb am Mi., 29. Juni 2022, 15:36:

**Comment by OkeanGames** [comment]
That is the only critical issue I do crash always at this scene
![QwwBxps](https://user-images.githubusercontent.com/2992753/176458750-6f4b6dfd-8eb4-48a6-bd5b-59bbdfe2c6e8.png)

My GPU is an Vega 56 Pulse

The fix is what ManDude told and this [](https://github.com/open-goal/jak-project/issues/1457), I was able to complete the game 100%

**Comment by Schatteneis** [comment]
> That is the only critical issue, I do crash always at this scene
> ![QwwBxps](https://user-images.githubusercontent.com/2992753/176458750-6f4b6dfd-8eb4-48a6-bd5b-59bbdfe2c6e8.png)
> 
> My GPU is an Vega 56 Pulse
> 
> The fix is what ManDude told and this https://github.com/open-goal/jak-project/issues/1457, I was able to complete the game 100%
> 

i can confirm that this works on Linux!

**Comment by water111** [comment]
Reopening because I'd like to eventually figure this one out.

**Comment by Schatteneis** [comment]
i have a suspicion that this might have something to do with ACO shader compilation on AMD cards because i had similar crashes in other games with that feature enabled (this feature is on by default since a few years)

**Comment by water111** [comment]
Haven't seen this come back since #1639, let's close for now
