### ISSUE TITLE
Move Jak folder for save/config to .config instead of home folder (Linux)

### ISSUE THREAD

**Issue by coreybruce** [open-goal/jak-project#1578]
### What feature is your idea related to?

Move the folder OpenGOAL from cluttering the home folder into .config which would be a much better place for this folder for Linux users

### Describe the solution you'd like.

By moving the folder it will be far less clutter for the user and will be in the hidden .config folder for Linux users.

**Comment by xTVaser** [comment]
While we're at this, we should finalize the location of the respective windows folder.  imo this should be sorted before we "officially release" with the launcher.

**Comment by coreybruce** [comment]
> While we're at this, we should finalize the location of the respective windows folder. imo this should be sorted before we "officially release" with the launcher.

This enhancement is for Linux not Windows

**Comment by ManDude** [comment]
Yes, he's saying we should also decide on something for both Linux and Windows. :)

**Comment by coreybruce** [comment]
Oh ok well I mean for Linux it's fine to just put it in .config, I don't think people want yet another launcher to manage a game but you could have the settings for it in the games settings itself and for Windows it could go in appdata

**Comment by xTVaser** [comment]
Not really relevant to this issue on whether or not the launcher is needed or people want it.  The name isn't really descriptive of the problem it's solving -- which is to provide a nice frontend around installing and updating the game.  The vast majority of our support requests are people not knowing how to do this or use/read the terminal.

**Comment by coreybruce** [comment]
I'm not talking about using the terminal I'm just talking about changing the default folder location for the save and settings on Linux, instead of dumping it in the home folder and cluttering it all I am suggesting is to move it to a different better location like .config that's all. :)

**Comment by xTVaser** [comment]
I...know.  I was responding to your latest comment.  I have no problems when the suggestion of using `.config`.

**Comment by coreybruce** [comment]
Oh alright fair enough :)
