### ISSUE TITLE
Audio Clipping

### ISSUE THREAD

**Issue by perrinpagess** [open-goal/jak-project#1583]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Loud sound effects in the game can sometimes cause audio clipping

### How To Reproduce

Play the game, wait for a loud sound.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

Audio doesn't clip. 

### Operating System

Windows 11

### OpenGOAL Version

0.1.12

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

No

**Comment by ManDude** [comment]
I don't think this is really fixable. Play the game on an original PS2 and the same thing happens there. The audio in this game just sucks balls, period.

**Comment by Margen67** [comment]
> I don't think this is really fixable. Play the game on an original PS2 and the same thing happens there. The audio in this game just sucks balls, period.

Something like a compressor would help.

**Comment by perrinpagess** [comment]
DRC with ffmpeg is easy and scriptable. Although if it's a quirk with how the game mixes audio sources, the DRC might not work 100%.

**Comment by perrinpagess** [comment]
Where are the audio bitstreams stored? Are there files for each sound effect which are mixed together by the game, or are there separate files with the sounds already mixed? I'm just curious.

**Comment by ManDude** [comment]
The sound effects are in the SBK files, music is in MUS files and streamed audio is in the VAGWAD files.

**Comment by perrinpagess** [comment]
I went through and listened to the sound effects and music files. the sources don't sound clipped to me, but they're stored in midi, so it makes manipulating them difficult. this does seem fixable with a sound engine rework, so i'll reopen the issue.

**Comment by ManDude** [comment]
Well, considering this is working as intended and therefore not an issue with the project (or a bug with the game), I'll keep this closed. Open it if you have plans to fix it (a "rework" of the sound engine isn't exactly simple).

**Comment by Margen67** [comment]
> Well, considering this is working as intended and therefore not an issue with the project (or a bug with the game), I'll keep this closed. Open it if you have plans to fix it (a "rework" of the sound engine isn't exactly simple).

Why not relabel it as an enhancement, then? If it's closed like this it will just fade into obscurity.

**Comment by ManDude** [comment]
Because nobody has any plans to do anything about it, it is a wontfix.

The game having bad audio isn't obscure, it's one of the more obviously bad things about it. Sadly, it is not that easy to resolve either.

**Comment by nameonascreen** [comment]
Id say its worth leaving the issue open, even if nobody plans to fix it. It's something that shouldn't be ignored FOREVER

**Comment by water111** [comment]
It will be ignored forever unless somebody volunteers to do the work. I don't want to, and none of the other usual contributors seem interested, so I think we should keep this closed and add the idea to the list of game enhancements.  

It's a good idea, and it's something that could be done, but we've been trying to reduce clutter on the list of issues by only tracking stuff in individual issues if it's something we plan to work on.
