### ISSUE TITLE
Newest release build goalc does not "look" in the new extraction directory.

### ISSUE THREAD

**Issue by Zedb0T** [open-goal/jak-project#1601]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

When I run the extractor it extracts everything fine and does (mi) and automatically launch the game.

When you relaunch goalc on windows however, you get an error that an iso folder is missing. If you look in iso_data the folder is named _temp instead of jak1. 

Then if you rename that to jak1 and reopen goalc you get this message "Input file assets/tpage-dir.txt does not exist."  the file is located at "0.1.5\data\decompiler_out\jak1\textures\tpage-dir.txt" for me currently but goalc doesnt look there

### How To Reproduce

Download 0.1.15, tried to reextract 4 times

### Does this problem occur on original hardware or PCSX2?

Not needed, bug is obvious

### Expected Behavior

Goalc should be able to open and (mi)

### Operating System

Windows 10

### OpenGOAL Version

0.1.15 Release

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

No

**Comment by Zedb0T** [comment]
Also there is an empty "assets" folder in the root now that isnt needed

**Comment by xTVaser** [comment]
I think there's a few things going on here, will look into it

**Comment by Zedb0T** [comment]
I can no longer reproduce the second issue locally.
