### ISSUE TITLE
[tests] write tests to ensure all decompiler configs still work

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#1603]

**Comment by xTVaser** [comment]
Considered doing this as part of #2185 but there wasn't really a benefit unless the offline tests also have the alternate ISOs and comparing to fixture configs doesn't really capture the "do the configs work".

Might be nice to have as something to run locally, but I imagine most people don't have all the ISOs anyway to run said-tests.

**Comment by xTVaser** [comment]
Going to close this, unless it's enforced in CI like the offline tests, it's unlikely this will actually keep out broken config changes.  If you think I'm wrong / interest renews in working on, re-open.
