### ISSUE TITLE
Getting an icon for the game

### ISSUE THREAD

**Issue by Syhnx** [open-goal/jak-project#1604]
### What feature is your idea related to?

When you tab out, you'll always see the programm having no (standard) icon
![image](https://user-images.githubusercontent.com/108582941/177191286-634ce432-f908-48de-b4f9-664b93906fe7.png)

### Describe the solution you'd like.

Personally i think this is an easy solution to add an icon to the "gk" file. It shouldn't be prioritized but it's nice to have

**Comment by Zorklis** [comment]
Agreed, It would look a lot more finished

**Comment by xTVaser** [comment]
Kinda a bug, kinda not.  There is an icon on the OpenGL window 
![image](https://user-images.githubusercontent.com/13153231/177432164-93de4f96-de0e-42d4-bbb9-606896d86e52.png)

On windows 11 for me, this works as expected 
![image](https://user-images.githubusercontent.com/13153231/177432189-645854c6-64bc-47b9-91b4-c3465f20e8c7.png)

I imagine for this to be totally solved, the icon needs to be applied to the executable file itself.  Which would be nice to do, eventually.
