### ISSUE TITLE
I have a few questions rather than issues

### ISSUE THREAD

**Issue by Adamillo** [open-goal/jak-project#1620]
Like the title of it says, I have a few questions regarding the opengoal project. First off, I heard that the games code hasn't been fully decompiled yet, but it's close. Where can I see the progress percentage chart in regards to that? And how is the current status of the PC port? Does it have any erroneus bugs I should know of?

**Comment by xTVaser** [comment]
Jak 1 is fully decompiled, there is no updated progress chart for the same reason.  There will eventually be one for jak 2 when we get started.

The current status is you can play it end to end with mostly no issues https://github.com/open-goal/jak-project#read-first

Most known bugs are related to the experimental high fps support https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc

Please try to keep the issues related to actual issues -- there is a discord where you can ask questions

**Comment by Adamillo** [comment]
Right, got it, thanks for answering. If I have more questions, I'll ask them on Discord instead.
