### ISSUE TITLE
Crashes at bootup (60+fps only)

### ISSUE THREAD

**Issue by Syhnx** [open-goal/jak-project#1628]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

When you start the game, you'll see the Naughty Dog logo. After that, the "Jak and Daxter" logo appears. However running the game at 60+ fps (100fps for me) crashes between the transition from Naughty Dog to the title screen. 

### How To Reproduce

Boot up the game with either 100 or 150 fps mode

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

On my experience, the game crashes based on RNG. Sometimes i get into the title screen, sometimes i dont. 
Here's the fix for the issue: Before the title screen, i activate "Accurate Lag Mode". I think this locks the fps back to 60fps, but im not sure. This prevents the game from crashing

### Operating System

Windows 10

### OpenGOAL Version

0.1.16

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

Yes

**Comment by Syhnx** [comment]
As a reference: https://youtu.be/HvTWlLILNUc

**Comment by water111** [comment]
should be fixed by https://github.com/open-goal/jak-project/pull/1655
