### ISSUE TITLE
[error] Failed to make main display.

### ISSUE THREAD

**Issue by WeenieHutJrs337** [open-goal/jak-project#1637]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

When I attempt to launch the game by double-clicking "gk.exe" all I get is a console window that indicates some errors before it closes. Below is the first five lines of my log, where the errors are.

[2022-07-11 10:30:39] [info] OpenGOAL Runtime 1.0
[2022-07-11 10:30:39] [info] GFX Init
[2022-07-11 10:30:39] [error] GLFW ERR 65543: WGL: Failed to create OpenGL context
[2022-07-11 10:30:39] [error] gl_make_display failed - Could not create display window
[2022-07-11 10:30:39] [error] Failed to make main display.

And then as far as I can tell, it seems like it tries to start the game anyway before crashing. But frankly, I have no idea what I'm looking at, so I could be way wrong!

And the full log is attached as well :)
[game.txt](https://github.com/open-goal/jak-project/files/9084942/game.txt)

### How To Reproduce

Step 1. Drag the ISO file onto "extractor.exe" and wait for it to complete extracting the game data.

Step 2. Double-click "gk.exe" to launch the game.

Step 3. Panic as you see the red error text for the first time in the console window.

Step 4. Repeat steps 2 and 3 a few more times in hopes that it will magically start working.

Step 5. Find the log file attempt to figure out why it isn't working before realizing that you have no idea what to make of anything you're looking at.

Step 6. Submit a new issue on GitHub and hope that it's not some really simple solution that makes you look like a total idiot :)

### Does this problem occur on original hardware or PCSX2?

Didn't check

### Expected Behavior

I expect the game to start when I double-click "gk.exe"

### Operating System

Windows 10

### OpenGOAL Version

0.1.18

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

No

**Comment by ManDude** [comment]
What is your GPU?

**Comment by WeenieHutJrs337** [comment]
> What is your GPU?

Intel HD Graphics 5500.

**Comment by ManDude** [comment]
Try updating your drivers and trying again.

**Comment by WeenieHutJrs337** [comment]
> Try updating your drivers and trying again.

Will do, thanks!

**Comment by water111** [comment]
is this still happening?
