### ISSUE TITLE
Flying lurkers power cell on Precursor Basin

### ISSUE THREAD

**Issue by DummHind** [open-goal/jak-project#1642]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Flying Lurker power cell on Precursor Basin level cannot be obtained. Camera locks on dropped power cell and follows it as power cell follows the path of killed lurker. At this point game behave like its in a cutsceene. Cannot enter pasue menu and you can only pause it like its cutsceene.

https://user-images.githubusercontent.com/109237472/178791040-48108a0f-11d1-4a7f-a6a9-7048eda49cf7.mp4

 

### How To Reproduce

-Enter Precursor Basin level on a zoomer
-Use zoomer to catch up with flying lurkers **(the order doesnt matter)**
-Last lurker drops power cell that cannot be obtained

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

If i kill last lurker Jak should go into powercell animation and collect it.

### Operating System

Windows 10 Pro 21H2 OS build 19044.1706

### OpenGOAL Version

v0.1.6

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

Yes

**Comment by ManDude** [comment]
Already fixed. Update the game.

**Comment by DummHind** [comment]
> Oh, you need super powers to be able to close issues.

Wasnt on github for the rest of the day, you dont have to be an ass
