### ISSUE TITLE
[game/collision] red eco doesnt work properly

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#1644]
Sometimes the red eco ground pound doesn't really hit anything.

![image](https://user-images.githubusercontent.com/7569514/178880959-fbc7a0f8-1fb8-4926-87d3-ab4eff0b2efd.png)

It looks like it doesn't expand for some reason.

**Comment by water111** [comment]
Pretty sure:
https://github.com/open-goal/jak-project/blob/96761000397faea0480b6b9b8553bd7162187eba/goal_src/jak1/engine/target/target.gc#L2784

has a typo:
```
(* 286720.0 0 ...
```
shouldn't be a 0 there.
