### ISSUE TITLE
release 0.1.18 can crash if pc-settings.gc is in a certain state.

### ISSUE THREAD

**Issue by Zedb0T** [open-goal/jak-project#1648]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

If   (ps2-parts?) is #t and (fps) == 150 the game will crash when the intro Daxter cutscene menu finishes.

I have attached a settings.gc file that consistently crashes like this. No idea if it is possible to get the settings file into this state via "normal" gameplay but we have had a end user report it so we should probably check this some how.

Link to discussion where the issue was reported in #help 

(https://discord.com/channels/756287461377703987/944405970874925066/997223584864927926)
https://cdn.discordapp.com/attachments/944405970874925066/997228668176826409/pc-settings.gc

### How To Reproduce

Unsure what options would result in the settings file being in this state, and it is possible that it may only be possible when updating or some other thing that will normally never happen.

This was reported by a user who updated from 0.0.5 (old settings location) to 0.1.18, so I think its possible just from a new settings file as 0.1.18, would initilize a "fresh" file.

### Does this problem occur on original hardware or PCSX2?

Not needed, bug is obvious

### Expected Behavior

Not sure what Ps2-parts? does, but ideally the settings would work together, if these settings conflict with each other then they should be checked and never allowed to equal #t and 150 at the same time respectively. 

### Operating System

Checked on windows highly likely this crash is cross-platform

### OpenGOAL Version

0.1.18

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

No

**Comment by Zedb0T** [comment]
#1499

**Comment by ManDude** [comment]
simply having `ps2-parts?` enabled causes this. This also only happens on retail mode. I have no idea why.

**Comment by water111** [comment]
should be fixed by https://github.com/open-goal/jak-project/pull/1655
