### ISSUE TITLE
[Game] FPS option not respected on boot

### ISSUE THREAD

**Issue by BreakPoints** [open-goal/jak-project#1662]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

After setting the FPS option to anything but 60FPS, when next booting the game it will be limited to 60FPS again and the setting has to be re-selected.

### How To Reproduce

Choose 100FPS or 150FPS option, reboot the game and check FPS.

### Does this problem occur on original hardware or PCSX2?

Not needed, bug is obvious

### Expected Behavior

FPS option to stick.

### Operating System

Windows 10 21H2

### OpenGOAL Version

0.1.19

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

Yes

**Comment by BreakPoints** [comment]
Side note, changing FPS mode also sets V-sync to off every time, even if the current FPS mode is selected again.

**Comment by ManDude** [comment]
V-sync resets to off if the selected fps doesn't match the refresh rate. I'm not sure but I think vsync caused issues there.
