### ISSUE TITLE
[reshade] Many particles appear as black pentagons

### ISSUE THREAD

**Issue by MasterDisaster64** [open-goal/jak-project#1666]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Certain particles in the game look like large black pentagons that cover up the area. This includes the particles going into the portals and ones rising from the lava. The particles are not seen while the game is paused.

### How To Reproduce

Look at the portal Samos' house in the opening cutscene or go to Volcanic Crater or Klaw's arena.

![gk 2022-07-16 23-41-55](https://user-images.githubusercontent.com/100798366/179372733-4f519fa9-0aba-4a0e-ad67-be9a32adfbc3.png)
![gk 2022-07-17 00-00-26](https://user-images.githubusercontent.com/100798366/179373368-bbaa1a9c-8391-4527-923d-7446bb2df884.png)
Note: I am playing with the ESRGAN Edition textures, but I believe I saw the bug before applying those as well.

### Does this problem occur on original hardware or PCSX2?

Not needed, bug is obvious

### Expected Behavior

The portal particles should look like blue transparent dots. I am not sure how the lava particles are meant to look.

### Operating System

Windows 11 Home

### OpenGOAL Version

v0.0.19

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

No

**Comment by ManDude** [comment]
Are you using reshade?

**Comment by MasterDisaster64** [comment]
> Are you using reshade?

Normally yes, but the bug still appears with reshade disabled.

**Comment by ManDude** [comment]
Try not having reshade at all.

**Comment by MasterDisaster64** [comment]
That worked, thanks.
