### ISSUE TITLE
[graphics] leaky shadow volumes in intro cutscene

### ISSUE THREAD

**Issue by water111** [open-goal/jak-project#1680]
![image](https://user-images.githubusercontent.com/48171810/179630163-9a62c6af-7d4b-4ffe-8277-dddcf05eecaf.png)

![image](https://user-images.githubusercontent.com/48171810/179630432-4e59e1cf-fbb1-433a-88a2-14e9e706bfaa.png)

![image](https://user-images.githubusercontent.com/48171810/179630453-a372a560-d615-4c09-a44a-a69bdb47925c.png)

kinda hard to see the problem:
![image](https://user-images.githubusercontent.com/48171810/179630479-7d403db4-6956-4c0f-aae3-e243ef88fab1.png)

I wonder if we're failing to handle the case where there are vertices both above and below the scissor plane (and triangles that split the scissor plane result in a bad mesh)

**Comment by water111** [comment]
no, I was wrong, the weird split happens in the original game:
![image](https://user-images.githubusercontent.com/48171810/179631247-c877e2b1-4554-4c34-b578-66e47d908d5e.png)

However, there's two weird thins:
- their "lower half" has inverted colors from mine
- no part of their "lower half" actually generates a shadow (there's a tiny green region too)

I wonder if they did the stencil operations a bit differently from me, so a leaky mesh doesn't result in huge broken shadow.

**Comment by ManDude** [comment]
Does the shadow renderer do backface culling?

**Comment by water111** [comment]
Kind of? Their renderer separates the triangles into front-facing and rear-facing ones.
I implemented the "depth fail" approach here https://en.wikipedia.org/wiki/Shadow_volume

**Comment by water111** [comment]
fixed in https://github.com/open-goal/jak-project/pull/1681
