### ISSUE TITLE
Crash in the lost precursor city

### ISSUE THREAD

**Issue by jambonsupreme** [open-goal/jak-project#1682]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

After completing the puzzle in the lost city where you have to jump and activate all the platforms if you go back to the adjacent room you will start hearing the "platform activated" noise as you walk around (and the plaforms load in). The first time I did this the game also crashed.

### How To Reproduce

I managed to reproduce the sound but not the crash: https://youtu.be/vDmORjR7oQc

First of all I did the puzzle where you have to jump and activate all the platforms to get a power cell. Then I raised the chamber. I got the power cell on top of the chamber and went back in the lost city. After that I arrived at the room with the three spinning lurkers and the bug started happening.

### Does this problem occur on original hardware or PCSX2?

I'm pretty sure that it's unique to OpenGOAL

### Expected Behavior

The game shouldn't crash and the platform activated sound shouldn't play when the platforms are loaded

### Operating System

Windows 10

### OpenGOAL Version

0.1.19

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

Yes, with the 150 fps in-game mode

**Comment by water111** [comment]
The sound issue also happens in the original game. If you beat the platform game, the platforms make a noise when they load in.

I wasn't able to replicate the crash. After raising the chamber, did you take chamber back into the level, or take the elevator?

**Comment by jambonsupreme** [comment]
I took the elevator that you use to enter the level the first time and the crash happened in that room as I was hearing the platform sound. That's why I assumed that it might be related, but I guess I was wrong.

**Comment by jambonsupreme** [comment]
I tried again a couple of times using the exact same save file but was unable to reproduce the crash. I'd provide the log for the first crash but I accidentally overwrote it when trying to reproduce the bug...

**Comment by water111** [comment]
Ok, that's good to know.  Happening at the same time as the platforms spawning is a good clue, and also that you took the chamber out and elevator back in.

Somebody else has reported a crash as they are riding the chamber out of the level, which might also be related.

I'll leave this issue open, but until we get more reports or figure out how to reproduce, there's not much I can do.
