### ISSUE TITLE
OpenGoal extractor is not working on Linux since  v0.17

### ISSUE THREAD

**Issue by xcom169** [open-goal/jak-project#1688]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

The decompiler fails on my NTSC iso file since version 0.17. 

### How To Reproduce

Run the extractor on Linux with the PAL or the NTSC iso file.   The process always fails: 

2022-07-20 19:19:43:139] [info] Extracting Z6TAIL.DUP...
[2022-07-20 19:19:44:871] [info] Detected Game Metadata:
[2022-07-20 19:19:44:871] [info] 	Detected - Jak & Daxter™: The Precursor Legacy (Black Label)
[2022-07-20 19:19:44:871] [info] 	Region - NTSC-U
[2022-07-20 19:19:44:871] [info] 	Serial - SCUS-97124
[2022-07-20 19:19:44:871] [info] 	Uses Decompiler Config - jak1_ntsc_black_label
[2022-07-20 19:20:16:658] [info] -Loading types...
[2022-07-20 19:20:16:841] [error] -100. was supposed to be an number, but isn't when parsing decompiler type file:
decompiler/config/all-types.gc:16776
(deftype sprite-frame-data (structure)
 ^

[2022-07-20 19:20:16:864] [error] Error during decompile: std::exception

### Does this problem occur on original hardware or PCSX2?

Not needed, bug is obvious

### Expected Behavior

The extractor should complete the task

### Operating System

Linux  , Manjaro or Ubuntu LTS

### OpenGOAL Version

0.1.20

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

No

**Comment by water111** [comment]
It works for me... Is there any chance that your language settings use a comma as a decimal separator?

**Comment by SuperSamus** [comment]
I experience the same issue, and the language settings do use a comma as a decimal separator.

**Comment by water111** [comment]
if you go to the file `data/decompiler/config/all-types.gc` near line 16776, there is `:score -100.`. Can you change that to `:score -100` and see if the problem goes away and you get a different error message?

I tried to recreate this problem by using `setlocale` but couldn't, but I'll keep looking around.

**Comment by xcom169** [comment]
Yes. In HU language comma is the separator.

**Comment by SuperSamus** [comment]
By removing the dot, the extraction goes further, but it gives an error later:
```
[ 19%] [copy    ] 1.560 /home/user/Downloads/opengoal-linux-v0.1.20/data/iso_data/jak1/V...
-- Compilation Error! --goal_src/jak1/kernel/gcommon.gc                                       
The symbol 1. was looked up as a global variable, but it does not exist.
Form:
1.
Code:
1.
--------------------------------------------------------------------------------
Location:
goal_src/jak1/kernel/gcommon.gc:87
  (/ 1. x)
   ^
Code:
(/ 1. x)
--------------------------------------------------------------------------------
Compilation failed: Compilation Error
Build failed on goal_src/jak1/kernel/gcommon.gc.
Code:
(make "GROUP:iso" :verbose #f :force #f)
From macro: make-group
--------------------------------------------------------------------------------
Code:
(make-group "iso")
From macro: mi
Used in:
Program string:1
(mi)
^

--------------------------------------------------------------------------------
-- Compilation Error! --
Build failed.
Location:
Program string:1
(mi)
^
Code:
(mi)
--------------------------------------------------------------------------------
terminate called after throwing an instance of 'CompilerException'
  what():  Compiler Exception
```

**Comment by ManDude** [comment]
Can you change the decimal character to be the dot instead of comma and see if it works?

**Comment by SuperSamus** [comment]
With a locale that uses a dot, the extractor succesfully finishes and the game launches, with either `:score -100.` or `:score -100`.
