### ISSUE TITLE
Typo in subtitles 

### ISSUE THREAD

**Issue by possum93** [open-goal/jak-project#1691]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

At the very beginning of the game in the opening cutscene Sage's subtitles read "... monoliths that lither our planet?". 

### How To Reproduce

Enable subtitles and start a fresh file. 

### Does this problem occur on original hardware or PCSX2?

Not needed, bug is obvious

### Expected Behavior

The subtitles should say "litter" and not "lither".

### Operating System

Windows 10

### OpenGOAL Version

v0.1.20

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

Yes

**Comment by ManDude** [comment]
You can fix it yourself if you want by making a pull request.
