### ISSUE TITLE
0.1.18+ can't be launched through Steam on Steam Deck

### ISSUE THREAD

**Issue by omair94** [open-goal/jak-project#1699]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

I recently tried updating my install from 0.1.12 to the latest 0.1.20.  No matter what I couldn't get it to launch through Steam. 

It works when I directly launch GK from the desktop, but through Steam it immediately stops before any window opens. Issue persists even with a fresh install. I have found other people having the same issue on Reddit.

I tried every version between 0.1.12 and 0.1.20 and found that the problem was introduced in 0.1.18

### How To Reproduce

Add the GK executable as a Non-Steam game on Steam Deck and try to launch.

### Does this problem occur on original hardware or PCSX2?

Not needed, bug is obvious

### Expected Behavior

When hitting play in Steam, the game opens.

### Operating System

SteamOS

### OpenGOAL Version

v0.1.18

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

No

**Comment by water111** [comment]
Any chance your language is set to something that uses commas for the decimal separator? Or do you have special characters in your username?

I'm also

**Comment by water111** [comment]
Thanks for tracking down which version it happens in.

Any chance you have a non-english language set on your device, or something that uses commas as the decimal seperator?

I also just started a build for version 1.21, which should be done in about 30 minutes. Once that's done, do you mind trying with that version? We've had a few fixes for linux since version 1.20 that might solve this problem.

**Comment by omair94** [comment]
I'm using US English
I'll be happy to try 1.21 and let you know if it works

**Comment by omair94** [comment]
1.21 did in fact fix the issue.
