### ISSUE TITLE
[opengoal] relax type checking in state handlers

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#1703]
Return type for the `code`, `trans`, `post`, `enter` and `exit` handlers should be `object`. There should also be minimal type checking if the handler passed is not an immediate lambda (`behavior`).

**Comment by water111** [comment]
I think `none` is probably better than `object` in cases where the functions do seem to actually have no return value. I'd rather try to fix whatever issues come up with having a return type of `none`.

I'm not sure I agree about dropping type checking in some cases. Yeah it's a little annoying to have the casts there, but missing argument/return types has been by far the biggest source of really tricky game bugs, and having the cast makes it easier to spot possible issues.

**Comment by ManDude** [comment]
Well, I find it a bit annoying that I have to write
```lisp
:trans (behavior () (setup-subtitle-font) (none))
```
instead of
```lisp
:trans (behavior () (setup-subtitle-font))
```

The extra `(none)` is just unnecessary, I'd rather not have to worry about the return type here at all, since the trans handler isn't meant to have a usable return value. But if it did, then code [like this](https://github.com/open-goal/jak-project/blob/master/goal_src/jak1/engine/common-obs/process-taskable.gc#L356) would actually be broken right now.

Ignoring the return type could also potentially drop [casts like these](https://github.com/open-goal/jak-project/blob/master/goal_src/jak1/engine/common-obs/process-taskable.gc#L360) which aren't useful. The code would look much cleaner.
