### ISSUE TITLE
Gk.exe behaves differently when flags are passed in certain orders.

### ISSUE THREAD

**Issue by Zedb0T** [open-goal/jak-project#1706]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

`gk.exe -proj-path C:\Users\Zed\AppData\Roaming\OpenGOAL-Launcher\data -boot -fakeiso -debug -v`

`gk.exe -boot -fakeiso -debug -v -proj-path C:\Users\Zed\AppData\Roaming\OpenGOAL-Launcher\data`

Behave differently 

Maybe just an end user issue, -booting before setting a path does seem kind of odd. Maybe just always run the `-boot` flag last if present?

### How To Reproduce

`gk.exe -proj-path C:\Users\Zed\AppData\Roaming\OpenGOAL-Launcher\data -boot -fakeiso -debug -v`

`gk.exe -boot -fakeiso -debug -v -proj-path C:\Users\Zed\AppData\Roaming\OpenGOAL-Launcher\data`

Behave differently 

Maybe just an end user issue, -booting before setting a path does seem kind of odd. Maybe just always run the `-boot` flag last if present?

### Does this problem occur on original hardware or PCSX2?

Didn't check

### Expected Behavior

`gk.exe -proj-path C:\Users\Zed\AppData\Roaming\OpenGOAL-Launcher\data -boot -fakeiso -debug -v`

`gk.exe -boot -fakeiso -debug -v -proj-path C:\Users\Zed\AppData\Roaming\OpenGOAL-Launcher\data`

Behave differently 

Maybe just an end user issue, -booting before setting a path does seem kind of odd. Maybe just always run the `-boot` flag last if present?

### Operating System

Windows 10

### OpenGOAL Version

Launcher 1.0 Release 0.1.21

### Game Version

JP

### Are you using a high refresh-rate monitor (>60Hz)

No

**Comment by water111** [comment]
The code that reads these is from the original game, and it has the same problem.  So it's kinda working as expected, but it's not a very good design
