### ISSUE TITLE
extractor.exe doesn't do anything

### ISSUE THREAD

**Issue by JohnARobotnik** [open-goal/jak-project#1720]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Nothing happens when the ISO is dragged onto extractor.exe. A black screen appears for a few seconds then disappears without anything happening. Attempting to use it with cmd also doesn't work (see screenshot). This also happens when my Antivirus is turned off.
![image](https://user-images.githubusercontent.com/110033509/182130099-835c376a-fdf8-457f-8390-e62de5e3e068.png)

### How To Reproduce

Don't know how to reproduce.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

At the very least, the extractor should produce error messages.

### Operating System

Windows 10

### OpenGOAL Version

v0.1.21

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

No

**Comment by GuthixAuditore** [comment]
One thing you need to be mindful of is antivirus can kill the scripts used for open goal, that can cause a blank screen for a few seconds followed by a crash. It could potentially be killing off the process for open goal quietly. It will trip anti virus sometimes depending on what you use, they do not like most custom scripts or programs.

**Comment by Syhnx** [comment]
This CPU does not support AVX. It's required to run openGOAL

**Comment by JohnARobotnik** [comment]
> This CPU does not support AVX. It's required to run openGOAL

You sure? The sites I looked on said it did support it.

**Comment by Zedb0T** [comment]
I can't find anything saying it supports AVX 
This site lists its features as blank, but on other CPUs it lists avx as a feature implying it's not supported 

Intel(R) Pentium(R) CPU G645 @ 2.90GHz 2.90 GHz

https://www.cpu-world.com/CPUs/Pentium_Dual-Core/Intel-Pentium%20G645%20-%20CM8062301262601%20-%20BX80623G645%20-%20BXC80623G645.html
