### ISSUE TITLE
Layering/Z-buffer order issue between blue eco and watterfall in Rock Village

### ISSUE THREAD

**Issue by RaphaelNunes10** [open-goal/jak-project#1721]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Found this blue eco sprite being rendered before the waterfall behind it:

![image](https://user-images.githubusercontent.com/43423924/182283233-b2e31c36-c153-4a47-9a6b-d4c13824771d.png)

### How To Reproduce

Go to Rock Village, point the camera so that the blue eco cluster aligns with the waterfall that's supposed to be behind it near the Geologist character.

### Does this problem occur on original hardware or PCSX2?

Not needed, bug is obvious

### Expected Behavior

The blue eco sprite should be rendered on top of the waterfall.

### Operating System

Windows 11

### OpenGOAL Version

v0.1.21

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

No

**Comment by ManDude** [comment]
Also happens in the original game #1050 . Also, "properly" layering sprites is borderline impossible without seriously tanking the framerate right now so we are deliberately lazier there too.

**Comment by water111** [comment]
Yep, I've checked this one on a real ps2 and it happens there too.
