### ISSUE TITLE
Alt+tabbing disconnects controller

### ISSUE THREAD

**Issue by Monkeor** [open-goal/jak-project#1723]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

I'm using a DS4 at the moment, without DS4Windows. Alt+tabbing disconnects the controller, and reconnecting requires completely turning it off (holding the PS button) and then reconnecting it. It's nothing game-breaking, but it's a hassle.

### How To Reproduce

Step 1: Use a controller
Step 2: Alt+tab while the controller is connected
Step 3: ???
Step 4: Profit.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

The controller should stay connected while alt+tabbed, even if the game isn't receiving input while not focused, and alt+tabbing back to the game should be all it takes to restore functionality.

### Operating System

Windows 10

### OpenGOAL Version

APP Version 1.0.0

### Game Version

NTSC Greatest Hits version (red label)

### Are you using a high refresh-rate monitor (>60Hz)

Yes

**Comment by towai** [comment]
wired or wireless? I haven't had this issue with using mine plugged in via USB, no DS4Windows required - in fact it'll control the game even while you're alt-tabbed, which might not be ideal...
also, could you provide the model number (something like AK8CUHZCT1) if the sticker on the back is still readable? iirc, there were different revisions of the dualshock 4 and that may factor in.

**Comment by Monkeor** [comment]
I just checked, and it doesn't happen when plugged in. The model is AK8CUHZCT1F1.
