### ISSUE TITLE
Game stuck on black screen in Ubuntu 22.04 LTS

### ISSUE THREAD

**Issue by animalstyletaco** [open-goal/jak-project#1727]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

The game shows up as a black screen after launching gk on Ubuntu 22.04 LTS.

### How To Reproduce

Launch the game.

Note: I don't run into this issue on Windows 10. Attached are logs for both Windows and Ubuntu game launches. 

[WindowsOpenGoal.log](https://github.com/open-goal/jak-project/files/9256939/WindowsOpenGoal.log)
[UbuntuOpenGoal.log](https://github.com/open-goal/jak-project/files/9256940/UbuntuOpenGoal.log)

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

Game should not be stuck in black screen

### Operating System

Ubuntu 

### OpenGOAL Version

1.22

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

No

**Comment by water111** [comment]
all the stuff in the log looks good...  there would be a lot more wrong if graphics were totally not working.

the resolution of 640x480 is suspicious to me - the game is supposed to start up in full screen at the resolution of your monitor and I'm guessing your monitor is not 640x480.

does it go full screen by default? if so, can you try going to `~/.config/pc-settings.gc` and changing from fullscreen to windowed?

**Comment by animalstyletaco** [comment]
The program does try to go full screen by default on both Ubuntu and Windows. Although, I don't see pc-settings.gc in ~/.config/OpenGOAL/jak1/settings/pc-settings.gc in my Ubuntu VM. However, I do have AppData/roaming/OpenGOAL/jak1/settings/pc-settings.gc available on my windows machine.

**Comment by xTVaser** [comment]
I've done all my linux testing using 22.04 without issue, if this is still an issue feel free to re-open, but hopefully it was just related to your environment?

**Comment by animalstyletaco** [comment]
Sounds good
