### ISSUE TITLE
All Scout Flies Collected, But 99% Completion

### ISSUE THREAD

**Issue by Damo7784** [open-goal/jak-project#1742]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

For some reason the game displays scout flies at 111/112 and game completion at 99%, even though all scout flies have definitely been obtained as power cells are at 100/100. Save files attached in a zip for use in testing if needed.

![Screenshot 2022-08-07 163112](https://user-images.githubusercontent.com/56873475/183298723-914796b9-fdde-4bbd-ae2e-77d35101f2cc.png)
[BASCUS-97124AYBABTU.zip](https://github.com/open-goal/jak-project/files/9277073/BASCUS-97124AYBABTU.zip)

### How To Reproduce

Complete the game 100% as normal.

### Does this problem occur on original hardware or PCSX2?

Not needed, bug is obvious

### Expected Behavior

As every collectible has been obtained the value for scout slies should be at 112/112, and game should show 100% completion.

### Operating System

Windows 11 Home Version 10.0.22000 Build 22000

### OpenGOAL Version

v0.1.22

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

Yes

**Comment by ManDude** [comment]
There's 101 power cells in the game. Go through the level list.

**Comment by Hat-Kid** [comment]
You missed this scout fly in Spider Cave.
![image](https://user-images.githubusercontent.com/6624576/183305822-ba4eae04-657a-4bb1-b78f-93ca04ca4569.png)
