### ISSUE TITLE
Invincibility bug.

### ISSUE THREAD

**Issue by TheBlueTroll** [open-goal/jak-project#1745]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Turning invincibility on causes no damage to be taken, however, if switched off from the secret menu, does not disable invincibility.

however, after a forced death, vincibility is restored, and you can take damage.
Also, saving then reloading also restores the ability to be hurt, both morally and physically.

### How To Reproduce

```
Steps to reproduce:

- One:     Turn on invincibility from the secrets menu.
- B:       Attempt to take damage and fail
- Tree:    Proceed back to the secrets menu to undo your mistake.
- See:     That you cannot be hurt again.
- And:     Go back to the secrets menu and weep as you confirm it is disabled, and yet you cannot be hurt.
```

### Does this problem occur on original hardware or PCSX2?

Didn't check

### Expected Behavior

When the invincibility cheat is disabled, damage can be taken.

### Operating System

Windows 10 21H2 Build:19044.1826

### OpenGOAL Version

v0.1.22

### Game Version

PAL

### Are you using a high refresh-rate monitor (>60Hz)

Yes

**Comment by ManDude** [comment]
good catch
