### ISSUE TITLE
Unsupported Blend a 0 b 1 c 0 d 2 when using texture replacements

### ISSUE THREAD

**Issue by jet082** [open-goal/jak-project#1762]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

I am using an iso of the black label version of the game. Extracting the game works fine and it runs well.

However, when using this HD Texture pack, the extractor does not succeed and fails on “Processing Level JUN.DGO” with 5 of the same error - “ Unsupported Blend a 0 b 1 c 0 d 2.”

Supposedly this HD texture pack used to work a few months ago.

I am using Linux on a Steam Deck.

### How To Reproduce

Run the iso through the extractor with the texture_replacements directory linked above in the data directory.

### Does this problem occur on original hardware or PCSX2?

Not needed, bug is obvious

### Expected Behavior

The extractor should succeed with texture replacements.

### Operating System

Linux (Steam Deck)

### OpenGOAL Version

0.1.22

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

No

**Comment by xTVaser** [comment]
I've removed the link to the texture pack as we do want to be involved in distributing texture packs that are modified original assets or be associated with them.

Further to that point, if this is only a bug with the texture pack (it doesn't fail without the texture pack) then this is really a bug that should be reported to the creator of the texture pack.

To my knowledge there aren't any issues extracting the assets on the latest release and if I recall correctly that unsupported blend may be a red herring as I think it's been unsupported for quite a while.  But I could be wrong about this.

**Comment by jet082** [comment]
Understandable on the link. I wasn't sure if that was okay or not, apologies.

I just redid the process on Windows and it worked just fine! The issue seems to only exist on the Linux extractor.

**Comment by water111** [comment]
Those error messages are unrelated, they show up without the texture packs on both linux and windows, and are really just a warning.

My best guess is that the extractor is running out of memory and being killed. I tested on my desktop and it uses about 11 GB of RAM, so I think it's believable that it could crash on steam deck (~16 GB RAM).

I'll look into this a bit. The game also runs poorly with these textures, which is something I've been meaning to work on for a long time.

**Comment by water111** [comment]
That texture pack is full of insanely large (~5000x3000 pixel) textures, some of which are jpgs with a `.png` extension... In total, there is about 3.5 GB of texture data. We end up storing the textures 3x (once on initial load to the texture db, then copied to the `tfrag3::level`, then once in the `Serializer`), and we do all the levels in parallel, so the ~11 GB of RAM usage makes perfect.

I think handling this size of textures is not going to work without some redesign. My recommendation is to use smaller textures, and also to use actual `.png`s when possible.

We expect that a single texture can always be uploaded in less than 2.5ms, yet a 5000x3000 texture would require a speed of `5000*3000*4 bytes / (2.5 ms) = 24 GB/sec`, which is like 10x faster than I actually get in practice.
