### ISSUE TITLE
[runtime] quick screenshot button

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#1765]
F8? F2? Any ideas?

**Comment by RandomPrimary2004** [comment]
Steam screenshot button is f12, so I don't know if it would be better to use that or not considering that some people run the game as a non steam game. f8 makes sense to me as an in-game screenshot function, but then again such a thing may be entirely unneeded considering that most GUI operating systems come with or can be configured to have a screenshot feature.

**Comment by Zedb0T** [comment]
F2/F3

**Comment by xTVaser** [comment]
Whatever is picked can it be easily toggable until we have a proper UI to remap buttons.  For example I have my AMD driver recording hotkeys setup to involve function keys.

**Comment by sardap** [comment]
Should we just save the screenshot as what is set in the debug gui ("screenshot.png") or do we want it to do a steam style name + timestamp if you trigger it with the hotkey so you don't override it each  screenshot?

**Comment by ManDude** [comment]
The debug GUI will eventually go away completely for normal users, so the filename would have to be something automatic. I really don't want to program an entirely new UI for this (and nobody else probably does either) so I think that's what we're gonna stick with on that aspect: hotkey and it just saves a screenshot to some user folder.

**Comment by sardap** [comment]
I think "opengoal_YYYY_MM_DD_hh_mm_ss.png" does the job this does limit to one screenshot per second though. 

For disabling screenshot with hotkey  is a simple checkbox in the screenshot debug GUI menu acceptable? 
![gk_Zka8MAlhS4](https://user-images.githubusercontent.com/22311832/185105227-e582ffe7-85ee-4044-b252-906c3fa768da.png)

**Comment by sardap** [comment]
Thinking about this more it really should be mappable though the existing control mapping UI I will try to get it working though that.

**Comment by xTVaser** [comment]
I would replace `opengoal` with the actual game name, ie. `jak1`.  That way we are future proofed for jak 2 and beyond, and opengoal is becoming a bit overloaded of a term.
