### ISSUE TITLE
Linux: Game not detecting Xbox One / Series X|S Controller with xone driver

### ISSUE THREAD

**Issue by r2rX** [open-goal/jak-project#1789]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Hey all,

First of all, fantastic job with this project! Lots of thanks and really looking forward to the day when the Jak Trilogy is playable natively on PC. So, I've been using an Xbox Series X|S controller (wired) with OpenGOAL, which works fine when operating with the xpad driver (which is the default in Fedora 36 KDE).

Recently, though, I switched to using the [xone driver](https://github.com/medusalix/xone) although still connected wired. Unfortunately, the game does not detect the controller. One assumption could be that it's a problem with the driver but from the library of titles I engage with, this is the only one where the controller isn't detected. Lastly, I also tested with an Xbox One Controller (wired) and the results, between using xpad and xone, are the same.

Are there any other users with Xbox One/Series X|S controllers that can attest to this as well?

### How To Reproduce

1. Prepare OpenGOAL with the Jak iso in Linux (in my case, using the NTSC (SCUS-97124) version in Fedora 36 KDE).
2. Connect the Xbox One / Series X|S controller and run the game using the xpad driver (should be the default driver for most distros).
3. Retest after installing the xone driver.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

The game should detect the controller while using the xone driver.

### Operating System

Fedora 36 KDE

### OpenGOAL Version

v0.1.22 - v0.1.25

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

Yes

**Comment by Zedb0T** [comment]
If you follow the sets here, is your controller in the list?

Also can you attach logs? It will let us see if goal is "trying" to use a controller.

https://opengoal.dev/docs/faq#my-controller-doesnt-work

**Comment by r2rX** [comment]
Hey @Zedb0T. I got the latest version of the gamecontrollerdb.txt, for reference, and used two sources to determine the GUID of the controller; the config.vdf file from Steam (in Steam/Config) and AntiMicroX v3.2.5 (for Steam, no in-built controller presets, a.k.a configuration support, were used). To be as helpful as possible, I tested in both Linux and Windows. The controller is an Xbox Series Pad (model no. 1914) with the latest firmware installed. The following are the results:

**Linux:**
```
Steam (config.vdf):
030000005e040000ea02000001030000,Xbox One Wireless Controller,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b8,leftshoulder:b4,leftstick:b9,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b10,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,platform:Linux
```

```
AntiMicroX v3.2.5 (AppImage):
060000005e040000120b00000d05000011182834,XInput Controller,platform:Linux,a:b0,b:b1,x:b2,y:b3,back:b6,start:b7,guide:b8,leftshoulder:b4,rightshoulder:b5,leftstick:b9,rightstick:b10,leftx:a0,lefty:a1,rightx:a3,righty:a4,lefttrigger:a2,righttrigger:a5,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,
```


**Windows:**
```
Steam (config.vdf):
030000005e040000ff02000000007801,XInput Controller,a:b0,b:b1,back:b6,dpdown:h0.4,dpleft:h0.8,dpright:h0.2,dpup:h0.1,guide:b10,leftshoulder:b4,leftstick:b8,lefttrigger:a2,leftx:a0,lefty:a1,rightshoulder:b5,rightstick:b9,righttrigger:a5,rightx:a3,righty:a4,start:b7,x:b2,y:b3,platform:Windows
```


```
AntiMicroX v3.2.5:
030000005e040000ff020000000072001118767,Controller (Xbox One For Windows),platform:Windows,a:b0,b:b1,x:b2,y:b3,back:b6,start:b7,guide:b10,leftshoulder:b4,rightshoulder:b5,leftstick:b8,rightstick:b9,leftx:a0,lefty:a1,rightx:a2,righty:a3,lefttrigger:a4,righttrigger:a5,dpup:h0.1,dpleft:h0.8,dpdown:h0.4,dpright:h0.2,
```

The only controller ID that is present in the gamecontrollerdb.txt is the reference from the Steam config file in Linux. What's surprising is that the game registered the pad in Windows. I don't know the technical details but assuming OpenGOAL/Jak is dependent on SDL2 and the game controller DB for the Windows version too, this doesn't make sense.

As for the logs, I've attached both the Linux and Windows logs but assuming you're looking specifically for the joystick detection entry, the Linux log states **[info] No joysticks found.** and the Windows log states **[info] Using joystick 0 for pad 0: Xbox Controller, XInput Gamepad (GLFW)**.

I'm a tad confused. :) Since installing the xone driver, I've ran an array of native & Proton/WINE games, as well as emulators. Everything I've run so far works for the exception of OpenGOAL/Jak.

Please let me know if there's any further info/testing that I can help with.

[game (windows).txt](https://github.com/open-goal/jak-project/files/9401201/game.windows.txt)
[game (linux).txt](https://github.com/open-goal/jak-project/files/9401202/game.linux.txt)

**Comment by r2rX** [comment]
Just wanted to give an update. I ran the game through Steam, with the Xbox controller profile enabled, and it did work; although no force feedback. I've been testing other games/emulators, ranging between evdev and SDL...all of them work fine. Ideally, it'd be nice to run Jak without it being parsed through Steam and its virtual controller.

**Comment by r2rX** [comment]
Hey @Zedb0T. After a little tinkering, the pad is detected properly now. To get it working, I downloaded @Ryochan7's SDL2_Gamepad_Mapper-0.0.3-x86_64.AppImage (https://drive.google.com/file/d/12CtYjPbP8YLN7dCIJiKX5EcNdf4PIz4g/view?usp=sharing), created a new mapping and copied the map string into the 'sdl_controller_db.txt' in data/game/assets. Works great now, including force feedback.
