### ISSUE TITLE
Game crashes after latest update

### ISSUE THREAD

**Issue by guido-pavesi** [open-goal/jak-project#1792]
After the latest launcher update, data sync and game update, every time I try to launch Jak 1 the game crashes after the Naughty Dog intro sequence. I can't get through that screen normally.
I use the PAL version of the game and my PC works fine with it.

**Comment by ManDude** [comment]
Post your `pc-settings.gc` file here, and then delete it so you can play the game.

**Comment by guido-pavesi** [comment]
[pc-settings.zip](https://github.com/open-goal/jak-project/files/9404806/pc-settings.zip)
Here's my settings. Thanks!

**Comment by xTVaser** [comment]
Closing this as we believe we solved the problem related to your settings file in the mentioned PRs, please re-open if the problem persists.
