### ISSUE TITLE
Keyboard Camera Controls not working

### ISSUE THREAD

**Issue by Xanus** [open-goal/jak-project#1799]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Since the latest update pushed through the launcher keyboard controls for camera turning and zooming don't work.

All other keys seem to be working without issue.

I plugged in a controller and it was able to turn the camera fine, the problem is limited to keyboard control.

### How To Reproduce

Simply run the game and use the keyboard controls.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

Should be able to turn camera when pressing keys for turn left/right and zoom.

### Operating System

Windows 10

### OpenGOAL Version

1.2.0

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

No

**Comment by animalstyletaco** [comment]
One of the latest changes implemented was a keyboard re-mapping feature. Look for the file %APPDATA%\Roaming\OpenGOAL\controller\controller-settings.json. By default, keyboard camera controls are mapped to the mouse x and y axis. 

The workaround is to change the controller-settings.json then restart the game. From this:

>             "ID": 1,
>             "Keyboard+Mouse": {
>                 "Analog": {
>                     "Left X Axis": {
>                         "Negative Key": 65,
>                         "Positive Key": 68
>                     },
>                     "Left Y Axis": {
>                         "Negative Key": 83,
>                         "Positive Key": 87
>                     },
>                     "Right X Axis": {
>                         "Axis Id": 6
>                     },
>                     "Right Y Axis": {
>                         "Axis Id": 7
>                     }
>                 },

To this, in order to match the original keyboard control scheme:

>             "ID": 1,
>             "Keyboard+Mouse": {
>                 "Analog": {
>                     "Left X Axis": {
>                         "Negative Key": 65, 
>                         "Positive Key": 68
>                     },
>                     "Left Y Axis": {
>                         "Negative Key": 83,
>                         "Positive Key": 87
>                     },
>                     "Right X Axis": {
>                         "Negative Key": 74,
>                         "Positive Key": 76
>                     },
>                     "Right Y Axis": {
>                         "Negative Key": 75,
>                         "Positive Key": 73
>                     }
>                 },
> 

However, there is a bug where setting the use mouse is always as false when loading in the json. I'll look into this further.

**Comment by Vorancex64** [comment]
Can confirm that despite being claimed to be fixed in 1.8.0 that the bug is still very much so there. The cursor does not lock to the screen at all and it is impossible to play with mouse and keyboard due to not being able to rotate camera.

**Comment by animalstyletaco** [comment]
I'm very confused. Mouse camera control wasn't implemented until v01.25. I would strongly recommend upgrading to the latest version.

**Comment by xTVaser** [comment]
https://opengoal.dev/docs/usage/settings/#default-keyboard-binds
