### ISSUE TITLE
Controller response

### ISSUE THREAD

**Issue by LegitCactus** [open-goal/jak-project#1810]
Hi just got into the game earlier today. It's been feeling like the response time on the controller is a bit delayed, as I can't do the normal punch/jump/spin combos and the like consistently, as fluid as I was able to on the ps3 ports and even on the originals. Is there anything I can do about this?

I am using an Xbox One controller plugged via micro USB that functions properly for all other dozens of games I use it for through steam.

**Comment by ManDude** [comment]
What framerate have you selected?

**Comment by LegitCactus** [comment]
I had 150 selected but just tested 60 and 100 fps and it feels like there is no difference between the 3 settings.
