### ISSUE TITLE
decompiler: decompiler process hang catch-all

### ISSUE THREAD

**Issue by xTVaser** [open-goal/jak-project#1820]
Sometimes in certain circumstances, the decompiler can hang.  Sometimes this is because a cast must be added, othertimes the problem is less obvious:
- [ ] `dm-cam-setting-float`
- [ ] `(method 20 tracking-spline)` (hang without a stack cast)
- [ ] infinite guessing loop on `cam-circular-position`
- [ ] cam-string-line-of-sight
- [ ] cam-stick-code
- [ ] cam-bike-code

**Comment by water111** [comment]
from chat

https://github.com/Hat-Kid/jak-project/tree/h/j2-board-states
Commenting out all the stack types for (enter target-board-halfpipe) (line 817) triggers it for me

**Comment by water111** [comment]
For `dm-cam-setting-float`:
couldn't reproduce the issue. Tried removing `label_types.jsonc` for `default-menu.gc`, but it still worked. Couldn't find stack structures or type casts for this funciton.

For `(method 20 tracking-spline)`:
couldn't reproduce the issue. Removed stack_structures and it still works. No label or type casts.

For `cam-circular-position`:
couldn't reproduce. function has no stack/type/label hints and is in the reference tests.

For `cam-string-line-of-sight`:
couldn't reproduce. Does need a hint for the collide-query, but this is expected given the current implementation.

For `cam-stack-code`:
couldn't reproduce. Could remove the vector stack hint, but need the collide-query for the same reason as above.

For `cam-bike-code`:
couldn't reproduce. Don't see any hints and seems to be decompiled already.

For board-states:
couldn't reproduce on `(trans target-board-halfpipe)` or `(enter target-board-halfpipe)`.

Casts removed when possible in https://github.com/open-goal/jak-project/pull/1977

**Comment by water111** [comment]
`ocean` method 18, with types `(_type_ object object)`, loops, possibly related to vector4/vector stuff.

**Comment by xTVaser** [comment]
Closing as i doubt we'll fix these -- anecdotally as things matured I hardly ever had a hang anymore so it feels good enough for the future.
