### ISSUE TITLE
decompiler: applying incorrect stack casts when calling the `new` method

### ISSUE THREAD

**Issue by xTVaser** [open-goal/jak-project#1821]
For example in the following code:
```mips
   or gp, a0, r0             ;; [  0] (set! arg0 arg0) [a0: entity ] -> [gp: entity ]
    lw v1, curve(s7)          ;; [  1] (set! v1-0 curve) [] -> [v1: <the etype curve> ]
    lwu t9, 16(v1)            ;; [  2] (set! t9-0 (l.wu (+ v1-0 16)))
                              ;; [v1: <the etype curve> ] -> [t9: (function symbol type curve) ]
    daddiu a0, sp, 16         ;; [  3] (set! a0-1 (+ sp-0 16)) [sp: <uninitialized> ] -> [a0: curve ]
    lw a1, curve(s7)          ;; [  4] (set! a1-0 curve) [] -> [a1: <the etype curve> ]
    jalr ra, t9               ;; [  5] (call! a0-1 a1-0)
                              ;; [a0: curve a1: <the etype curve> t9: (function symbol type curve) ] -> [v0: curve ]
```
The decompiler incorrectly assumes that the stack cast is a `symbol`, because that is the type required by the function.  However it actually needs to be `curve` in this case, as that is the structure we are creating.

**Comment by water111** [comment]
oops, yeah this needs a special case. `new` for stack structures passes the address to the space on the stack to the first arg, which is usually a `symbol`, but can also be a 16-byte aligned pointer for constructing stuff on the stack.

this shouldn't be a hard fix

**Comment by xTVaser** [comment]
Removed blocking-decomp because you can workaround by adding casts
