### ISSUE TITLE
Catching the Flying Lurker Hardlock

### ISSUE THREAD

**Issue by SirBootyCheeks** [open-goal/jak-project#1845]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

After catching the Flying Lurker next to the weed patch in the precursor basin the power cell does not stop. Instead it continues along the path the lurker took in an infinite loop/cutscene. You can only pause it as a cutscene and it Hardlock the game, forcing you to exit entirely.

### How To Reproduce

Grab the flying Lurker next to weeds.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

When you grab the lurker the bug occurs

### Operating System

Windows 10

### OpenGOAL Version

v0.1.18

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

Yes

**Comment by ManDude** [comment]
please use the latest version

**Comment by SirBootyCheeks** [comment]
I started the with the new patch for opengl and have had no problems. You guys are doing a great job with this
