### ISSUE TITLE
[decompiler] `(set! foo bar) bar` could be cleaner

### ISSUE THREAD

**Issue by water111** [open-goal/jak-project#1854]
In particular, we see stuff like
```
      (let ((v1-2 (the-as object (-> v1-1 mood-context state)))
            (f0-0 arg0)
            )
        (set! (-> (the-as forresca-states v1-2) electricity arg1 scale) f0-0)
        f0-0
        )
```
which could be
```
      (let ((v1-2 (the-as object (-> v1-1 mood-context state))))
        (set! (-> (the-as forresca-states v1-2) electricity arg1 scale) arg0)
        )
```

This is somewhat tricky to fix for a few reasons.  It wouldn't be too hard to eliminate the `f0-0` after expressions and before `let`s, but knowing if it's safe to eliminate `f0-0` is a lot harder - we really only have the information and tools to do this as part of the expression building pass.

I _think_ we could identify all of these cases by looking for a
```
<store> val, addr
<move> val2, val
```
and then have this become "push the `set!` expression we'd normally do to `val2` on the expression stack". Then the usual expression stack logic would handle all the logic to eliminate temporaries.

But there's probably a lot of details to get right here.

**Comment by ManDude** [comment]
I think we can also fix this in the let rewrite pass.
