### ISSUE TITLE
My eyes are aching 

### ISSUE THREAD

**Issue by Arachn1dsGrip** [open-goal/jak-project#1863]
Hello. I launched the game for the first time today and from the first seconds i am experiencing problems with the image on screen, i cant describe it but my eyes are aching while im playing the game. I tried different resolutions, disabled vertical synchronisation, tried 100fps setting but i just cant play it. I have my pcsx2 installed and ajusted for the jak1 but i have never experienced that before neither with jak nor with any other pc game i played. Maybe it’s because of 60fps, but as mentioned above this is the first game i have this problem. Created this post to see if i am not alone here and maybe somebody will help me. Much love to all jak fans <3

**Comment by ManDude** [comment]
I'm sorry but I'm not sure what you expect us to do about this since you didn't really describe an actual problem within the game. This isn't the place for discussion posts, it's for bug reports and other issues.
