### ISSUE TITLE
[runtime] investigate blocking code when window is minimized on windows

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#1879]

**Comment by water111** [comment]
for what it's worth, i checked on my windows laptop and didn't see the issue.

I'd try timing the `glfwSwapBuffers` call. Somewhere in there it probably calls https://docs.microsoft.com/en-us/windows/win32/api/wingdi/nf-wingdi-swapbuffers
and there may be some weird power saving feature in your graphics driver that drops the max framerate when things are minimized.
