### ISSUE TITLE
Hitting a drill lurker in spidercave with flut flut groundpound can crash the game

### ISSUE THREAD

**Issue by Zedb0T** [open-goal/jak-project#1885]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

If you flutflut groundpound near a drill lurker under unknown but common circumstances the game will crash/loop/freeze

### How To Reproduce

Ground pound near a drilling lurker on flutflut

### Does this problem occur on original hardware or PCSX2?

It does on PCSX2

### Expected Behavior

Drilling lurker die

### Operating System

Windows

### OpenGOAL Version

Launcher

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

No

**Comment by xTVaser** [comment]
Going to close this since this would obviously never happen in the real game lol.  But it'll be in the backlog of issues incase anyone makes a similar flutflut mod :P
