### ISSUE TITLE
goalc: determine how we want to handle "invalid" enum entries (ie. `-1` in an unsigned enum)

### ISSUE THREAD

**Issue by xTVaser** [open-goal/jak-project#1893]
In jak 2, there is evidence that they intentionally use, for example, `-1` in a `uint8` enum:
```lisp
(defenum game-task
  :type uint8
  :bitfield #f
  (unknown -1)
..
```

The compiler currently does not like this, as it definitely seems like a very strange thing to do (but makes sense in this case -- they are using it as a non-sensible value that should never be set)  https://github.com/open-goal/jak-project/pull/1887

- Should the compiler allow an entry like this?
- Should the decompiler output it with a cast and not demand an entry be created for it?
- ...?

**Comment by water111** [comment]
I think we handle this now
