### ISSUE TITLE
decompiler: Detect square macro in decompiler

### ISSUE THREAD

**Issue by xTVaser** [open-goal/jak-project#1896]
For example:
```mips
lw t9, matrix-axis-sin-cos!(s7);; [124] (set! t9-12 matrix-axis-sin-cos!)
                              ;; [] -> [t9: (function matrix vector float float matrix) ]
    or a0, s0, r0             ;; [125] (set! a0-20 s0-0) [s0: matrix ] -> [a0: matrix ]
    or a1, s3, r0             ;; [126] (set! a1-13 s3-0) [s3: vector ] -> [a1: vector ]
    lui v1, 16256             ;; [127] (set! v1-18 1.0) [] -> [v1: float ]
    mtc1 f1, v1               ;; [128] (set! f1-3 (gpr->fpr v1-18)) [v1: float ] -> []
    mov.s f2, f0              ;; [129] (set! f2-1 f0-9) [] -> []
    mul.s f2, f2, f2          ;; [130] (set! f2-2 (*.s f2-1 f2-1)) [] -> []
    mfc1 v1, f2               ;; [131] (set! v1-19 (fpr->gpr f2-2)) [] -> [v1: float ]
    mtc1 f2, v1               ;; [132] (set! f2-3 (gpr->fpr v1-19)) [v1: float ] -> []
    sub.s f1, f1, f2          ;; [133] (set! f1-4 (-.s f1-3 f2-3)) [] -> []
    sqrt.s f1, f1             ;; [134] (set! f1-5 (sqrt.s f1-4)) [] -> []
    mfc1 a2, f1               ;; [135] (set! a2-4 (fpr->gpr f1-5)) [] -> [a2: float ]
    mfc1 a3, f0               ;; [136] (set! a3-1 (fpr->gpr f0-9)) [] -> [a3: float ]
    jalr ra, t9               ;; [137] (call! a0-20 a1-13 a2-4 a3-1)
                              ;; [a0: matrix a1: vector a2: float a3: float t9: (function matrix vector float float matrix) ] -> [v0: matrix ]
    sll v0, ra, 0

    lw t9, vector-matrix*!(s7);; [138] (set! t9-13 vector-matrix*!) [] -> [t9: (function vector vector matrix vector) ]
```
![image](https://user-images.githubusercontent.com/13153231/190841061-ca11dcd7-1b8c-4c59-b619-b52875ee79de.png)

Atleast, this is my guess to why it's ending up in the let, the code would look a lot nicer if it was just the function call (in this case, sometimes its nice to split up things into a `let` but that's probably not an easy (or desired) decompiler feature)

**Comment by water111** [comment]
This isn't anything to do with functions returning a value (this happens all the time), but instead the use of `f2-1` two times. How can we rearrange this section to look nicer, without changing the meaning of the code?
```
(* f2-1 f2-1)
```
can't be rewritten as
```
(* (cos f0-8) (cos f0-8))
```
that would call the `cos` function an extra time, and we shouldn't do that (might have side effects).

So I'd argue that the decompiler is correct in this case, and any rearrangement that looks nicer would make the code behave differently.  The only way this could look nicer is to add a special case for a `square` macro like
```
(defmacro square (expr)
  `(let ((temp ,expr))
    (* temp temp)
    )
 )
 ```

With this macro, I think it could look like this:
```
(let ((f0-9 (cos f0-8)))
  (matrix-axix-sin-cos! s0-0 s3-0 (sqrtf (- f1.3) (square f2-1)) f0-9)
  )
```
and have the same meaning. Which I'm pretty sure is what they had in the first place.

However, the `(cos f0-8)` must still be in a `let`. Suppose that calling `cos` changes the value of `matrix-axis-sin-cos!` to be a different function. The original code would read the `matrix-axis-sin-cos!` symbol after calling `cos`, and we must do the same.


So maybe this issue should be: "Detect `square` macro in decompiler" or something like that?

**Comment by water111** [comment]
With these types of questions, I find it's really useful to write out the thing you want to see, like
```
(matrix-axix-sin-cos! s0-0 s3-0 (sqrtf (- 1.0 (square (cos f0-8))) f0-9)
```
then "evaluate" the code by hand, iterating from left to right, in a depth first way. So you do
- load `matrix-axis-sin-cos!`
- move `s0-0` to argument register a0
- move `s3-0` to argument register a1
- put constant `1.0` in a float register 
- move `f0-8` to argument register a0
- call `cos`
- multiply result by itself
- do subtraction
- move `f0-9` to argument register
- call `matrix-axis-sin-cos!`

The GOAL compiler's register coloring algorithm is only able to:
- change register-register moves (or remove them)
- insert moves immediately before a `jalr`, or immeidately at the top of a funciton.

and for the rest, no reordering is allowed.

You'll see that the nice looking output doesn't match the assembly here.

**Comment by ManDude** [comment]
`rewrite_let.cpp` has a bunch of code to find macros that were used in the middle of expressions inside lets like in this case which can be used. However, I think this particular example isn't a `square`: the `f1-3` register is loaded after the 2nd argument and right before `f2-1` which is obviously also an extra temporary in the middle of the function call, so the original unwound code most likely looked more like:
```lisp
(let ((f0-9 (cos f0-8)))
  (matrix-axix-sin-cos! s0-0 s3-0 (let ((f1-3 1.0)
                                        (f2-1 f0-9))
                                    (sqrtf (- f1.3 (* f2-1 f2-1))))
                                   f0-9)
  )
```
which means their macro was:
```lisp
(defmacro some-macro (a b)
  `(let ((val-a ,a)
         (val-b ,b))
      (sqrtf (- val-a (* val-b val-b))))
  )
```
(it is possible that there is a `square` macro inside this macro, btw)
I don't know what kind of operation this is though so I have no idea what to call it.

**Comment by xTVaser** [comment]
Closing for now as the original description is inaccurate and I was mistaken.

If the macro(s) used in this particular example are pervasive enough to warrant a decompiler addition then I'll make a new issue that actually captures that work properly.
