### ISSUE TITLE
Requirements

### ISSUE THREAD

**Issue by mills32** [open-goal/jak-project#1905]
Hi!.  Just a question, what are the requirements for this to work, what version of OpenGL, RAM etc?.

I want to test on an "old" PC (1.5GHz, intel HD GPU, windows 32bit).

Thanks a lot for this.

**Comment by Hat-Kid** [comment]
The absolute minimum requirements would be:

- An x86-64 OS and CPU with AVX
- A GPU with at least OpenGL 4.3 support

RAM depends, but the game shouldn't use much more than I believe ~500 MB in most scenarios.

**Comment by ManDude** [comment]
Read the FAQ please.
