### ISSUE TITLE
boxed arrays of enums do not decompile nicely

### ISSUE THREAD

**Issue by xTVaser** [open-goal/jak-project#1922]
For example:
```clj
(define *language-name-remap*
  (the-as (array game-text-id)
    (new 'static 'boxed-array :type uint32 #x111 #x112 #x113 #x114 #x115 #x117 #x116 #x30b)
    )
  )
```

Would be a lot nicer if it complained about missing entries / decompiled with the entries

**Comment by water111** [comment]
The actual `:type uint32` here is actually in the game's data - this is really an `(array uint32)`.  That said, maybe they had some fancy feature where a `(array game-text-id)` at compile time magically becomes an `(array uint32)`.

I do think we could support this, but it would be a few steps to make it work properly (some of which might already be done):
- compiler would need to know to change `game-text-id` to `uint32` when creating static data
- decompiler would need to know how to decompile arrays of enums
- decompiler would need a way to know that `(array game-text-id)` should have the element type be `uint32`, but should use `game-text-id` as the type to decompile.
