### ISSUE TITLE
decompiler: add warning for unresolved loads/stores that still decompile

### ISSUE THREAD

**Issue by Hat-Kid** [open-goal/jak-project#1933]
Something like `WARN: Store failed on op 390: (s.d! (+ v1-137 148) 0)`, where the decompiler output is:
```
(let ((v1-137 (-> self fact)))
  (s.d! (+ v1-137 148) 0)
  )
```

**Comment by water111** [comment]
I think this is a good idea, and would be pretty easy to add.

This case shows up when the decompiler fails to convert a `StoreOp` (which just represents a simple store) into something fancier (like storing into a pair/array/symbol/field/dereferenced pointer). In this case, it converts the `StoreOp` to a `StoreElement`, which is the thing that shows up like `s.d!` or `s.f!`.

I think you could add a warning in `AtomicOpForm.cpp` (the file where all these op -> element conversions happen). On the last line of `StoreOp::get_as_form` if nothing else succeeds, it falls back to
```cpp
return pool.alloc_element<StoreElement>(this);
```
right before this line, you could put something like this
```cpp
env.func->warnings.warning("Failed store: {} at op {}", to_string(env), m_my_idx);
```
and it will output a warning on top of the function.
