### ISSUE TITLE
Similarly named variables can result in an invalid `local-vars` list

### ISSUE THREAD

**Issue by xTVaser** [open-goal/jak-project#1941]
Take the following snippets from a function:
```clj
...
        ((= evt-type 'move-to)
         (when (and (-> self next-state) (let ((v1-20 (-> self next-state name)))
                                           (or (= v1-20 'waiting) (= v1-20 'arrived))
...
        ((= evt-type 'trigger)
         (when (and (-> self next-state) (let ((v1-48 (-> self next-state name)))
                                           (or (= v1-48 'waiting) (= v1-48 'arrived))
```

In this situation, both `v1-20` and `v1-48` are both locally scoped variables, and in this case do exactly the same thing -- so it makes sense to probably want to name them the same thing and there should be no concerns over them shadowing each other with how they are scoped.  Let's say we name them `next-state`.

If `v1-20` is the only thing casted, it works out fine like so:

```clj
...
         (when (and (-> self next-state) (let ((next-state (-> self next-state name)))
                                           (or (= next-state 'waiting) (= next-state 'arrived))
...
         (when (and (-> self next-state) (let ((v1-48 (-> self next-state name)))
                                           (or (= v1-48 'waiting) (= v1-48 'arrived))
```

However, once we also cast `v1-48`, the variable optimizing code (i assume) detects that we can get away with less variables and uses a local variable instead in this case (sometimes it will use an encompassing `let` instead).

```clj
  (local-vars (next-state-name symbol) (next-state-name symbol))
...
         (when (and (-> self next-state) (begin
                                           (set! next-state-name (-> self next-state name))
                                           (or (= next-state-name 'waiting) (= next-state-name 'arrived))
...
         (when (and (-> self next-state) (begin
                                           (set! next-state-name (-> self next-state name))
                                           (or (= next-state-name 'waiting) (= next-state-name 'arrived))
```

This is a problem because the same name now appears in the `local-vars` list twice, which is a compiler error.

I think an easy solution is just to de-dupe the local-vars list, but it's an interesting problem in general because:
1. the optimization sometimes produces nicer code, sometimes it doesn't (in this case, the inner `let` looks cleaner / has less random mutation / less lines and avoids a `begin`)
2. you have to keep this behaviour in mind when cleaning up the code, the structure will change

**Comment by ManDude** [comment]
The decompiler in general doesn't support variables with the same name. See #521

**Comment by xTVaser** [comment]
Alright, I'll pivot to documenting this somewhere / preventing it via the editor tools.
