### ISSUE TITLE
Unable to decompile static data for a structure containing an "array" of `strings` that can also be `#f`

### ISSUE THREAD

**Issue by xTVaser** [open-goal/jak-project#1952]
File is `minimap`, the type is:
```clj
(deftype minimap-texture-name-array (structure)
  ((data string 35 :offset-assert 0)
   )
  :method-count-assert 9
  :size-assert         #x8c
  :flag-assert         #x90000008c
  )
```

The static data looks like so:
```asm
L324:
    .symbol #f
    .symbol #f
    .word L345
    .word L344
    .symbol #f
    .symbol #f
    .word L343
    .word L342
    .word L341
...
```

Results in the following assertion being hit
```
[26:26] [die] Assertion failed: 'elt_type != TypeSpec("uint128")'
        Source: C:/Users/xtvas/Repositories/opengoal/jak-project/decompiler/util/data_decompile.cpp:299
        Function: goos::Object __cdecl decompiler::decompile_value_array(const TypeSpec &, const Type *, int, int, int, const std::vector<LinkedWord> &, const TypeSystem &)
```

I think a solution to this is to make it an `object` array, which fails when it hits a symbol -- though i remember this being potentially fixed on another branch...either way this feels like a kludgey solution that keeps coming up

**Comment by water111** [comment]
I took a look and the problem is unrelated to the `minimap-texture-name-array`. It's the `minimap-corner-array`, which is an array of `uint128`s. I would make the type this instead
```
(deftype minimap-corner-array (structure)
  ((data qword 35 :inline :offset-assert 0)
   )
  :method-count-assert 9
  :size-assert         #x230
  :flag-assert         #x900000230
  )
  ```
  then it works

**Comment by water111** [comment]
The `string` for `minimap-texture-name-array` is correct - that is succeeding - it's the next array that has the uint128 error.
