### ISSUE TITLE
static decompilation of value array can get confused by following label's `.type`

### ISSUE THREAD

**Issue by xTVaser** [open-goal/jak-project#1967]
`actor-hash` has these gigantic empty arrays which atleast for now are probably just plain bytes, when trying to treat them like this however it uncovers an interesting bug, similar to #1948 

a snippet from the problematic part:
```asm
    .word 0x0
    .word 0x0
    .word 0x0
    .type string
; "actor-hash"
L37:
    .word 0xa
    .word 0x6f746361
    .word 0x61682d72
    .word 0x6873
```

And the related error:
> ;; ERROR: Failed static ref finding: Got bad word in kind in array of values: expecting array of uint32's, got a 7

So the data_decompilation code is interpreting the `.type` as part of the array, instead of considering that the end -- probably a bug in our end-of-label detection code or something.

**Comment by water111** [comment]
fixed in https://github.com/open-goal/jak-project/pull/2009
