### ISSUE TITLE
Unknown ID xxx after language change

### ISSUE THREAD

**Issue by Mer08** [open-goal/jak-project#1969]
### Acknowledgements

- [x] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

I have dumped my original PAL DVD but when I changed the language, some texts are translated and some are not.
![image](https://user-images.githubusercontent.com/79792352/195977199-ffe03300-dd98-4052-9559-8e65e153cf1f.png)

### How To Reproduce

Boot up the game (PAL ISO ONLY) and change the language to Spanish. (only happens on OpenGOAL)

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

When you change the language, the "Unknown ID xxx" text replaces some buttons on the main menu.

### Operating System

Microsoft Windows [Version 10.0.19044.2130]

### OpenGOAL Version

v1.5.0

### Game Version

PAL

### Are you using a high refresh-rate monitor (>60Hz)

Yes

**Comment by ManDude** [comment]
Not a bug. It means nobody has wrote the text for that language. Make a PR with all the translations (see #1709 and #1568) and we'll look into adding it to the game.

**Comment by Mer08** [comment]
> Not a bug. It means nobody has wrote the text for that language. Make a PR with all the translations (see https://github.com/open-goal/jak-project/pull/1709 and https://github.com/open-goal/jak-project/pull/1568) and we'll look into adding it to the game.
Thank you for answering. I'm Spanish and would like to what file to modify and what to type on each line to point to a specific text ID. Also, is it not possible to import the text from the ISO used for decompiling the game?

**Comment by ManDude** [comment]
It is not possible because it is not text from the original game - it's extra text we have added.

**Comment by Mer08** [comment]
Oh, I see. Thanks for the clarification.

**Comment by MineSAT** [comment]
> It is not possible because it is not text from the original game - it's extra text we have added.

And is it possible to translate it in some way so that it does not look like this when the game is put in Spanish?
thanks in advance :)

**Comment by ManDude** [comment]
Yes, see #1502
