### ISSUE TITLE
Running (mi) repl with non black label versions (eg jak1_pal) fails looking in wrong folder

### ISSUE THREAD

**Issue by chillypepper** [open-goal/jak-project#1993]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

One of the final steps in the build process (the `(mi)` build step in `task repl`) does not properly respect the `iso_data_path`, meaning for pal users we get a pathing issue in the final stage (extracting works fine).

The issue seems to be in `goal_src\jak1\compiler-setup.gc` not having awareness of `*use-iso-data-path*` and `*iso-data*` that are used in `goal_src\jak1\game.gp` - in the repl run it uses the default path (`jak1/`) for `$ISO` and `$DECOMP`.

It's easy to work around because of this, just by changing these two defaults to `jak1_pal` in my case, or in renaming the folders in `decompiler_out` and `iso_data` from their original form to just `jak1`.

This is not a high priority as it's easy to work around, but I've got almost no experience in C++ or this project so it'll take me a while to figure out the right solution.

Workaround below for anyone else that might hit this, just by editing your `goal_src\jak1\game.gp` file with the new paths, eg:

![game_gp_iso_path_changes](https://user-images.githubusercontent.com/19725656/198268365-9638faf0-1f24-4e8e-ac82-2ed8f38da305.png)

### How To Reproduce

This does require a pal or other non standard version in order to properly test, but can be shortcut easily by updating the task config to something else and then running `(mi)`, when you don't have valid assets in your `jak1` `decompiler_out` and `iso_data` folders.

```
task set-game-jak1
task set-decomp-pal
task repl
g > (mi)
```

Despite this setting the iso path to `jak1_pal` the error you should see will be something like `Input file iso_data/jak1/MUS/TWEAKVAL.MUS does not exist.`

![repl_mi_exception](https://user-images.githubusercontent.com/19725656/198267869-cf845bcc-ec6d-46ea-9f7b-03dd2e350fe9.png)

### Does this problem occur on original hardware or PCSX2?

Not needed, bug is obvious

### Expected Behavior

Running `(mi)` should respect the iso path settings. I'm still looking at options, but it would be great if there was a way to just use `decompiler\extractor\main.cpp` > `compile` or something similar as a util to load the version data or defaults and set up the environment correctly.

### Operating System

Windows 10 Pro 22H2 - 19045.2193

### OpenGOAL Version

c03576df45a7615badeff4075c2ff852ba5c2ca4

### Game Version

PAL

### Are you using a high refresh-rate monitor (>60Hz)

Yes

**Comment by chillypepper** [comment]
Adding a comment for some extra information - I'm hoping to fix this one up myself, but thought I'd document this to include the workaround in case anyone else hits something similar. I'm also secretly hoping someone will see this and go "oh that's an easy fix, here's an example of another .gc file that loads the config" and save me some headaches, but I'll be using this to learn a bit while I poke around in the code anyway so no problems if that doesn't happen :P

**Comment by chillypepper** [comment]
Yeah that makes sense, and with that in mind even more impressive that this was the only step I hit an issue with my pal copy hahaha. If that's the case though I'd be interested in trying my hand at separating out some functionality to load the path from the task env settings (wherever they're stored) and then looking at making that universal for these functions, but I might just park it for now and see if there's something more valuable I can work on to start with.

Would you be happy for me to make a PR for the docs to include a note for users to rename their folders in `iso_data` and `decompiler_out` to `jak1` if they're using other versions? That should get around this problem for now in the install with no code changes required during the install, and this ticket can sit in the backlog for later

**Comment by ManDude** [comment]
To be honest the intentional behavior is for people looking to modify the game like this to change the project file themseles, hence the user clause.

**Comment by xTVaser** [comment]
I don't see how the user clause helps currently?  It has a hard-coded check for your user, so everyone would have to add their own extra clause, and get it merged.  The experience can be much better than that.

**Comment by ManDude** [comment]
I don't have any issues with people adding their own users there if they're contributing upstream. And if they're not contributing then it doesn't affect anything.

**Comment by xTVaser** [comment]
I do because that isn't a scalable solution, it just pollutes the project file with a bunch of conditional checks for one-off users.

**Comment by ManDude** [comment]
Either way that doesn't matter now - editing `game.gp` to point to your stuff is indeed how you're supposed to work through this. Feel free to come up with better solution or instructions but you will always need to change some path somewhere if you're not using the defaults.

**Comment by chillypepper** [comment]
I agree that it's not a major issue if users need to deviate from the original instructions to get the build working, but given that the docs suggest all regions should work and it's not immediately obvious it's just a pathing issue it might lead new developers to thinking they have other environmental issues at play (speaking from experience :P). In this case though they don't even need to edit `game.gp` - a simple renaming of the folder works around the issue and would allow them to start developing immediately.

I've created https://github.com/open-goal/jak-project/pull/1995 to include a note about this in the readme that I think will avoid this issue for devs from other regions. That way they can get started working with the actual game, and this can be left until later
