### ISSUE TITLE
add an easier way to bind keyboard and controls?

### ISSUE THREAD

**Issue by Id-ware** [open-goal/jak-project#2003]
### Is your feature request related to a problem?

the issue is as for now you can't easily bind the keyboard/controller to different keys or to a mouse
(you can do it only via the controller-settings.json, but it's not documented and very hard to understand/configure for pepole who just want to play)

### Describe the solution you'd like.

create an option in the launcher UI to select and bind your game keys for keyboard/mouse/controller, have an option to select modes (keyboard only, keyboard + mouse, or controller) ect

**Comment by animalstyletaco** [comment]
Related to https://github.com/open-goal/jak-project/pull/1737
