### ISSUE TITLE
macros: `ja num! identity` does not function properly

### ISSUE THREAD

**Issue by xTVaser** [open-goal/jak-project#2071]
It seems like this is the first instance of `identity` anywhere in the project, so I'm assuming it's just an untested path.

This happens in `gungame-obs::(code close gungame-door)`

```clj
      (suspend)
      (when (>= 0.0 (ja-frame-num 0))
        (ja-no-eval :num! identity :frame-num 0.0)
        (goto cfg-12)
        )
```

```
[GOOS] Evaluation error on (car num-args): Argument 0 has type [empty list] but [pair] was expected
Argument is: ()
test/decompiler/reference/jak2/decompiler-macros.gc:893
        ((eq? num! 'identity) `(set! (-> ja-ch frame-num) ,(car num-args)))
```

**Comment by ManDude** [comment]
```cpp
    // check the num! arg
    if (prelim_num == "identity") {
      if (set_fn2) {
        auto obj_fn2 = set_fn2->to_form(env);
        if (obj_fn2.is_float(0.0)) {
          num_form = pool.form<ConstantTokenElement>("min");
```
somehow this case isn't being hit

**Comment by ManDude** [comment]
can you see if #2074 works?

**Comment by ManDude** [comment]
looks like this is actually just a ridiculous edge case. `identity` is used many times in jak 2 https://sourcegraph.com/search?q=context:global+repo:open-goal/jak-project+file:%5Egoal_src/jak2/+%28identity&patternType=standard&case=yes&sm=0
