### ISSUE TITLE
controller input not working on steam deck

### ISSUE THREAD

**Issue by poxy100** [open-goal/jak-project#2117]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

weather I start it in desktop or gaming mode, the game won't use the actual controller input on steam deck, I had to make an entire controller configuration from steam to get the controller kinda work using the keyboard layout.

I know this is related to steam itself, cause On my laptop I got this same issue, but the way it was solved was to shut off steam entirely, and I don't think thats possible on the deck.

listen I'm stupid, I don't know how other people fix this problem, or why I'm getting it, but if there is a simple solution it would be great to know about it and it should probably be on the Q&A page.

### How To Reproduce

on windows it happens when steam is running, steam interferes with controller input and it stacks with the raw input leading to overlapping and contradictory input, it happens with other non steam games as well, and if you shut off steam it works as normal. this is not the case for the steam deck, you can "exit steam" on desktop but it doesn't fix it.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

the controller input should work, it doesn't. I have to use a controller layout to mimic the keyboard controls, which is not functionally ideal

### Operating System

steam deck

### OpenGOAL Version

v0.1.31

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

No

**Comment by water111** [comment]
I'm not sure what we can do about this if it's steam that's causing the problem. See https://www.reddit.com/r/Steam_Link/comments/9gxh5w/double_input_fix_for_xbox_and_nonsteam_controllers/ maybe.
