### ISSUE TITLE
Black screen after switching displays

### ISSUE THREAD

**Issue by tcannie** [open-goal/jak-project#2124]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Game stops displaying when switching to a secondary monitor. Audio continues to work and menus can still be navigated, but nothing is visual on the screen. Issue persists after restarting/uninstalling and reinstalling.

### How To Reproduce

After pressing start on the title screen, proceed to Options->Graphic options->Display. Then select Display 2.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

When Display 2 is selected, the game should then be able to be played on a secondary monitor.

### Operating System

Windows 11

### OpenGOAL Version

Release v0.1.31

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

Yes

**Comment by Zedb0T** [comment]
Odd.. Can you provide some more information so I can attempt to replicate this?


Can you provide your pc-settings.gc file so I can take a look?
Are both the monitors set to the same refresh rate?
Are you experiencing this in fullscreen or borderless mode? Or both?

Thanks!
