### ISSUE TITLE
(Jak & Daxter) Oddities when skipping cutscenes

### ISSUE THREAD

**Issue by ddubs13** [open-goal/jak-project#2145]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Skipping the opening cutscene for Jak 1 causes the tutorial level to be at night. In fact, I think the day/night cycle is entirely stuck like that for the rest of the game, if you never quit. In addition, during cutscenes, the music is muted (it comes back once the cutscene ends). Both of these issues will be fixed if you quit and reload a save.

I also noticed that changing in-game options after this happened caused the game to crash, but I have no idea if that's related.

### How To Reproduce

When starting a new game with the "skippable cutscenes" option enabled, skip the opening. Make your way through the tutorial back to Sandover Village and you'll see what I mean about the cutscene audio.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

The game should always start at daytime and have a normal day/night cycle. During cutscenes, you should hear background music.

### Operating System

Windows 11

### OpenGOAL Version

v0.1.31

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

Yes

**Comment by Zedb0T** [comment]
I was able to replicate this issue in debug mode. Here is a attached video
https://youtu.be/ZBjA7UE8k1I
