### ISSUE TITLE
(Jak 1) Missing sound effects

### ISSUE THREAD

**Issue by ddubs13** [open-goal/jak-project#2151]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Some sound effects in Jak 1 seem to be entirely missing and don't play at all, and I can't for the life of me figure out why. Sounds that don't play include:

- Firing yellow eco
- The fisherman's boat
- Almost the entirety of the Klaww battle
- The zoomer
- The balloons you hit with the zoomer

Sometimes, if I entirely close the game and open it again, the sounds will work again, but go right back to not working after a short while.

### How To Reproduce

Play the game to where the situations I mentioned are, and see if the sounds play.

I also have hints disabled and am playing at 100fps, but I don't know if that has anything to do with it. Otherwise, it's a vanilla setup.

### Does this problem occur on original hardware or PCSX2?

Didn't check

### Expected Behavior

There should be obvious sounds for the events I mentioned.

### Operating System

Windows 11

### OpenGOAL Version

v0.1.31

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

Yes

**Comment by Hat-Kid** [comment]
This is known and has already been fixed, there will be a new release at the end of the month with that fix included.
