### ISSUE TITLE
fake_iso max list size is static and too small for Jak 2

### ISSUE THREAD

**Issue by xTVaser** [open-goal/jak-project#2177]
If you add too many files to the project (ie. including all STR files) you will run into the `350` file limit hard-coded into fake_iso.cpp https://github.com/open-goal/jak-project/blob/23c1f3019b0b8b686672000c658a69de2fa9dfea/game/overlord/fake_iso.cpp#L50-L54

This limit should be adaptable based on the game version.

In general this seems fragile anyway, I imagine custom levels could run into this same limit if sufficiently complex (custom animations, etc)

**Comment by Ziemas** [comment]
MAX_ISO_FILES is 640 in Jak 2 overlord, just for the record.

**Comment by water111** [comment]
I think this was fixed was overlord was updated for jak 2.
