### ISSUE TITLE
PS3 HD game compatibility

### ISSUE THREAD

**Issue by JimScript** [open-goal/jak-project#2227]
### What feature is your idea related to?

Not everyone who has played the Jak games has played the PS2 versions, some(like myself) have started on the PS3 collection and therefore don't have a PS2 copy on hand. I could get a copy, of course, but it would feel like a waste considering I already have a version of the game. And the way I hear it, the PS3 had some enhanced textures that came with it too, so it could help with that as well.

### Describe the solution you'd like.

When you get a Jak Collection disk ready for RPCS3, the only files that matter for the games themselves(i.e. not part of the collection interface) are the .self to run the game, and the .PSARC that contains _all_ the data for the game in the data/jak(1,2,3) folders. So instead of loading the assets from a PS2 ISO, load them from a PS3 PSARC instead(and from the .self if needed be) as another option.

**Comment by ManDude** [comment]
Not planned. This project is specifically targeting the PS2 versions. Anything else adds way too much work for little benefit.

Only a few of the PS3 textures are redrawn. The same effect can be achieved by applying texture mods to the game.

If you can rip PS3 games then it shouldn't be too difficult to figure out how you can get a PS2 version of the game.
