### ISSUE TITLE
hover enemies are broken

### ISSUE THREAD

**Issue by Zedb0T** [open-goal/jak-project#2275]

**Comment by Zedb0T** [comment]
Surprisingly they don't seem to spawn currently??

But I recall them functioning not long ago.

**Comment by Hat-Kid** [comment]
They work fine for me.
![image](https://user-images.githubusercontent.com/6624576/221422207-55044614-dbeb-46aa-9214-d380144a7453.png)

**Comment by Zedb0T** [comment]
Huh yeah I just rebuilt the project in visual studio, extracted to get fresh fr3's, did a (mi) and booted the game and I still dont have them. Oddly enough they are also missing in `drill-ship` even tho I tested that mission in #2265. Only difference is I did a fresh pull this morning
