### ISSUE TITLE
Swap the bumpers with the triggers as a default

### ISSUE THREAD

**Issue by Gorilli09** [open-goal/jak-project#2290]
### What feature is your idea related to?

Some platformer games on the PS2 use the L1 button to crouch, and most gun games use the R1 button to shoot.

### Describe the solution you'd like.

I'd like bumpers to be swapped with the triggers as a default because it feels modern.

**Comment by Zedb0T** [comment]
A more future/elegant solution would probably be proper in game keybind settings. atm Jak 2 is the priority tho for the main devs
