### ISSUE TITLE
log rotation code throws an exception if the log file is empty

### ISSUE THREAD

**Issue by xTVaser** [open-goal/jak-project#2297]
https://github.com/open-goal/jak-project/blob/d6bd437ea1b6ee16bb2a4d03b479fadc5af412f9/common/util/FileUtil.cpp#L281-L284

This code doesn't handle an empty file properly

It would probably be better to use the std::filesystem API to copy a file instead of reading/writing it manually. https://en.cppreference.com/w/cpp/filesystem/copy

**Comment by ManDude** [comment]
that code should also be fixed too
