### ISSUE TITLE
[sprite-glow] glows can be seen through other glows when they should be covered up

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#2328]
![image](https://user-images.githubusercontent.com/7569514/226085496-86b6237d-402a-4dd6-afe2-5357c2424dd0.png)

**Comment by xTVaser** [comment]
Another example of this -- you can see the boosts on the other segment of the race-track in class 2 when turning this corner 
![image](https://github.com/open-goal/jak-project/assets/13153231/7f4469b9-4d92-475e-ba22-cfc53343472e)

**Comment by water111** [comment]
I think the important change is to _always_ draw to the grid patterns, never to the actual screen coordinates. The grids don't overlap, but the screen coordinates do. So we should be safe to batch stuff as long as all writes always go to the grid (there's a comment pointing this out in the top of `GlowRenderer`, I just didn't think through all the way how to do this yet).

I think this approach could work. Again, we would two draws to do the probing, then do the downsampling like we do now.

Before drawing, we blit the depth buffer to a texture. (i think blit is needed for msaa reasons).

Our first batch of draws will clear alpha in the grid, and set the depth component in the grid appropriately. We can use the depth buffer texture, and `gl_fragdepth` in the fragment shader to copy square regions of the depth buffer. The texture coordinates here are screen coordinates, but the vertices are grid.

Next, we can draw the probes on the grid (just using z from the original probe). This will test against the copied z, and write alpha only where it passes.
