### ISSUE TITLE
spydroids lack particle effect

### ISSUE THREAD

**Issue by Zedb0T** [open-goal/jak-project#2354]
Smoke cloud when they die looks like it might be messed up?
-Zed

https://user-images.githubusercontent.com/89345505/221422109-34503b39-dc86-45a1-9a12-46eb0a9ccecb.mp4

Youtube video
https://youtu.be/7o0Ntu6MuX4?t=270

**Comment by water111** [comment]
I think this still happens?

**Comment by Zedb0T** [comment]
It does the last time I checked, but It was hard to verify if it was accurate or not as I compared to PS2 on a CRT. I should have used PCSX2 to verify my apologies

**Comment by Zedb0T** [comment]
Potentially the same as #2370

**Comment by ManDude** [comment]
Fixed now. Banana sprite was also appearing on precursor stone in tomb boss.
