### ISSUE TITLE
Ashelins projectile effects look wrong

### ISSUE THREAD

**Issue by water111** [open-goal/jak-project#2377]

**Comment by water111** [comment]
unknown if fixed or not:


![Image](https://user-images.githubusercontent.com/48171810/226764880-057e5f5e-9298-4794-84ea-8b8105e49e7e.png)

**Comment by Zedb0T** [comment]
Looks a bit different for me?


![Image](https://user-images.githubusercontent.com/89345505/227757050-25bd9f2b-8a06-46b8-acdc-82ca0d556f81.png)

**Comment by ManDude** [comment]
Looks fixed.
