### ISSUE TITLE
cable - fortress searchlights look a little rough

### ISSUE THREAD

**Issue by xTVaser** [open-goal/jak-project#2417]
![Image](https://user-images.githubusercontent.com/13153231/227747277-049dd4fc-8aa3-4c0e-be2c-52ebdcc5ab69.png)

**Comment by ManDude** [comment]
Can be seen throughout the city as well.

![image](https://user-images.githubusercontent.com/7569514/227755329-5e8c52c8-06d1-47f4-a7cf-21aee2705759.png)
