### ISSUE TITLE
after watching the first kor intro cutscene, kor moves backward in a weird way

### ISSUE THREAD

**Issue by water111** [open-goal/jak-project#2439]
https://user-images.githubusercontent.com/48171810/227747293-d52b2b1c-05be-43cb-9d3c-c44a133a42c4.mp4

**Comment by water111** [comment]
The jump in rotation was fixed by #2430, but the first jump still happens.

**Comment by ManDude** [comment]
Make sure it's not something that happens in the original game that was covered by the blackout.
