### ISSUE TITLE
Jak and Daxter the precurssor legacy Black Screen

### ISSUE THREAD

**Issue by CaioGpaly** [open-goal/jak-project#2465]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Every time I open jak 1 the monitor screen goes black and a "no signal" message appears. Just by opening the game this happens. You can hear the game open and running, but no image appears.

### How To Reproduce

Just opening the game in OpenGOAL.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

When I open the game, the image should appear on the screen.

### Operating System

Windows 10

### OpenGOAL Version

v2.0.9

### Game Version

NTSC 1.0 (black label)

### Are you using a high refresh-rate monitor (>60Hz)

No

**Comment by xTVaser** [comment]
Most people that have reported this problem have had suggest resetting their settings, see if that helps you.

![image](https://user-images.githubusercontent.com/13153231/230949044-c27ad85e-7e99-4519-a113-c90aeaa0f845.png)

**Comment by CaioGpaly** [comment]
> Most people that have reported this problem have had success resetting their settings, see if that helps you.
> 
> ![image](https://user-images.githubusercontent.com/13153231/230949044-c27ad85e-7e99-4519-a113-c90aeaa0f845.png)

Thank you very much, it solved my problem, now I can enjoy this wonderful port.
