### ISSUE TITLE
yakow textures are bad

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#2529]
`login<1> could not find texture 14 in obj #<merc-ctrl yakow-lod0 :length 0 @ #x2facc74> shader 2fadcf0`

**Comment by water111** [comment]
Bad textures:
it seems like both the extractor and the original GOAL texture code can't find this texture.

The original GOAL code would end up printing that error and setting some messed up texture settings on the GS. (unclear if this case is also hit on the original game, but I'm guessing it is)

![Image](https://github.com/open-goal/jak-project/assets/48171810/a4feca52-1923-45d6-92f9-7a319e51e316)
