### ISSUE TITLE
Jak 1 Project board is not properly linked to the jak-project repository.

### ISSUE THREAD

**Issue by Zedb0T** [open-goal/jak-project#2589]
https://github.com/orgs/open-goal/projects/1

![image](https://user-images.githubusercontent.com/89345505/235326983-de9709f3-7dad-4be9-9d52-d170044c7b7c.png)
![image](https://user-images.githubusercontent.com/89345505/235326989-8ead38c9-bb3d-442a-9741-a1d711244803.png)

It exists here tho https://github.com/orgs/open-goal/projects
Just isnt tied to the jak-project repo

![image](https://user-images.githubusercontent.com/89345505/235327007-b90b758f-7b6b-49a7-b222-3b60196eec47.png)

**Comment by xTVaser** [comment]
I can fix this up, tbh there isn't really a benefit to having multiple boards since we can just make filter views on one.  So I'm just going to make the current one we are using not jak 2 specific and close the other.
