### ISSUE TITLE
New `defpart` format causes full game compilations to take about twice as long

### ISSUE THREAD

**Issue by xTVaser** [open-goal/jak-project#2591]
The new changes introduced here https://github.com/open-goal/jak-project/commit/0ce5835818a1e6223281939b9e801704f9091cac cause full game compiles to take about twice as long.

On my setup:
```
> Successfully built all 1063 targets in 12.467s
vs
> Successfully built all 547 targets in 20.777s
With the latest commit that attempts to optimize it:
> Successfully built all 544 targets in 20.242s
```

On water's
```
for me: 16s -> 40s
```

**Comment by ManDude** [comment]
Is this still a problem? The games compile very fast for me now.

**Comment by xTVaser** [comment]
It's still significantly faster than it was prior to the changes yeah.  I'm not aware of any improvements since water's attempt that only sped it up by around 50%

**Comment by water111** [comment]
I think this is not an issue any more - I made GOOS a lot faster and it's not much of a bottleneck for compilation speed.
