### ISSUE TITLE
[jak 2] Crash when taking the elevator to the palace cable.

### ISSUE THREAD

**Issue by water111** [open-goal/jak-project#2619]
I started the city-power mission from the debug menu, played through it normally, then went to the elevator and got:
```
[45:08:604] [info] link finish: jak-pole+0
dkernel: trying to redefine a type 'int32' with 11 methods when it had 0, try restarting
[45:08:620] [die] Assertion failed: 'false'
```
this happened right as the city unloaded so I am suspicious that this is some "use after unload" bug.

**Comment by ManDude** [comment]
sigh
![image](https://user-images.githubusercontent.com/7569514/236377191-08753472-d4b5-4b60-a49a-3d02968e9ea6.png)

**Comment by ManDude** [comment]
Can't reproduce, sadly.

**Comment by ManDude** [comment]
Superseded by #3153
