### ISSUE TITLE
[menu blit] single frame of nothingness

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#2621]
For a single frame when the progress menu is opened and closed, all of the background renderers are turned off while the sprite renderer isn't, leading to a flicker where all glow sprites pass the depth test. When the progress menu is closed, the blit is not drawn so you can also see a single frame of black from the lack of background rendering.

**Comment by water111** [comment]
The single frame of black when closing is gone, but the glow sprite issue is still there.

**Comment by ManDude** [comment]
Glow sprite happens in the original game, not worth fixing right now.
