### ISSUE TITLE
[jak2] scissoring bugs

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#2630]
![image](https://user-images.githubusercontent.com/7569514/236648320-1aefa800-4fbb-4028-a016-30c593000db8.png)
![20230506230503117_gk_nDpKtZ8stV](https://user-images.githubusercontent.com/7569514/236648358-bcff5216-0437-43d0-ac0a-28994738ec5c.png)

**Comment by ManDude** [comment]
Actually caused by #2397 bad fullscreen detection

**Comment by xTVaser** [comment]
can you provide more detail, what do you mean by fullscreen _detection_?  The mode is explicitly set (and has some issues with setting properly  / using the correct resolution).  But im not sure what you are referring to by detection

**Comment by ManDude** [comment]
Nevermind, this might actually be my bad lol I think the letterbox region isn't accounted for in some scenarios.
