### ISSUE TITLE
[jak2] `fill-bg-using-box-new` infinite loop

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#2679]
The `t5` register can sometimes get a very bad result and this branch gets completely screwed up:
```cpp
  c->daddiu(t5, t5, -1);                            // daddiu t5, t5, -1
  // nop                                            // sll r0, r0, 0
  bc = c->sgpr64(t5) != 0;                          // bne t5, r0, L69
  c->daddu(t9, t6, t8);                             // daddu t9, t6, t8
  if (bc) {goto block_3;}                           // branch non-likely
```
![image](https://github.com/open-goal/jak-project/assets/7569514/3e2c3b6b-faf6-4fa1-8304-250e5f46edca)

It seems to get triggered by the crimson guard hover guards quite often. There is a continue point at the end of fortress rescue next to two hover guards. Messing around with them will eventually cause the game to hang on that code forever.

**Comment by water111** [comment]
Likely the same as https://github.com/open-goal/jak-project/issues/2618, which happened in a totally separate level.

**Comment by water111** [comment]
I'm not convinced this is the same as 2618 so I will leave that open for now.
