### ISSUE TITLE
blue debug line on water platforms

### ISSUE THREAD

**Issue by water111** [open-goal/jak-project#2687]
![Image](https://user-images.githubusercontent.com/48171810/235542467-9ccfee38-9d6d-4d1a-977d-f98c3c37b06a.png)

This blue line shows up the first time you get near a platform. Seems to happen once, each time you reload the level.
I think it happened to Zed in the dig lava platforms too.

The cause for this is line 1207 in `rigid-body.gc`. - Hat Kid

**Comment by water111** [comment]
Looks like this happens in the real game in debug mode too - nothing for us to fix.

**Comment by ManDude** [comment]
I've had it show up on the Rift Rider in defend stadium. It looks like it's a rigid physics object too.
