### ISSUE TITLE
[sprite-glow] occasional flickering issue

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#2735]

**Comment by BreakPoints** [comment]
Consistently triggers on the title screen

**Comment by ManDude** [comment]
yeah it happens everywhere

**Comment by water111** [comment]
just so i don't forget: this billboard is a reliable way to trigger it
![image](https://github.com/open-goal/jak-project/assets/48171810/d587d08d-f69f-42bc-a497-e4cd845fbe79)
