### ISSUE TITLE
[jak 1] Could you add a control sheet for players using a keyboard?

### ISSUE THREAD

**Issue by Xxravenshadow14xX** [open-goal/jak-project#2737]
### Is your feature request related to a problem?

I just installed the game recently, and do not have the money to purchase a real controller to use with the game. 

### Describe the solution you'd like.

I think you should add a part of the launcher that shows the controls for keyboard players for both Jak 1, as well as Jak 2 (for when that one is finished)

**Comment by Zedb0T** [comment]
Hi, 

In the development build of the game there is currently a feature that lets the users set their own keybinds, I have attached a video of it below. With this you are free to pick any input setup you would like!

It should be included in next months release after some more testing.

https://github.com/open-goal/jak-project/assets/89345505/b65aa219-8867-4688-b483-3f6fb23c9b45

**Comment by Zedb0T** [comment]
Ill go ahead and create a feature request in the launcher repo, it would be a good first issue for someone to contribute to. There are a few things that need to be considered but it would certainly be possible to sync up the options with the current installation and display them in the launcher.
