### ISSUE TITLE
PAL strings aren't used in introductory cutscene

### ISSUE THREAD

**Issue by ticky** [open-goal/jak-project#2793]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Right at the beginning after starting a new game, the "Sony Computer Entertainment [X] Presents" card shows the SCEA string even when built from a PAL disc. Changing the text and subtitle languages have no effect.

My disc copy matches the hashes of the expected PAL build.

My un-educated guess is that this is because the [`scf-get-territory`](https://github.com/open-goal/jak-project/blob/cf295952b68eef4466b46b0b29c4f7d2c72a5cff/goal_src/jak1/engine/game/main.gc#L362) function checks the (possibly default?) main language, and not the current text language.

### How To Reproduce

1. Import PAL copy of the game
2. Start a new game
3. Observe that "Sony Computer Entertainment America" are credited

### Does this problem occur on original hardware or PCSX2?

Not needed, bug is obvious

### Expected Behavior

When in UK English, or if built from PAL sources, it should read "Sony Computer Entertainment Europe"

### Operating System

Linux (SteamOS 3.5)

### OpenGOAL Version

v0.1.38

### Game Version

PAL

### Are you using a high refresh-rate monitor (>60Hz)

No

**Comment by ManDude** [comment]
Are you using the launcher?

**Comment by ticky** [comment]
Yes, v2.1.4

**Comment by ManDude** [comment]
Are you launching the game in debug mode?

**Comment by ticky** [comment]
I don't believe so, I haven't turned on any debug features myself. I'll double check with `ps` once I get the chance, though.

**Comment by ManDude** [comment]
Err, if the REPL is connected at all then that means that yes, you are in debug mode. The game region function works differently between debug mode and retail mode.

**Comment by ticky** [comment]
I don't have a REPL up, I meant checking args with a separate terminal session

**Comment by ticky** [comment]
Okay, yeah, debug mode is a separate button I haven't touched before.

The `gk` process is running with this command line:

```bash
/home/deck/Games/OpenGOAL/versions/official/v0.1.38/gk -v --game jak1 --proj-path /home/deck/Games/OpenGOAL/active/jak1/data -- -boot -fakeiso
```

**Comment by ManDude** [comment]
Oh right, `ps` is also just a normal command on most shells lol

The arguments used to launch the game will not affect the region. The region is set by the extractor when it compiles the game.

**Comment by ticky** [comment]
Ah, okay, any useful debug data I can gather from that, then?
