### ISSUE TITLE
In-game Daxter mouth movement

### ISSUE THREAD

**Issue by Gorilli09** [open-goal/jak-project#2812]
### What feature is your idea related to?

Whenever Daxter talks in-game, I noticed that his mouth doesn't move.

### Describe the solution you'd like.

Daxter's mouth should move whenever he talks in-game like giving Jak advice.

**Comment by Zedb0T** [comment]
Is there a specific cutscene you have noticed this in? Or are you referencing when daxter talks mid gameplay giving ambient hints?

**Comment by ManDude** [comment]
This has never been how the original games worked.

**Comment by ManDude** [comment]
I guess it was a suggestion, though. You can add this to https://github.com/open-goal/jak-project/discussions
