### ISSUE TITLE
[jak1] semi-random crash in snowy mountain near fortress

### ISSUE THREAD

**Issue by Zedb0T** [open-goal/jak-project#2813]
Thread link: https://discord.com/channels/756287461377703987/1120442595043197008/1120442595043197008

https://user-images.githubusercontent.com/89345505/251772385-af00dc3a-a09d-4e4c-b310-899cfc7b3220.mp4

call stack
https://cdn.discordapp.com/attachments/1120442595043197008/1126611493627105410/message.txt

seems to possibly happen due to the ice-cube but cant be sure yet.

**Comment by water111** [comment]
Fixed in https://github.com/open-goal/jak-project/pull/2851
