### ISSUE TITLE
Jak 1 actor culling option is flipped?

### ISSUE THREAD

**Issue by Aloqas** [open-goal/jak-project#2815]
It noticed that the Actor Culling option seems to work in reverse, as actors are reduced when Off instead of when On. I assume this isn't the expected behavior, as Particle Culling reduces particles when On.

Actor Culling off:
![jak1_2023-07-08T01-37-19](https://github.com/open-goal/jak-project/assets/102683375/a3bdc6b0-7505-49db-a128-991e8fd87167)

Actor Culling on:
![jak1_2023-07-08T01-37-03](https://github.com/open-goal/jak-project/assets/102683375/80c05652-e224-426f-a169-eaae3bbd24e3)

(see the barrels and orbs)

This is on the release v0.1.38

**Comment by ManDude** [comment]
Yes, I noticed this too. The menu text is wrong.

**Comment by Zedb0T** [comment]
Closed by #2852
