### ISSUE TITLE
[jak1] music panning very wrong on a few tracks

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#2820]
sunken and ogre boss themes are very wrong.

**Comment by water111** [comment]
I looked at sunken (Game... Continue... sunken-start), and it seems like it's been like this since audio was first implemented.

From what I can tell, it comes from the `MusicBank`, where the `MIDISound::Pan` value is 64. We use 0 for no pan.

**Comment by Ziemas** [comment]
Yeah, I've not figured out what's going on here yet. The panning option is specified in the sound bank and I don't know why it would be wrong.
