### ISSUE TITLE
Crashes due to OVERLORD RAMDISK OOM'ing / running out of files

### ISSUE THREAD

**Issue by xTVaser** [open-goal/jak-project#2844]
Easiest way to reproduce is to boot Jak 1 and select the `village3-warp` continue point.  This issue has been around for a while, I believe I've traced it back to https://github.com/open-goal/jak-project/commit/cb895d4ba01be22cfd178ac54cc35094582a47e7 which given the nature of the changes seems very plausible.

```
Displaying level village3 [display]
Adding level ogre
-----------> begin load ogre-vis [ogr.DGO]
Starting level load clock
Swapping in vi3 VIS [dumping #f]
[54:00] [debug] [OVERLORD] Queue 0 (1/4), LoadDGO
GAMEPLAY: enter village3
[54:00] [debug]   PRI 0 elt 0 LoadDGO @ #x7FF60F34D908
[54:00] [debug] [OVERLORD] FS Open OGR     DGO
[OVERLORD RAMDISK] Failed to load file because RAMDISK is out of memory or files!
[OVERLORD RAMDISK] Failed to find ISO file for read.
task: Failed to run task "boot-game": exit status 5
task: Failed to run task "boot-game": exit status 5
```

But at times this issue also feels intermittent.

Discord thread with more info - https://discord.com/channels/756287461377703987/1131445305242566687

**Comment by water111** [comment]
The code immediately before this does:
```
    // reset files and memory
    gNumFiles = 0;
    gMemUsed = 0;
```

So I suspect that something else bad is going on.

I added some extra print statements in https://github.com/open-goal/jak-project/pull/2842 to get more info. I wasn't able to recreate the problem. If somebody else can run with these print statements and capture the output, it would be useful.

**Comment by water111** [comment]
I believe this is fixed - please reopen if you see it again.
