### ISSUE TITLE
Certain shrubbery is translucent when it shouldn't be

### ISSUE THREAD

**Issue by Margen67** [open-goal/jak-project#2882]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

In some places certain `shrubbery` is translucent even though it should be opaque.

Cups and plates in Rock Village (near `village2-dock`):
![jak1_2023-08-04T17-32-02](https://github.com/open-goal/jak-project/assets/3462541/22c3c12f-ba8c-4bab-b2ea-6cba7501e51a)
Chains in Misty Island (near `misty-bike`):
![jak1_2023-08-04T17-19-45](https://github.com/open-goal/jak-project/assets/3462541/c077b5ff-7830-4df6-8bf3-c1fe9b3aeaf8)

This is just what I've noticed in my playthrough so far, so there might be more anomalies I don't know about.

### How To Reproduce

1. Go to the areas in the screenshots.
2. Profit

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

`shrubbery` should always render properly.
* Rock Village:
    * https://youtu.be/IZX9_CsW1fc?t=433
    * https://youtu.be/egFOnGTIwm0?t=84
* Misty Island:
    * https://youtu.be/fdkBmVesDj8?t=536

### Environment Information

[opengoal-support-package.zip](https://github.com/open-goal/jak-project/files/12265337/opengoal-support-package.zip)

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

Yes

**Comment by dallmeyer** [comment]
Are you using any texture pack?

**Comment by Margen67** [comment]
> Are you using any texture pack?

No.

**Comment by Zedb0T** [comment]
![image](https://github.com/open-goal/jak-project/assets/89345505/db1be9f3-1cd0-4d36-b5ff-5b097619b6be)
![image](https://github.com/open-goal/jak-project/assets/89345505/5d5e8e2d-072d-428d-9f50-0a5792bf39ce)

**Comment by Zedb0T** [comment]
This is master with #2853 reverted

![image](https://github.com/open-goal/jak-project/assets/89345505/d7ae6e1b-1d92-43ea-8801-c0e50ddef735)

**Comment by water111** [comment]
Should be fixed in https://github.com/open-goal/jak-project/pull/2899
