### ISSUE TITLE
Windows 11 Display Scaling causing game to minimize

### ISSUE THREAD

**Issue by Kuitar5** [open-goal/jak-project#2930]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

On windows 11, it seems like the game automatically minimize to the task bar every time I open it if the scaling is not set to 100% 

The setting can be found on `System > Display > Scale & layout > Scale`

Clicking on the icon in the task bar would also automatically minimize it which made it unusable.

This seems to be a problem that can happen to lot of fullscreen applications on w11 so not sure it's fixable on the project's side. But I still wanted to note it down.

### How To Reproduce

- Use Windows 11
- Go to this setting `System > Display > Scale & layout > Scale`
- Change it to a value that's not `100%`, for example `125%`
- Start the game
- The game should automatically minimize to the task bar
- Trying to click on it should show the game for a fraction of a second then go back to minimized

### Does this problem occur on original hardware or PCSX2?

Didn't check

### Expected Behavior

Starting the game shouldn't automatically minimize it, especially after trying to click on it again.

### Environment Information

- OpenGOAL v0.1.39
- Windows 11 Version 22H2
- CPU: Ryzen 5800H
- GPU: RTX 3070 (portable)
- RAM: 16GB

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by bob7l** [comment]
You should be able to disable scaling for specific applications through properties->Compatibility->Change high DPI settings

OpenGoal could implement a fix too: 
https://learn.microsoft.com/en-us/windows/win32/api/shellscalingapi/nf-shellscalingapi-setprocessdpiawareness

**Comment by xTVaser** [comment]
what you linked was attempted, it fixed some problems, clearly not all of them. https://github.com/open-goal/jak-project/pull/2730/files

**Comment by bob7l** [comment]
> what you linked was attempted, it fixed some problems, clearly not all of them. https://github.com/open-goal/jak-project/pull/2730/files

Have you tried to set it in the manifest? 

https://learn.microsoft.com/en-us/windows/win32/api/shellscalingapi/ne-shellscalingapi-process_dpi_awareness

`Important  

For older applications, it is strongly recommended to not use SetProcessDpiAwareness to set the DPI awareness for your application. Instead, you should declare the DPI awareness for your application in the application manifest. See [PROCESS_DPI_AWARENESS](https://learn.microsoft.com/en-us/windows/desktop/api/shellscalingapi/ne-shellscalingapi-process_dpi_awareness) for more information about the DPI awareness values and how to set them in the manifest.`

**Comment by xTVaser** [comment]
No because:
- no idea how to make the manifest, we don't have a manifest at all
- SDL is supposed to handle this for us in some way, we are just doing something wrong / missing something.

SDL3 is supposed to make handling DPI much, much easier.  And there's many issues over on their repo with people talking about potential solutions / fighting with things not working.

**Comment by Zedb0T** [comment]
For what its worth, I was not able to replicate this issue on 2.20

**Comment by xTVaser** [comment]
Reopen if this can still be replicated
