### ISSUE TITLE
[sprite] double check sprite counts

### ISSUE THREAD

**Issue by water111** [open-goal/jak-project#2948]
In this case we have ~130 blocks and ~6k sprites. Distort claims to be drawing 1680 tris and 2d draws 512 tris.
![image](https://github.com/open-goal/jak-project/assets/48171810/17d7d298-21a6-4c6f-b4a5-4013b88f8d20)

I've kind of suspected this for a long time (since jak 1), but I think our modifications to the maximum number of sprites has caused the sprite allocator in GOAL to not work very well, causing us to send/process a lot of sprites that are never drawn. (but possibly still uploaded to the gpu?)

It's probably time to double check sprite performance again. I'm not convinced it's really doing much work here, yet it's taking ~1 ms.

**Comment by ManDude** [comment]
![image](https://github.com/open-goal/jak-project/assets/7569514/d56b3b3d-e070-4987-9f75-5ea7fe2a1d91)
The counts seem to match the GOAL thread. That said I'm also curious wtf in the city is spawning thousands of particles.

**Comment by ManDude** [comment]
sometimes when I despawn all of these particle spawners, the counts mismatch for a few seconds and then seem to get corrected somehow

![image](https://github.com/open-goal/jak-project/assets/7569514/93d9554c-995e-497c-b308-f5828027f4cd)

**Comment by water111** [comment]
I confirmed that a similar problems in both jak 1 and jak 2. Going near the sentinel beach waterfall is enough to trigger it, even if you then move away/despawn it.

The sprites are sent to the sprite renderer in blocks (each block is one run of the VU1 program). Each block holds up to 48 sprites, but some sprites may be disabled and not drawn. After the waterfall is drawn, there GOAL side sends many blocks with only very few (~0-3) sprites. For example, we might draw ~200 sprites, but send ~11,000 sprites, most of which are disabled.

I think there is some logic for sprite allocation that isn't working properly once the sprite array was made bigger. (or their code doesn't handle this case well).

We could optimize the sprite renderer to handle this better, but it seems like the better fix is to get the GOAL side to send fewer blocks when we aren't drawing many sprites.

**Comment by water111** [comment]
one confusioning point is that packets are send in groups of 48 to the VU1, but the sparticle system handles "blocks" of 64. We've accidentally named the 48-sprite groups "blocks" in the C++ renderer, but this is a separate concept from the "block" in the allocator.
