### ISSUE TITLE
Jak 1 Reset controller settings does not reset back to the original controller that gk used to select before choosing one.

### ISSUE THREAD

**Issue by Zedb0T** [open-goal/jak-project#2950]

**Comment by xTVaser** [comment]
Would this even make sense to do?
1. You are selecting the option with a controller, so you'd rather it stay on whatever one is considered active
2. The controller logic should already ignore controllers that are preferred, but are no longer plugged in.  (ie. if you normally use a PS5 controller but the next time you launch a game you only have a 360 controller plugged in, it should pick the 360 controller.  If you later launch the game with the PS5 controller plugged back in, it'll pick that one instead).
    - If this isn't working and was the motivation for this issue, let me know and ill fix that instead.  Otherwise, i think this is a close.

**Comment by xTVaser** [comment]
Closing based on the above, if im mistaken reopen and clarify.
