### ISSUE TITLE
Tie wind objects over extracted

### ISSUE THREAD

**Issue by TROYNELSON12** [open-goal/jak-project#2967]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Tie wind objects have their mesh extracted far more than once, it seems to be once per object from what little into I've gathered. For firecanyon with it's ~750 tie wind objects each object would have ~750 copies of its mesh in the same place.

### How To Reproduce

Extract the level geometry and open any level with tie wind objects in Blender, firecanyon is especially notable with it taking tens of gigabytes of ram to load.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

Not have hundreds of copies of the same mesh in the same place.

### Environment Information

OpenGOAL version 46c634686 since tie wind exporting was added as of pull request #2960.

### Game Version

NTSC Greatest Hits version (red label)

### Have you set the game to something other than `60fps`?

No

**Comment by TROYNELSON12** [comment]
Something else I noticed is the trees seem to be getting duplicated to other tree positions as well, there's a lot of trees that shouldn't be there.

OpenGOAL:
![image](https://github.com/open-goal/jak-project/assets/22382517/68b142e0-0814-4310-8fb7-92c05640736e)
Exported:
![image](https://github.com/open-goal/jak-project/assets/22382517/75ad704d-57af-47c9-bb58-f37220a7162b)

OpenGOAL:
![image](https://github.com/open-goal/jak-project/assets/22382517/022915a1-1971-497e-893c-64801c5a330b)
Exported:
![image](https://github.com/open-goal/jak-project/assets/22382517/9e4c5b51-69b0-431e-a865-f2fbd76bf0ed)

This was after merging by distance to get rid of all the duplicate trees I mentioned above.

**Comment by ManDude** [comment]
it's time to begin deforesting

**Comment by water111** [comment]
I think I've fixed this in https://github.com/open-goal/jak-project/pull/2972 - firecanyon doesn't use GBs of RAM for me in blender, and the incorrectly placed trees (and other meshes) are gone too.

That said, I am not 100% sure it is totally fixed. If there's still an issue with multiple copies on top of each other, can you let me know how I can check this in blender?

**Comment by TROYNELSON12** [comment]
I don't know of any proper way of checking, I just switched to edit mode and saw the tie wind objects as all white because of all the overlapping highlights. It's fixed though.
