### ISSUE TITLE
[jak 2] freeze in guards turret mission

### ISSUE THREAD

**Issue by water111** [open-goal/jak-project#2970]
<img width="210" alt="image" src="https://github.com/open-goal/jak-project/assets/48171810/00360137-c3ec-4416-a59b-b7a9884d704a">

3 separate reports of this. Looks like normal behavior for GOAL stuck in a loop. happened with 17 guards left, looks like it is in debug mode too.

**Comment by Zedb0T** [comment]
https://www.twitch.tv/videos/1919753416?t=7h30m0s

**Comment by Zedb0T** [comment]
Might not be fixed - 
![image](https://github.com/open-goal/jak-project/assets/89345505/7d6872ef-eed7-4220-a54f-29d3e02d2baa)

@water111
