### ISSUE TITLE
[jak2] Sound classified as speech ignores speech-volume setting

### ISSUE THREAD

**Issue by blahpy** [open-goal/jak-project#3004]
Anything that uses speech volume such as cutscenes, character speech and dark bomb sound effects ignore the speech-volume setting and play at 100% (I think?) volume if speech volume is set to a non-zero value.

Commit number in the top right of the game is bfb03d493 which was downloaded today

Possibly related to #2635 ???

**Comment by ManDude** [comment]
Interesting. I think volume is just straight up not working for streamed audio.

**Comment by ManDude** [comment]
I'm not getting this, actually.

**Comment by blahpy** [comment]
I'm also not able to reproduce it any more, despite it happening both times I built + started the game yesterday.
I'll close this for now and reopen if I figure out the cause
