### ISSUE TITLE
[jak2] After driving to keira, race starts immediately

### ISSUE THREAD

**Issue by Zedb0T** [open-goal/jak-project#3022]
Should spawn outside of garage, then reset mission and end up in the race

**Comment by ManDude** [comment]
Do you mean skateboard challenge? Because the steps you described is what happens to me right now.

**Comment by Zedb0T** [comment]
Sorry I mean the drive to stadium to start the class 2 race

**Comment by Zedb0T** [comment]
nvm headstrong is crazy

**Comment by ManDude** [comment]
The race starting immediately is the intentional behavior.
