### ISSUE TITLE
Jak 1 `draw-string-xy-scaled` is buggy 

### ISSUE THREAD

**Issue by dallmeyer** [open-goal/jak-project#3038]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

The `draw-string-xy-scaled` function I added in #1756 doesn't quite work properly - it does scale the text, but in doing so it scales the available screen space that the text can be drawn to. So say your scale is 0.5, then any text in the lower and/or right half of the screen would get cut off.

Spoke to Vaser a bit about this and he suggested replacing with `draw-string-adv` instead, setting the scale in the `font-context`, but the issue is that `draw-string-adv` (really `draw-string` itself) doesn't do anything with the `font-context`'s scale, at least in [Jak 1 where we use the GOAL implementation](https://github.com/open-goal/jak-project/blob/1f4044b9ffcd0836e33f2ab68ad1563891ab8016/goal_src/jak1/engine/gfx/font.gc#L610-L615)

In Jak 2, I believe it's using the [mips2c implementation of `draw-string`](https://github.com/open-goal/jak-project/blob/master/game/mips2c/jak2_functions/font.cpp), and apparently this does respect the font context - maybe this is a bug in the Jak 1 GOAL implementation?

### How To Reproduce

`draw-string-xy-scaled` with a scale like 0.5 and you won't be able to draw text to the right/bottom of screen

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

`draw-string` (whether through a helper function like `draw-string-xy-scaled` or otherwise) should support scaling text properly to all areas of the screen

### Environment Information

All environments

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by ManDude** [comment]
Your implementation looks like it's based on `print-game-text-scaled`, which doesn't actually work properly in the original game anyway.

**Comment by dallmeyer** [comment]
Actually I did some more testing and it's only an issue vertically - you can get scaled text on the right side of the screen as you'd expect, but whatever logic decides if a line is cut off or not _vertically_ isn't respecting the scaling
