### ISSUE TITLE
Korean language breaks on Discord Rich Presence

### ISSUE THREAD

**Issue by slysonic** [open-goal/jak-project#3074]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Playing the game on Korean breaks the text on Discord rich presence, sometimes showing UNKNOWN ID or random strings of characters seen in image. 
![image](https://github.com/open-goal/jak-project/assets/76589545/70a301f9-d185-48e4-8158-4d93445f9f39) 
Probably is known, I dunno, but other languages including Japanese display fine. 
Also a similar "bug" with Korean language (which I don't think is in PAL PS2?) misaligns the "g" in UK English (not seen in US English oddly enough) 
![image](https://github.com/open-goal/jak-project/assets/76589545/553558d6-57d4-46d5-aa7f-dc8b3985cb98)

### How To Reproduce

Switch "Language" to Korean. I personally do this through the debug L3+Start menu and from quick testing the same issues show when selecting language through Game Settings

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

the language doesnt break lol

### Environment Information

Played through unofficial mod launcher, v0.1.42

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by ManDude** [comment]
Superseded by #3075
