### ISSUE TITLE
fullscreen doesn't work on macOS

### ISSUE THREAD

**Issue by jmast12054A** [open-goal/jak-project#3099]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak1+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

fullscreen doesn't work iv tried messing with all the graphics and aspect ratio settings even ran the game on another MacBook its just a small box in the screen 

![jak 02 PM](https://github.com/open-goal/jak-project/assets/12482474/4c3c5b6d-b890-4421-9640-931291112507)
 iv tried different tooling version pretty much anything I can think of the problem doesn't happen in pcsx2

### How To Reproduce

I'm on macOS 14.0

3.3 GHz Quad-Core Intel Core i7
Intel Iris Pro Graphics 6200 1536 MB
16 GB 1867 MHz DDR3

the game runs good just won't go into fullscreen

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

I really don't know what to do iv read all the documentation trying to see if I was configuring something wrong

### Environment Information

[opengoal-support-package.zip](https://github.com/open-goal/jak-project/files/13064418/opengoal-support-package.zip)

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by Zedb0T** [comment]
Another report of this issue in the discord here -> https://discord.com/channels/756287461377703987/1171006804117950485/1171006804117950485

**Comment by revblaze** [comment]
Hope this gets resolved soon. Occurs with both Jak & Daxter, as well as Jak 2. I've tried every single config option, but to no avail.

<img width="1680" alt="Screenshot 2023-12-23 at 12 00 04 PM" src="https://github.com/open-goal/jak-project/assets/1476332/bbda515d-3cdc-4af4-ad08-26c871cde799">

<img width="1680" alt="Screenshot 2023-12-23 at 12 00 12 PM" src="https://github.com/open-goal/jak-project/assets/1476332/66443ac7-f231-40ae-bddd-5bbbb5b2e2d3">

**Comment by revblaze** [comment]
Also halves the size in window mode. Perhaps this is an issue with over compensating for the retina 2x display?

<img width="752" alt="Screenshot 2023-12-23 at 12 09 13 PM" src="https://github.com/open-goal/jak-project/assets/1476332/99bf4b56-808b-4f98-a34f-6e180f0563c1">

**Comment by Zedb0T** [comment]
https://discord.com/channels/756287461377703987/1171006804117950485/1171155383352574102

Reported about 3 times, none of the contributors currently have a intel mac so its unlikely to get fixed until/if someone with a intel mac starts working actively on the project again

**Comment by revblaze** [comment]
@Zedb0T I wouldn't even know where to begin, but if any of the devs had an idea of where the problematic code might be happening, I could definitely give it a look!

**Comment by xTVaser** [comment]
We use SDL2 and all of the display related code should be found here https://github.com/open-goal/jak-project/blob/master/game/system/hid/display_manager.cpp I'd hope the problem is somewhere in there and not in the actual OpenGL rendering code.

**Comment by revblaze** [comment]
@xTVaser Thanks a lot! I still haven't been able to build successfully on the latest version of Sonoma, but I'll keep at it.

**Comment by xTVaser** [comment]
Might be easier to talk back and forth in the discord if you are able to join, hopefully the README steps are still accurate for sonoma, they worked for ventura (when i last had an intel mac)

**Comment by Zedb0T** [comment]
(https://discord.gg/VZbXMHXzWv)

**Comment by revblaze** [comment]
@xTVaser @Zedb0T Appreciate it! I'm currently recovering from gum graft surgery but I'll hopefully get on the Discord at some point.

**Comment by revblaze** [comment]
I'm sure this won't be of much help, but in the meantime and just in case it is, here is the session output per build instructions:

- [session1.txt](https://github.com/open-goal/jak-project/files/13762099/session1.txt)
- [session2.txt](https://github.com/open-goal/jak-project/files/13762098/session2.txt)

**Comment by xTVaser** [comment]
Looks like it's related to this https://github.com/zyantific/zydis/issues/350 we'll have to update this third-party dependency.

**Comment by fabjan** [comment]
I saw this open issue and wanted to have a go at seeing what it could be, knowing I was able to run the game and fix code before on my Mac.

But I cannot reproduce the problem, I think. I tried both building OpenGOAL from latest master, and using the latest released launcher and the latest tooling from that. I can run Jak 1 in fullscreen just fine.

If I use windowed mode, the green little "enter fullscreen mode" from macOS gives me a crisp full screen view of the game. Maybe this is not fullscreen? But I also tried the options menu to select the "fullscreen" display mode, and that  gave me a proper fullscreen view of the game.

Maybe this depends on your hardware or OS version? To help investigate I'll share my specs (according to neofetch):

```
OS: macOS 13.4.1 22F82 x86_64 
Host: MacBookAir8,2 
Resolution: 2560x1440@2x 
CPU: Intel i5-8210Y (4) @ 1.60GHz 
GPU: Intel UHD Graphics 617 
```

I have the PAL version of Jak 1.

**Comment by xTVaser** [comment]
Ah i had missed that you replied to this @fabjan If you are still interested in digging in, there's this discord thread where people shared some more context / some hardware info https://discord.com/channels/756287461377703987/1171006804117950485/1171006804117950485
