### ISSUE TITLE
Warpgate "jump in" animation is skipped if you have i-frames

### ISSUE THREAD

**Issue by dallmeyer** [open-goal/jak-project#3105]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak1+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

If you have invincibility frames while using a `warpgate` portal, the animation for jumping into the portal gets skipped and the screen cuts to black. On PS2 the jumping in animation still plays, regardless of i-frames.

### How To Reproduce

Take fall damage to get invincibility frames, then use a `warpgate` portal, and the animation for jumping into the portal will get skipped 

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

jump in animation plays like normal

### Environment Information

Confirmed an issue on latest release 0.1.43, but I went all the way back to 0.1.0 and it was an issue there as well

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by dallmeyer** [comment]
PS2:
https://github.com/open-goal/jak-project/assets/2515356/72ee2531-57cf-457e-986f-450490d62d66

OpenGOAL (without and with i-frames):
https://github.com/open-goal/jak-project/assets/2515356/813794a8-37a6-4211-8eed-25cf100fa31c

**Comment by ManDude** [comment]
Intended behavior. This warp gate waits until Jak goes invisible to do the actual warp, which the flickering effect will toggle on and off.

**Comment by dallmeyer** [comment]
Some more context in case someone comes across this later - original code has a check that allows for this behavior at the citadel/lavatube warp gate. OpenGOAL extended this check to the geyser warp gate as well due to differences in how files are loaded/unloaded

https://github.com/open-goal/jak-project/blob/fc43870d859562fb6510380c23e0c95d6723d362/goal_src/jak1/engine/common-obs/basebutton.gc#L481-L488
