### ISSUE TITLE
Left/Right (3rd Person) is Inverted Permanently

### ISSUE THREAD

**Issue by MuchWhittering** [open-goal/jak-project#3116]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

It doesn't matter if you set Left/Right (3rd Person) camera controls to Normal or Inverted, they act inverted at all times.

### How To Reproduce

It doesn't matter if you set Left/Right (3rd Person) camera controls to Normal or Inverted, they act inverted at all times.

This was done using an NTSC ISO, if that's relevant.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

Normal should have Left be Left and Right be Right.

### Environment Information

[opengoal-support-package.zip](https://github.com/open-goal/jak-project/files/13239508/opengoal-support-package.zip)

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by Dethorhyne** [comment]
I am experiencing the same issue, and I'd like to extend that all camera controls seem to be hardcoded and don't respond to any of the 4 options in the menu (1st/3rd person LR / UD). 

Recording showing both controller and screen available here: https://youtube.com/shorts/Xaj4Khhs5vs
Recording shows movement in all 4 axis in 3rd person and first person, then inversion of the controls, and movement in all 4 axis again that are same, instead of inverted.

**Comment by JaredFeeney** [comment]
experiencing the same issue, using a Dualsense controller on linux with latest tooling

**Comment by 0Mazze0** [comment]
Same here, thanks for raising the bug.

**Comment by ManDude** [comment]
The menu options don't do anything right now. Everyone has this bug.

**Comment by RaunchySanta** [comment]
Input settings are currently useless and does nothing as far as I can tell. I have found no changes in controller inversion or mouse input. On a side note, I can't help but complain that Q on keyboard is used for rolling, when shift would be a better option by default.

**Comment by Zedb0T** [comment]
I like Q

**Comment by Veelox-Incident** [comment]
I also can confirm this issue.  Using a DualSense controller.

**Comment by xTVaser** [comment]
This is not a bug or unique to certain controllers, the feature is not implemented. See #3167

**Comment by koel700** [comment]
i can also add that even if you use an external app like DS4 to revert from it the camera controls, they still do not change
