### ISSUE TITLE
Menu Options Not Displaying Properly With PAL ISO

### ISSUE THREAD

**Issue by MuchWhittering** [open-goal/jak-project#3120]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

![jak2opengoalpalmenubug](https://github.com/open-goal/jak-project/assets/149691053/cc075cf6-ebaf-460e-8d1e-33ced7b5c698)

The menus display a lot of UNKNOWN ID text instead of their correct functions when using a PAL ISO.

### How To Reproduce

Install with a PAL ISO.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

The menus should display correctly.

### Environment Information

I don't have it handy unfortunately as I've since reinstalled from NTSC. I can provide the exact ISO I used if you need it.

### Game Version

PAL

### Have you set the game to something other than `60fps`?

No

**Comment by Zedb0T** [comment]
This is expected behavior, custom text is only added in EN_US at the moment, soon it will fall back to EN_US if it doesnt find a proper translation 
#3118
