### ISSUE TITLE
can't boot jak 2 outside of debug mode because of main menu problem

### ISSUE THREAD

**Issue by KayLilac** [open-goal/jak-project#3125]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

when i boot up jak 2 normally the game runs extremely slow and shows no sign of response, on top of that it makes my computer slow down but when i open task manager it doesn't seem to be eating up all my resources.
i can only play if i boot up with debug mode since it skips the main menu.

### How To Reproduce

i really don't know what exactly causes this, i just boot it up and it happens

https://github.com/open-goal/jak-project/assets/149713452/0d8afc36-678b-4857-a827-b1f2dd9ead85

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

when i open the game it runs really poorly to the point of almost looking frozen making the main menu useless and most of the time it just stops responding 

### Environment Information

CPU: 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz
GPU: Intel(R) Iris(R) Xe Graphics
OS: Windows 11 (64-bits)
OpenGOAL Ver: 0.1.44

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by Zedb0T** [comment]
Can you boot it up, then open the debug menu and scroll down to pc-settings and hit save and see if that fixes the retail issue?

**Comment by KayLilac** [comment]
> Can you boot it up, then open the debug menu and scroll down to pc-settings and hit save and see if that fixes the retail issue?

i'll try that

**Comment by Zedb0T** [comment]
![image](https://github.com/open-goal/jak-project/assets/89345505/8d744b2b-6297-4f41-9848-09a4cfa79975)
L3 + start to open the menu

**Comment by KayLilac** [comment]
> Can you boot it up, then open the debug menu and scroll down to pc-settings and hit save and see if that fixes the retail issue?
it didn't fix

**Comment by blahpy** [comment]
If you leave the prison in debug mode does the issue come back?

**Comment by KayLilac** [comment]
> If you leave the prison in debug mode does the issue come back?

yep! i tried it here, this problem seems to be related to haven city for some reason
should i update this post since this is a problem related do haven?

https://github.com/open-goal/jak-project/assets/149713452/b1f2c394-4ad0-445b-bf14-5c48cf05e60d

**Comment by Zedb0T** [comment]
If you open the debug menu, and disable the sky render does it fix it?

**Comment by KayLilac** [comment]
> If you open the debug menu, and disable the sky render does it fix it?

nope

**Comment by ManDude** [comment]
Try turning off "sky textures".

You have an Intel GPU, so I'll be surprised if that doesn't fix the issue.

**Comment by KayLilac** [comment]
> Try turning off "sky textures".
> 
> You have an Intel GPU, so I'll be surprised if that doesn't fix the issue.

oof, yeah that worked XD

**Comment by KayLilac** [comment]
> Try turning off "sky textures".
> 
> You have an Intel GPU, so I'll be surprised if that doesn't fix the issue.

will there be a proper fix for intel gpu's in the future? i understand if it's not priority, just wondering

**Comment by Zedb0T** [comment]
Yeah Its kind of hard for us to get just right and test since we do not have a device that experiences this issues but we are currently investigating this thanks for helping us pinpoint the issue!

**Comment by water111** [comment]
> will there be a proper fix for intel gpu's in the future? i understand if it's not priority, just wondering

Yes! I think I have a fix for it. We actually found the issue just a few days before release and I didn't have the time to fix it...

Fix here, if anybody with a dev environment set up has an intel card and wants to test:
https://github.com/open-goal/jak-project/pull/3130

**Comment by KayLilac** [comment]
oh great! that's nice to hear!

**Comment by KayLilac** [comment]
> Yeah Its kind of hard for us to get just right and test since we do not have a device that experiences this issues but we are currently investigating this thanks for helping us pinpoint the issue!

no worries! you can count on me if i find anymore issues, i like reporting stuff to devs xD
