### ISSUE TITLE
`Select controller` is not working

### ISSUE THREAD

**Issue by xTVaser** [open-goal/jak-project#3129]
> If I have more than one controller connected, in the input options, the "Select controller" option does nothing. When I select another controller, the setting returns to what it was before.

Trying to change controller the "dirty way" (that is, unplugging the controller I don't want to use, so that the one I want to use is the only one that appears) makes it work.

**Comment by Zedb0T** [comment]
Another controller related issue/enhancement, detect if the the multiple controllers share the same name and append something on the end so the user can differentiate them Ps2 controller (1),Ps2 controller (2),Ps2 controller (3) etc

**Comment by SuperSamus** [comment]
I thought I found the cause.

https://github.com/open-goal/jak-project/blob/55611169eecc3c0ce7eed038bf5be66d2230dc33/goal_src/jak2/pc/progress/progress-static-pc.gc#L117

https://github.com/open-goal/jak-project/blob/55611169eecc3c0ce7eed038bf5be66d2230dc33/goal_src/jak2/pc/progress/progress-static-pc.gc#L431

The respective function is defined as:
```c
void pc_get_controller(u32 controller_id, u32 port)
```

Meaning that the lines above should be replaced with:
```
:on-confirm (lambda ((index int)) (pc-set-controller! index 0)))
```

Which is how it is for jak1:
https://github.com/open-goal/jak-project/blob/55611169eecc3c0ce7eed038bf5be66d2230dc33/goal_src/jak1/pc/progress-pc.gc#L1620

However, I tried to change it, recompile, and the bug isn't fixed.

**Comment by SuperSamus** [comment]
Nevermind, I only compiled it wrong.
Doing this partially fixes the issue: visually, it still shows the first controller, but the controller you select is the one that will actually work.
