### ISSUE TITLE
Jetboard training crash in Japanese

### ISSUE THREAD

**Issue by dallmeyer** [open-goal/jak-project#3133]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

When playing the jetboard training mission in japanese, it will crash at a certain point:
https://clips.twitch.tv/CarelessResourcefulBorkTriHard-0KVr3Vam9ba3m5Gf

### How To Reproduce

Play the jetboard training mission in Japanese

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

no crash

### Environment Information

https://www.twitch.tv/atrueboss_

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by dallmeyer** [comment]
likely related to #3137

**Comment by ManDude** [comment]
superseded by #3137
