### ISSUE TITLE
Score UI remains if you exit the gun course from the entrance

### ISSUE THREAD

**Issue by RealSharpness** [open-goal/jak-project#3136]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Score UI for the gun course remains displaying in Haven City when you leave the gun course before finishing it.

### How To Reproduce

1. Start the gun course and observe the score UI at the top is displayed

2. Go back through the entrance and leave out into Haven City, observe the gun course score UI is still displaying as if the mission is still in progress

### Does this problem occur on original hardware or PCSX2?

Didn't check

### Expected Behavior

If Jak leaves the gun course through the entrance and exits to the city, the game should register that the player quit the mission and remove the score UI

### Environment Information

AMD Ryzen 7 5800X 8-Core Processor         3.80 GHz
NVDIA GeForce RTX 3060
Windows 11 version 22H2

OpenGOAL version 2.3.0

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by Hat-Kid** [comment]
The UI eventually goes away when you're far enough from the gun course, which matches PS2 behavior.
