### ISSUE TITLE
The Spinning in the Palace Throne Room Doesn't Work

### ISSUE THREAD

**Issue by MuchWhittering** [open-goal/jak-project#3145]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

When you go to the palace throne room to meet Ashelin late in the game, the world is meant to be spinning when you look outside the window, but it's not.

### How To Reproduce

Play the game.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

The world should be slowly spinning outside.

### Environment Information

[opengoal-support-package.zip](https://github.com/open-goal/jak-project/files/13257216/opengoal-support-package.zip)

### Game Version

PAL

### Have you set the game to something other than `60fps`?

Yes

**Comment by ManDude** [comment]
It's working for me.

**Comment by Hat-Kid** [comment]
Confirmed to be a high FPS bug.

**Comment by ManDude** [comment]
Ah ye, breaks at 144 or higher.

**Comment by xTVaser** [comment]
Fixed in https://github.com/open-goal/jak-project/pull/3147
