### ISSUE TITLE
JAK 2 - ISO Content # does not match Error (Official Copy of game PS2 in my hand)

### ISSUE THREAD

**Issue by Matty2024** [open-goal/jak-project#3149]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

"Installation has Failed! Unexpected error occured with code 4012"

Overall ISO content's hash does not match. Expected '8410801891219727031, ', Actual '15637648662558474533'

Hello everyone, hope you are all doing well.

Please assist with this. I'm not sure what to do. I have Jak & Daxter 1 working perfectly and i went through the exact same process with Jak 2 but keep getting this error. Anyway to solve it? I'm using the PAL version of the game.

### How To Reproduce

I'm not sure exactly. I copied all the files off the CD. Created an ISO like i did with the original Jak game and i get this error.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

Should Install normally

### Environment Information

Using Windows 11

### Game Version

PAL

### Have you set the game to something other than `60fps`?

No

**Comment by ManDude** [comment]
What PAL version in particular? What region (of Europe or Australia)? Is it a Platinum disc or normal disc?

**Comment by Matty2024** [comment]
> What PAL version in particular? What region (of Europe or Australia)? Is it a Platinum disc or normal disc?

Thank you very much for the reply. Here is as much detail as I can find on the DVD cover.
Also, here is a link to a [Amazon EXAMPLE](https://www.amazon.de/-/en/9637011/dp/B00009N2FV) of what the disk looks like.

It's not the Platinum version, just a normal disk. Its from the Europe Region as their is a British Flag on the bottom left corner.
On the spine of the cover it has "SCES 51608"

Hope this helps. Please ask anything and i will try my best to assist.

**Comment by ManDude** [comment]
Can you contact me on Discord? Username is `dassb` (ID 126398522361643008)

**Comment by Matty2024** [comment]
> Can you contact me on Discord? Username is `dassb` (ID 126398522361643008)

I can try, I don't use Discord very often though. However, if its going to be helpful in making the game functional then we can certainly try that.
