### ISSUE TITLE
Missing Grind Rails - Eco Well Mission 

### ISSUE THREAD

**Issue by CleverlyStoopid** [open-goal/jak-project#3152]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

This bug occurs during the mission where you use the jet board to plant bombs into six eco wells under a two minute time limit. 

I've found that one well is un-reachable due to a large gap missing grind rails with only the pipe connectors left floating in the air, almost like the rails themselves are invisible. This leaves the mission to be virtually unbeatable. 

### How To Reproduce

This bug seems to occur without player input. 

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

The described gap should be bridge with grinding rails, allowing the player to cross to the other side. 

### Environment Information

[CPU] 
11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz   2.30 GHz

[GPU] 
NVIDIA GeForce RTX 3070 Laptop GPU

[OS Version] 
Windows 11 Home

[OpenGOAL Version]
v2.3.2 for Windows

### Game Version

PAL

### Have you set the game to something other than `60fps`?

No

**Comment by Zedb0T** [comment]
Not missing, they are not supposed to be there until later in the game, but OG doesnt hide them 100% perfectly

**Comment by CleverlyStoopid** [comment]
I just double checked and realised that you're absolutely right. Sorry for
the inconvenience, I just remembered this part of the game slightly
different.

Thank you for responding nonetheless.

**Comment by Kingslayer411** [comment]
Rails are still missing even after update

**Comment by ManDude** [comment]
They are meant to be missing, just as the *two* comments right above specified.
