### ISSUE TITLE
error while loading shared libraries: libssl.so.1.1

### ISSUE THREAD

**Issue by DankeBrutus** [open-goal/jak-project#3154]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

For a long time now I have used the terminal to extract and build jak 1 without any issues. Now when building jak 1 and 2 there is an issue with openssl.

- I run ./extractor jak2.iso
- the program extracts the files and builds the game
- the game can be run from the gk executable

With this newest release of version 0.1.44 on both my Fedora desktop and Steam Deck, both platforms which I have built the game and ran it successfully before with the above process, now I am getting an error upon the completion of the build

`Successfully built all 1305 targets in 13.350s
/home/USER/Games/Jak-PC-Port/OpenGOAL/data/../gk: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

I can confirm that the OpenGOAL launcher works with jak 2 and the previous version 0.1.42 CLI works with jak 1.

### How To Reproduce

1. Open terminal in directory containing OpenGOAL files
2. run ./extractor jak2.iso

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

1. run ./extractor jak2.iso
2. assets are extracted and game is built
3. game runs automatically

### Environment Information

Fedora Desktop:
Ryzen 5 3500
RX6600
32GB 3200mhz DDR4
games on NVME drive

Steam Deck

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by xTVaser** [comment]
The latest release has this issue, the binaries were not fully statically built.  The next release will hopefully fix it.

**Comment by xTVaser** [comment]
Resolved in https://github.com/open-goal/jak-project/pull/3162 will be included in the next release
