### ISSUE TITLE
v0.2.0 claims the tooling version doesn't support the game

### ISSUE THREAD

**Issue by Melechtna** [open-goal/jak-project#3156]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

The title says it all, even though the change logs tell a different story. Jak and Daxter works just fine

### How To Reproduce

update tooling from 0.1.44 to 0.2.0

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

It'd work given the update seems to specifically be for Jak2

### Environment Information

I'm using NixOS, has some error when trying to export the support package.

```
[22:36:04][opengoal_launcher][ERROR] panic occurred: PanicInfo { payload: Any { .. }, message: Some(called `Option::unwrap()` on a `None` value), location: Location { file: "/home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/wgpu-hal-0.17.2/src/gles/egl.rs", line: 813, col: 77 }, can_unwind: true }
   0: <unknown>
   1: <unknown>
   2: <unknown>
   3: <unknown>
   4: <unknown>
   5: <unknown>
   6: <unknown>
   7: <unknown>
   8: <unknown>
   9: <unknown>
  10: <unknown>
  11: <unknown>
  12: <unknown>
  13: <unknown>
  14: <unknown>
  15: <unknown>
  16: <unknown>
  17: <unknown>
  18: <unknown>
  19: <unknown>
  20: <unknown>
  21: <unknown>
  22: <unknown>
  23: <unknown>
  24: <unknown>
  25: <unknown>
  26: <unknown>
  27: <unknown>
  28: start_thread
  29: __GI___clone3
  ```

### Game Version

NTSC Greatest Hits version (red label)

### Have you set the game to something other than `60fps`?

No

**Comment by xTVaser** [comment]
This is a launcher issue, a release with a fix is currently in-flight
