### ISSUE TITLE
Shotgun Sound isn't playing in Firing Range Mission

### ISSUE THREAD

**Issue by AcerolaOrionHub** [open-goal/jak-project#3158]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

The Shotgun firing sound disappears after a few shots and sometimes only comes back after 5 or 6 other sounds. Sometimes earlier, sometimes not at all. All other Sounds continue to play as normal.

### How To Reproduce

Happened every time.

### Does this problem occur on original hardware or PCSX2?

Didn't check

### Expected Behavior

The Sound shouldn't be missing.

### Environment Information

Launcher: 2.3.3
Tooling 0.1.44

Ryzen 5 5600X
RTX 2080
Win 11

### Game Version

PAL

### Have you set the game to something other than `60fps`?

No

**Comment by TheTechnician27** [comment]
Can confirm that this problem happens to me as well (NTSC-U) and that it does not happen on PCSX2 or original hardware. The shooting sound played for a while but then cut out for a while before coming back near the end of the shooting range. It seems plausible to me that this isn't exclusive to the shooting range but may instead happen if the gun is fired too many times (you do fire it a lot there in rapid succession). On the other hand, it could be some unique interplay between the sound effects present in the firing range (the mechanical sounds of the targets moving, the points lost sound when you hit a civilian, the golden target noise, and the target being destroyed noise).

I'd have to test some more when I have time to possibly narrow down the issue.

**Comment by ManDude** [comment]
[Very, very, very known issue.](https://opengoal.dev/blog/progress-report-oct-2023/#jak-2-beta-release)

**Comment by AcerolaOrionHub** [comment]
> [Very, very, very known issue.](https://opengoal.dev/blog/progress-report-oct-2023/#jak-2-beta-release)

Oh thank you, I‘ve seem to overlook that.
