### ISSUE TITLE
Debug prints during regular gameplay

### ISSUE THREAD

**Issue by EdnessP** [open-goal/jak-project#3163]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

During the Jetboard challenge mission, there are some debug prints visible on the screen that shouldn't be there.  Seems related to #3150?

![attels](https://github.com/open-goal/jak-project/assets/55930127/ff014189-f575-4f99-8131-7cf2e901f8da)

### How To Reproduce

Start the Jetboard challenge.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

Debug info shouldn't be visible during regular gameplay.

### Environment Information

Intel Core i5-8300H, NVIDIA GeForce GTX 1060, Windows 10, OpenGOAL Launcher v2.3.6, Tooling v0.2.0

### Game Version

PAL

### Have you set the game to something other than `60fps`?

No

**Comment by ManDude** [comment]
It's not a debug print.

**Comment by EdnessP** [comment]
Well then what is it?  It certainly isn't visible there on PS2 and PS3.  Seems like leftover testing prints to me.

![attels](https://github.com/open-goal/jak-project/assets/55930127/b7c7b6d9-d029-4f3b-8612-bc08251f40ea)

**Comment by ManDude** [comment]
They're a new thing we added.
