### ISSUE TITLE
Texture extraction

### ISSUE THREAD

**Issue by Melechtna** [open-goal/jak-project#3164]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

I'm not sure if this is actually a bug, or if things are unfinished, but Jak2 doesn't dump its textures, just its folder structure. I can however go through and manually stitch together which texture is which using debug mode and looking through the entity renderer. So long as I name the file correctly, redoing the decompile loads in the replaced textures without issue, but this is tedious, and the pack I'm converting from PCSX2 to OpenGOAL has some formatting problems that are difficult to solve without a direct texture to compare to, I.E. some textures need to be stitched back together.

Some of the textures in the render list are listed as "place holder" so my guess is this is incomplete, but the reports here don't give me a solid yes or no.

### How To Reproduce

Decompile Jak2, look in the texture folder, find nothing but folders.

### Does this problem occur on original hardware or PCSX2?

Not needed, bug is obvious

### Expected Behavior

The textures would populate

### Environment Information

NixOS, again, can't make a support package because "reasons"

### Game Version

NTSC Greatest Hits version (red label)

### Have you set the game to something other than `60fps`?

No

**Comment by ManDude** [comment]
You need to enable the `save_texture_pngs` parameter in `jak2_config.jsonc`.
