### ISSUE TITLE
Rails are missing in the eco well mission 

### ISSUE THREAD

**Issue by Kingslayer411** [open-goal/jak-project#3166]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Bug prevents you from completing the mission at all rails were present in the original game the bug soft locks you from progressing further in the game 

### How To Reproduce

The bug is produced once you start the mission 

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

When you get to the final eco well you need to grind with the jet board to get to it and the rails do not spawn in at all 

### Environment Information

CPU AMD Ryzen 7 7700x
GPU Nvidia RTX 3070ti 
OS Windows 11
OpenGOAL v2.3.6

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by Hat-Kid** [comment]
The rails are meant to be invisible during that mission and are also invisible on PS2. They only appear during the destroy eggs mission where you drop the crate onto the Metal Head eggs. You do not need those rails to complete the eco wells mission.

OpenGOAL just doesn't properly hide them at the moment.
