### ISSUE TITLE
Mech Suit Audio Cutout in Drill mission

### ISSUE THREAD

**Issue by Veelox-Incident** [open-goal/jak-project#3169]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

During the Mech Suit mission towards the end of the game where you destroy the drilling platform, there is an audio cutout where the suit, metalheads, and lasers stop their noises.

### How To Reproduce

Play the mission and the glitch happens towards the end.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

Audio should remain as it is in the rest of the level.

### Environment Information

[opengoal-support-package.zip](https://github.com/open-goal/jak-project/files/13262671/opengoal-support-package.zip)

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

Yes

**Comment by ManDude** [comment]
For the sake of not cluttering the issues page with 100 repeated sounds cutting out issues, you do not need to report more of these (as per the 'known issues' section of the latest october blog post)
