### ISSUE TITLE
Jak2 trying to open Jak1

### ISSUE THREAD

**Issue by DankeBrutus** [open-goal/jak-project#3188]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

When decompiling jak2 with `./extractor jak2.iso` the program attempts to open a file in a directory that does not exist.

jak2/data/out/jak1/fr3/GAME.fr3

If I copy the jak1 folder in `/data/out` in my jak1 directory it will open jak1 when running `./gk` in my jak2 directory. The decompiler does recognize that jak2.iso is a jak2 disc with serial SCUS-97265. 
If I rename the jak2 folder in `/data/out/` to jak1 the jak2 data folder, obviously, cannot be found.

<img width="798" alt="Screenshot 2023-11-11 at 13 14 47" src="https://github.com/open-goal/jak-project/assets/77204422/908c851b-6e07-4b3a-a489-ddc60f2b5839">

This same ISO does work with the OpenGOAL launcher.

### How To Reproduce

1. open terminal in directory with fresh opengoal v.2.2 files
2. run `./extractor jak2.iso`

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

Once jak2 is extracted and compiled I would expect jak2 to start

### Environment Information

Steam Deck Q2

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by xTVaser** [comment]
This is expected, by default `jak1` is assumed.  If you are going to manually run the extractor yourself, you have to pass in the `--game jak2` argument.

The same goes for running `gk` yourself.

Run `./extractor --help` for information

https://github.com/open-goal/jak-project/blob/288624b90f55443a24efed68a45a208f29831cec/decompiler/extractor/main.cpp#L272

**Comment by aleccool213** [comment]
@xTVaser Please considering adding these argument options to the installation guide. I had trouble until I stumbled here.
