### ISSUE TITLE
Blow Up Strip Mine Eco Wells Grind Pipes Missing

### ISSUE THREAD

**Issue by TristanJofish** [open-goal/jak-project#3189]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

The pipes to grind on to get to the Eco Wells are missing. Unable to grind on where they should be. The joints of the pipes are still present. No collision
![Screenshot 2023-11-11 120019](https://github.com/open-goal/jak-project/assets/150549583/0c728a73-777e-463e-9401-6e26e3180046)

### How To Reproduce

Unknown

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

Supposed to be able to see and grind on pipes

### Environment Information

[opengoal-support-package.zip](https://github.com/open-goal/jak-project/files/13326289/opengoal-support-package.zip)

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by dallmeyer** [comment]
https://github.com/open-goal/jak-project/issues/3166
https://github.com/open-goal/jak-project/issues/3152
