### ISSUE TITLE
TM symbol has weird pink artifacts

### ISSUE THREAD

**Issue by thetntm** [open-goal/jak-project#3192]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak1+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

On the title screen, the "TM" icon appears to have pink artifacts around it, seen here:
![Screenshot (33)](https://github.com/open-goal/jak-project/assets/12042483/6c678feb-a225-4e33-b23d-f2d70378f0b7)

### How To Reproduce

Launch the game.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

The TM icon should not have pink artifacts around it.

### Environment Information

[opengoal-support-package.zip](https://github.com/open-goal/jak-project/files/13326509/opengoal-support-package.zip)

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by thetntm** [comment]
I know this is a VERY minor bug compared to some of the other bugs y'all are dealing with, so don't worry about getting this one fixed. just wanted to point it out because I'm not sure you know about it.

**Comment by Hat-Kid** [comment]
This is not an OpenGOAL bug, this also happens in the original game.

**Comment by thetntm** [comment]
> This is not an OpenGOAL bug, this also happens in the original game.

https://youtu.be/k9PTTaf9faM?si=rUCVuGtjz-pfiZHI

Is it a version issue? I don’t see the same artifacts in this capture of the ps2 title screen. I no longer have a working ps2 so I can’t check for myself, but I also know the ps4 version doesn’t have this issue either.

**Comment by ManDude** [comment]
You don't see them because the game has a native resolution of 512x224. Open the game in an emulator or rip the texture and you can see it.
