### ISSUE TITLE
Subtitles are always in english

### ISSUE THREAD

**Issue by Shamamo** [open-goal/jak-project#3198]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

While the game language setting works, the subtitles setting does not: subtitles are always english no matter what language I choose. It seems to happen only in the world, not in cutscenes.
![20231112203813_1](https://github.com/open-goal/jak-project/assets/29727639/d70e7103-c5d7-4d47-9bb2-b2e0785aa51e)
![20231112203822_1](https://github.com/open-goal/jak-project/assets/29727639/14748bca-bfbb-4d38-bd13-b1fb08d39fd2)

### How To Reproduce

- Put any language in "subtitle language"
- Wait for a subtitle to appear

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

When I select a subtitle language, it should be in the language selected

### Environment Information

Steam deck, steam OS 3.4.11. Latest openGOAL as of the 12/11/2023

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by xTVaser** [comment]
Expected:
- these new subtitles are not yet fully transcribed into english
- the ones that are have not been translated yet.

**Comment by Shamamo** [comment]
Ok great, thanks for the quick answer :)

**Comment by RoyalForgotten** [comment]
Only these one work for me when i translated to french : DSbop002 - DSbop004 - DSbop010 - DSbop011 - DSbop016 - DSbop017

**Comment by xTVaser** [comment]
See the above comment

**Comment by RoyalForgotten** [comment]
Indeed that was the reason, all translations work now, thanks
![image](https://github.com/open-goal/jak-project/assets/150559120/918f5b6e-6730-45d5-84f3-1bd3b38c2a6b)
