### ISSUE TITLE
Glub no death sound 

### ISSUE THREAD

**Issue by DivinusPrime** [open-goal/jak-project#3204]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Walking dead town like usual. Hit the glub but it did not have its death sound. 

### How To Reproduce

https://github.com/open-goal/jak-project/assets/20008541/3de6ddb2-bfc1-47ac-ad5f-ea5a6a04ff17

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

When I kill it, it's supposed to scream its death sound. This is not the case shown here. 

### Environment Information

core i9 11900k 
rtx 3080 12GB
Windows 11 Pro
openGoalLaucnher v2.4.0

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by ManDude** [comment]
Original game thing.

**Comment by ManDude** [comment]
Nevermind.

**Comment by Nick0778** [comment]
[https://youtu.be/NVUXXvK8M-g?si=d02epoU3Aixg1TwA](url)
Well,  I think that they should play this sound when they die... check: 3:06 in this video.

**Comment by Nick0778** [comment]
Also, I noticed that the same happens with most of the enemies of Jak 2, they don't play their death sounds.
