### ISSUE TITLE
speedrunner mode/restart feature bugs

### ISSUE THREAD

**Issue by nameonascreen** [open-goal/jak-project#3209]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

the restart feature can cause issues if restarting at specific moments in the game.

### How To Reproduce

by restarting during a black screen (hitting a cutscene that bugs out and doesn't play immediately) bugs can occur. the most noticeable being that the escape exit doors won’t open.

by restarting with the “press x to jump” text on screen (possibly ANY interact text on screen) the text will bug out and stay on screen. this makes zoomers inaccessible even after the protect kid mission because the text stays on screen

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

restart the game properly as if starting a new game from the main menu.

### Environment Information

latest launcher and game release as of post.

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by xTVaser** [comment]
> by restarting with the “press x to jump” text on screen (possibly ANY interact text on screen) the text will bug out and stay on screen. this makes zoomers inaccessible even after the protect kid mission because the text stays on screen

can't reproduce this, but attempting to open the normal debug menu during this results in the game being in a hung state interestingly. It doesn't persist the text, you are just stuck in menu mode without the menu being visible (so you can't exist it either)
