### ISSUE TITLE
Hero mode is inaccessible 

### ISSUE THREAD

**Issue by Raganoxer** [open-goal/jak-project#3212]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Upon collecting over 200 orbs AND beating the game's final boss, hero mode should be available in the secrets page of the main menu. It strangely doesn't show up.

![Image A](https://github.com/open-goal/jak-project/assets/127743334/73c8c080-257a-4e47-91f3-430d55d6d277)
![Image B](https://github.com/open-goal/jak-project/assets/127743334/ddd31e6c-01e0-49c2-a17a-39a1990376f6)

### How To Reproduce

Just collect over 200 orbs and defeat the final boss. 

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

When I collect over 200 orbs, there should be a hero mode option in the secrets page.

### Environment Information

![Image C](https://github.com/open-goal/jak-project/assets/127743334/5cc7ed02-c322-4795-ab3d-3b77782c9b9d)

### Game Version

NTSC Greatest Hits version (red label)

### Have you set the game to something other than `60fps`?

Yes

**Comment by Zedb0T** [comment]
upload support package

**Comment by ManDude** [comment]
Can't reproduce.

**Comment by Raganoxer** [comment]
> upload support package

How do I do that? I apologize I'm very new with Opengoal

**Comment by Raganoxer** [comment]
> upload support package

Here it is.
[opengoal-support-package.zip](https://github.com/open-goal/jak-project/files/13407943/opengoal-support-package.zip)

**Comment by Matty2024** [comment]
Hey Raganoxer, 

I'm currently playing Hero Mode in Jak 2. Works perfectly for me.

> > upload support package
> 
> Here it is. [opengoal-support-package.zip](https://github.com/open-goal/jak-project/files/13407943/opengoal-support-package.zip)

Hey Ragnaoxer,

I'm currently playing Hero Mode in Jak 2. So the functionality is definitely accessible and working.

**Comment by Raganoxer** [comment]
> Hey Raganoxer,
> 
> I'm currently playing Hero Mode in Jak 2. Works perfectly for me.
> 
> > > upload support package
> > 
> > 
> > Here it is. [opengoal-support-package.zip](https://github.com/open-goal/jak-project/files/13407943/opengoal-support-package.zip)
> 
> Hey Ragnaoxer,
> 
> I'm currently playing Hero Mode in Jak 2. So the functionality is definitely accessible and working.

Any idea why I can't access it?
