### ISSUE TITLE
The game lags after I plug my controller in.

### ISSUE THREAD

**Issue by XaggyGaming** [open-goal/jak-project#3220]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak1+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

My game is lagging everytime I punch a wall, break a box or pick up a blue/yellow eco.
This happenes only when I plug my controller in. I have Gembird JPD-WDV-01.
[2023-11-24.log](https://github.com/open-goal/jak-project/files/13456696/2023-11-24.log)

### How To Reproduce

I connect my controler to the computer. Then I turn on the game. I start New Game or a Save File. I do all of the actions I mentioned above. The game lags for a second every time I do some of those actions. The game lags the whole duration I have a blue eco which is the worst.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

When I plug my controller in, the game should not lag at all during any action.

### Environment Information

[opengoal-support-package.zip](https://github.com/open-goal/jak-project/files/13456810/opengoal-support-package.zip)
CPU: Intel Core i5 @ 2.50GHz Comet Lake 14nm Technology
GPU: NVIDIA GeForce GTX 1650
OS Version: Windows 11 Home 64-bit
OpenGOAL Version: v2.4.0
Tooling: v0.2.2

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by ManDude** [comment]
Your controller is likely connecting/disconnecting whenever it vibrates.

**Comment by Xaggy** [comment]
I reinstalled the controller software and now it works. I'm sorry for creating an unnecessary post. I should've thought of that solution immediately.
