### ISSUE TITLE
Metal Head Nest doesn't load

### ISSUE THREAD

**Issue by AnimusCase** [open-goal/jak-project#3225]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

I can't play the last part of the game, the Metal Head Nest is missing

### How To Reproduce

https://youtu.be/kzMzz9aik3Q

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

x

### Environment Information

This section is really missing, there is emptyness, when I'm trying get in there, I fall in.

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by ManDude** [comment]
Were you hovering all over the place?
