### ISSUE TITLE
Freezing cut-scenes

### ISSUE THREAD

**Issue by CR4Y-F1SH** [open-goal/jak-project#3236]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Additional cutscene freezes besides torn and strip mine, happening in almost every single one. I play on high end PC. Can skip them. Will not happen in 2nd instance of playing cut-scene.

### How To Reproduce

Play through any cutscene.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

Cutscenes should play though

### Environment Information

n/a

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by ManDude** [comment]
Can you show us a video? And attach your support package please.

**Comment by CR4Y-F1SH** [comment]
Heya,

Its hard to know when it will do it is the only issue with getting a video. I'll try to get the support package though.

J



Sent from my Galaxy



-------- Original message --------
From: ManDude ***@***.***>
Date: 01/12/2023 22:06 (GMT+00:00)
To: open-goal/jak-project ***@***.***>
Cc: CR4Y-F1SH ***@***.***>, Author ***@***.***>
Subject: Re: [open-goal/jak-project] Freezing cut-scenes (Issue #3236)


Can you show us a video? And attach your support package please.

**Comment by xTVaser** [comment]
Not enough information to go off of, potentially related to https://github.com/open-goal/jak-project/issues/3405 which is a known issue in the original game as well -- but hard to tell given the wording.

Feel free to re-open if the problem is different and you have more information to share.
