### ISSUE TITLE
Investigate and fix new unicode error if applicable

### ISSUE THREAD

**Issue by xTVaser** [open-goal/jak-project#3244]
Someone apparently had a problem, then fixed it by installing it somewhere else (without the unicode symbols potentially).
- make sure the problem wasn't because of the unicode symbols
- if it was, fix the regression

![image](https://github.com/open-goal/jak-project/assets/13153231/2cfc13ac-59b8-40c6-9365-a89ae66934e1)

**Comment by ManDude** [comment]
Also happened when someone had a directory with `š` in it (but the reply is a bit confusing as to how they fixed the issue)
![image](https://github.com/open-goal/jak-project/assets/7569514/94c6201b-cf44-483e-a5f2-7d1672ab6192)
