### ISSUE TITLE
Fast swimming can make jak swag out

### ISSUE THREAD

**Issue by Zedb0T** [open-goal/jak-project#3249]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

https://clips.twitch.tv/SplendidAbstemiousCucumberShazBotstix-5soxI6blY6h3obCn

### How To Reproduce

I guess fast swimming? havent tried it myself yet, but will now. They should have had speedrunner mode on and been 60 fps

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

a

### Environment Information

a

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by Zedb0T** [comment]
https://clips.twitch.tv/SplendidAbstemiousCucumberShazBotstix-5soxI6blY6h3obCn

**Comment by LuminarLight** [comment]
I experienced this issue in original game, but it is very rare and I think i never got more than one rotation.
