### ISSUE TITLE
`skill` shadows are wrong

### ISSUE THREAD

**Issue by dallmeyer** [open-goal/jak-project#3269]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Shadows for precursor orbs seems really off, doesn't match PS2

https://github.com/open-goal/jak-project/assets/2515356/7e20ade1-f2c6-4a4a-aea7-a4e9c7694d6b

https://github.com/open-goal/jak-project/assets/2515356/11623c74-6482-4d56-bb51-a6df1ddcb844

### How To Reproduce

See videos

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

See PS2 video

### Environment Information

Windows

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by ManDude** [comment]
Shadow is placed at 0,0,0 with a broken shadow control.
![imagem](https://github.com/open-goal/jak-project/assets/7569514/b9ad0de1-338d-4afd-93c3-d94186b84120)
