### ISSUE TITLE
`onintent` spider sprites render on top of transparent textures

### ISSUE THREAD

**Issue by dallmeyer** [open-goal/jak-project#3281]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

![image](https://github.com/open-goal/jak-project/assets/2515356/89b74f91-0072-463b-8fee-424169ad2925)

### How To Reproduce

use debug in onintent

### Does this problem occur on original hardware or PCSX2?

Didn't check (DOES occur on PCSX2)

### Expected Behavior

spider sprites should be partially obscured by transparent textures

### Environment Information

windows

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by ManDude** [comment]
This is normal. `tfrag-water` doesn't write to the depth buffer.
