### ISSUE TITLE
Menu opening almost every time I press jump

### ISSUE THREAD

**Issue by Pizzamaker60** [open-goal/jak-project#3282]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

When I'm playing the game with an Xbox One controller almost every time I press the jump button the menu opens up like hitting the start button. This also happens with JAK 1

### How To Reproduce

just play the game with a Xbox one controller and try jumping the menu will open often

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

if you press jump with an Xbox One controller the menu opens anytime you press the A button

### Environment Information

OpenGoal Version 2.4.0 Tooling version is 0.2.4

![Screenshot 2023-12-31 162433](https://github.com/open-goal/jak-project/assets/155218626/0f2a6bf9-9447-416c-b186-a39323e6bfd8)

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by ManDude** [comment]
Disable Steam Input, or exit Steam completely.
