### ISSUE TITLE
Lightly pressing the R2 button while in a car makes the sound for changing elevations but does not move the car. 

### ISSUE THREAD

**Issue by callumhalo** [open-goal/jak-project#3289]
### Acknowledgements

- [x] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Lightly pressing the R2 button while in a car makes the sound for changing elevations but does not move the car. 

Easily recreateable in any car, though I have not tested other fps it happens at 240fps with a dualshock 4 controller.

### How To Reproduce

Lightly pressing the R2 button while in a car

### Does this problem occur on original hardware or PCSX2?

Didn't check

### Expected Behavior

Either no noise unless the car moves or the little movement of R2 should change elevation. 

It probably happens because the triggers have values oh how far they have been pressed. (they are not just linear switches)

### Environment Information

CPU: 10700k
GPU: RTX 3080
Windows 10
Version 2.4.0
Tools 0.2.4

(not sure what version eu aussie version)

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

Yes

**Comment by xTVaser** [comment]
I can "reproduce" this at both high and low framerates.  I don't think it has anything to do with that:
1. Yes triggers are analog values however in the current implementation any value above `0` (the switch is considered not neutral) is a "press".  So this is not relevant.
2. You can press R2 to switch hover zones as fast as you want in the original game
3. Lightly pressing puts you in situation where it's very easy to quickly change between not pressing the button, and pressing the button
4. Right now the sounds for the game are not really accurate -- the hover changing sound is not playing properly when rapidly switching (some are skipped)

As far as I can tell, with all of these things taken into account it just seems like it's working as intended.  You are just rapidly switching zones and then switching back so the car does not move, and only 1of the 2 (or more) sounds is being played, so it seems like something was ignored.  Looking at the code this makes sense as it's pretty much impossible to skip the hover zone switch, if the sound plays -- it will run the code to switch zones https://github.com/open-goal/jak-project/blob/4ca84f9a971fb07706d7460ab3afe04a76ba752f/goal_src/jak2/levels/city/traffic/vehicle/vehicle-util.gc#L1079-L1080
