### ISSUE TITLE
Jak 2 Peacemaker incorrect ammo

### ISSUE THREAD

**Issue by callumhalo** [open-goal/jak-project#3291]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Peacekeeper sometimes shows 0 ammo but actually has 1 ammo. You can shoot with 0 ammo sometimes.

### How To Reproduce

Not sure specifically how to reproduce it, I just noticed in my playthrough that more than one time I had 0 ammo and I just pressed the fire button without thinking and shot one more blast. (perhaps related to having to charge?)

Also harder to reproduce because I didn't come across much ammo when I got it.

I'm also unsure if the ammo collected corresponds with the actual ammo or if the counter itself is broken.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

When ammo shows 0 in the HUD, the ammo should be 0

### Environment Information

CPU: 10700k
GPU: 3080
OS version: Windows 10
OG version: 2.4.0
Tool version: 0.2.4

Game version, the EU Aussie version. (renegade)

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by ManDude** [comment]
Are you sure you're not just getting confused? Ammo is deducted when you begin charging the Peacemaker, not when you shoot it.

**Comment by callumhalo** [comment]
> Are you sure you're not just getting confused? Ammo is deducted when you begin charging the Peacemaker, not when you shoot it.

I could be wrong. 

But my memory of it is the HUD showing 0 and then pressing the fire button and it still charging and shooting another shot.
Like I remember having 2 ammo, shooting 2 and then being able to shoot another.

But yeah, I only noticed it vaguely when I was playing so it is possible that I am mistaken.

**Comment by ManDude** [comment]
Please verify.

**Comment by callumhalo** [comment]
Will do, I'll be busy a few days but ill give it a look soon :)

**Comment by xTVaser** [comment]
Feel free to re-open if you can reproduce it, ideally with a recording.
