### ISSUE TITLE
"Music Player" under "Secrets" doesn't work properly (it always play the first track of the list)

### ISSUE THREAD

**Issue by SixelAlexiS90** [open-goal/jak-project#3293]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak1+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

When you go on "Music Player" under "Secrets", once you choose a level it will always play the first track in the list no matter what track you select.

### How To Reproduce

Go to:

1. "Secrets"
2. "Music Player"
3. Select a level
4. Play any track you want
5. At that point it will always play the first track of the list, even if you change it after that
e.g. you will always hear "Sandover Village" track under "Sandover Village" level and "Sentinel Beach" track under "Sentinel Beach" level.

Here a video of the issue:
https://www.youtube.com/watch?v=4an0j6EcnDU

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

The appropriate music track should be played when selected.

### Environment Information

CPU: i7 4770K
GPU: RTX 2060
OS: Windows 10 Pro - 22H2 - 19045.3803
OpenGOAL: Launcher v2.4.0 - Tooling v0.2.4

### Game Version

PAL

### Have you set the game to something other than `60fps`?

No

**Comment by ManDude** [comment]
Uh... I think you're just a bit confused. Read what it says at the top carefully, "select flavor." It changes the flavor of the track to what you selected. After you selected "grotto" for example, it played the grotto flavor version of Sentinel Beach.

**Comment by SixelAlexiS90** [comment]
> Uh... I think you're just a bit confused. Read what it says at the top carefully, "select flavor." It changes the flavor of the track to what you selected. After you selected "grotto" for example, it played the grotto flavor version of Sentinel Beach.

What is supposed to change? They all sounds to same to me, I'm indeed confused :'D

**Comment by ManDude** [comment]
https://www.youtube.com/watch?v=G8lNKbCt4h8&list=PLF296898380E24516&index=5&pp=iAQB8AUB
