### ISSUE TITLE
Linux: Water rendering incorrectly

### ISSUE THREAD

**Issue by r2rX** [open-goal/jak-project#3298]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak1+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Hey all. As the title suggests, the water/ocean in-game is rendering incorrectly (rendered in blocks). Additionally, the same issue affects Jak II (SCUS-97265) and adjusting the framerate higher than 60fps doesn't make a difference.

![jak_water](https://github.com/open-goal/jak-project/assets/18622885/25388c6f-06d2-48ac-8d5e-b6dfa33a11a9)

### How To Reproduce

Run Fedora (or any other Linux distro) with an AMD GPU (ideally RDNA2) running Mesa 23.3.2 Stable and/or 24.0.0-git and simply run the game. The issue should be apparent on the menu screen.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

The water should render correctly.

![jak_c](https://github.com/open-goal/jak-project/assets/18622885/96c22196-6e52-4234-80f1-b101963347d6)

### Environment Information

CPU: AMD Ryzen 9 5900HX
GPU: AMD Radeon RX 6800M
GPU Driver: Mesa 23.3.2 Stable & 24.0.0-git
OS: Fedora 39 KDE (Wayland)
OpenGOAL: 0.2.4

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

Yes

**Comment by Hat-Kid** [comment]
A few weeks ago, somebody else reported a similar issue on our Discord with water rendering being broken. They also had a mobile AMD card (RX 5600M) and reported that downgrading Mesa from `23.3.1` to `23.2.1` fixed it.

If doing this also fixes it for you, then this must be something in the Mesa update breaking our ocean renderer implementation somehow specifically on (mobile?) AMD cards.

**Comment by r2rX** [comment]
Thanks, @Hat-Kid. Downgrading to Mesa 23.2.1 does indeed correct the issue. Considering that this affects RDNA1 and RDNA2 mobile variants, I'll bring it up with mesa on their git issue tracker and update here. Cheers!

**Comment by r2rX** [comment]
The issue seems to have been reported on the [mesa git tracker](https://gitlab.freedesktop.org/mesa/mesa/-/issues/9807) already and the regression was bisected. It's also occurring on non-mobile GPUs as well.

**Comment by r2rX** [comment]
The issue was resolved with this [merge](https://gitlab.freedesktop.org/mesa/mesa/-/merge_requests/27095). Using any mesa-git from this point, or the next stable release, should work fine now.
