### ISSUE TITLE
Make multiplication/division/mod match the PS2 Hardware

### ISSUE THREAD

**Issue by water111** [open-goal/jak-project#33]
GOAL seems to have 4 operations:
- Signed Multiply (`mult`, 3 operand form)
- Unsigned Multiply (`multu`, 3 operand form)
- Divide (`div` and `mflo`)
- Mod (`div` and `mfhi`)

We should try to match the behavior of the PS2 exactly with our implementation. It would be great to find a test case for PS2 emulators or look at PCSX2's implementation.

Also we should check float to int and int to float.

**Comment by blahpy** [comment]
Does no GOAL operation use `divu`? I've included it below anyway.

Anyway, here is the implementation from https://github.com/PCSX2/pcsx2/blob/master/pcsx2/R5900OpcodeImpl.cpp:

```/*********************************************************
* Register mult/div & Register trap logic                *
* Format:  OP rs, rt                                     *
*********************************************************/

// Signed division "overflows" on (0x80000000 / -1), here (LO = 0x80000000, HI = 0) is returned by MIPS
// in division by zero on MIPS, it appears that:
// LO gets 1 if rs is negative (and the division is signed) and -1 otherwise.
// HI gets the value of rs.

// Result is stored in HI/LO [no arithmetic exceptions]
void DIV()
{
	if (cpuRegs.GPR.r[_Rs_].UL[0] == 0x80000000 && cpuRegs.GPR.r[_Rt_].UL[0] == 0xffffffff)
	{
		cpuRegs.LO.SD[0] = (s32)0x80000000;
		cpuRegs.HI.SD[0] = (s32)0x0;
	}
    else if (cpuRegs.GPR.r[_Rt_].SL[0] != 0)
    {
        cpuRegs.LO.SD[0] = cpuRegs.GPR.r[_Rs_].SL[0] / cpuRegs.GPR.r[_Rt_].SL[0];
        cpuRegs.HI.SD[0] = cpuRegs.GPR.r[_Rs_].SL[0] % cpuRegs.GPR.r[_Rt_].SL[0];
    }
	else
	{
		cpuRegs.LO.SD[0] = (cpuRegs.GPR.r[_Rs_].SL[0] < 0) ? 1 : -1;
		cpuRegs.HI.SD[0] = cpuRegs.GPR.r[_Rs_].SL[0];
	}
}

// Result is stored in HI/LO [no arithmetic exceptions]
void DIVU()
{
	if (cpuRegs.GPR.r[_Rt_].UL[0] != 0)
	{
		// note: DIVU has no sign extension when assigning back to 64 bits
		// note 2: reference material strongly disagrees. (air)
		cpuRegs.LO.SD[0] = (s32)(cpuRegs.GPR.r[_Rs_].UL[0] / cpuRegs.GPR.r[_Rt_].UL[0]);
		cpuRegs.HI.SD[0] = (s32)(cpuRegs.GPR.r[_Rs_].UL[0] % cpuRegs.GPR.r[_Rt_].UL[0]);
	}
	else
	{
		cpuRegs.LO.SD[0] = -1;
		cpuRegs.HI.SD[0] = cpuRegs.GPR.r[_Rs_].SL[0];
	}
}

// Result is written to both HI/LO and to the _Rd_ (Lo only)
void MULT()
{
	s64 res = (s64)cpuRegs.GPR.r[_Rs_].SL[0] * cpuRegs.GPR.r[_Rt_].SL[0];

	// Sign-extend into 64 bits:
	cpuRegs.LO.SD[0] = (s32)(res & 0xffffffff);
	cpuRegs.HI.SD[0] = (s32)(res >> 32);

	if( _Rd_ ) cpuRegs.GPR.r[_Rd_].UD[0] = cpuRegs.LO.UD[0];
}

// Result is written to both HI/LO and to the _Rd_ (Lo only)
void MULTU()
{
	u64 res = (u64)cpuRegs.GPR.r[_Rs_].UL[0] * cpuRegs.GPR.r[_Rt_].UL[0];

	// Note: sign-extend into 64 bits even though it's an unsigned mult.
	cpuRegs.LO.SD[0] = (s32)(res & 0xffffffff);
	cpuRegs.HI.SD[0] = (s32)(res >> 32);

	if( _Rd_ ) cpuRegs.GPR.r[_Rd_].UD[0] = cpuRegs.LO.UD[0];
}
```
```
/*********************************************************
* Move from HI/LO to GPR                                 *
* Format:  OP rd                                         *
*********************************************************/
void MFHI() { if (!_Rd_) return; cpuRegs.GPR.r[_Rd_].UD[0] = cpuRegs.HI.UD[0]; } // Rd = Hi
void MFLO() { if (!_Rd_) return; cpuRegs.GPR.r[_Rd_].UD[0] = cpuRegs.LO.UD[0]; } // Rd = Lo
```

https://github.com/PCSX2/pcsx2/blob/master/pcsx2/x86/ix86-32/iR5900MultDiv.cpp also exists, but I don't know what it is used for.

**Comment by water111** [comment]
Thanks!  The first part you posted is from the EE interpreter, and second is from the EE recompiler.  We can use the PCSX2 implementation to check the results of the compiler.

**Comment by blahpy** [comment]
Apparently, the EE's floating point unit does not follow the IEEE standard which could make it more difficult to get perfect. In fact, it's possible to do floating point operations on the FPU and VU and get **different results**. There are also differences in how overflows are handled. PCSX2's implementation... might be handling it all now?

https://wiki.pcsx2.net/PCSX2_Documentation/Nightmare_on_Floating-Point_Street The author of this article might be able to provide more insight about the issue if you would like me to reach out to them, but I don't really know the right questions to ask.

**Comment by xTVaser** [comment]
Have we solved this by this point? I know there's been a lot of work fixing inconsistencies with division and such.

**Comment by water111** [comment]
sadly no - we don't get divide by zero quite right, and I'd really like to add tests for sign behavior on `mod`/`rem` (I think we got this right though)

**Comment by water111** [comment]
after https://github.com/open-goal/jak-project/pull/1296, I think it is okay to close this issue. There actually was a bug with `mod` on unsigned numbers, though it would only make a difference on unsigned values between `INT32_MAX` and `UINT32_MAX`.

In most cases, we match the PS2 and GOAL exactly. There are a few tricky parts, and tests that confirm we got it right:
- mul/div/mod are 32-bit operations(*) and don't pay attention to the upper 32-bits of the inputs and create 32-bit outputs
- GOAL will recognize mul/div with a constant power of 2, and switch to using 64-bit shifts, making these 64-bit operations
- div and mod are actually different operations for signed/unsigned, even on just the lower 32-bits
- the PS2's CPU is quite weird and sign-extends the unsigned result of mul/div/mod with unsigned inputs

Note that you can get the upper 32-bits of the mul (which depend on signed/unsigned) using the `hi` register. This is only done in a few places and is manually handled.

The PS2 has nonstandard behavior if there's an overflow/divide by zero. In OpenGOAL, it will simply crash in these cases, so it will be obvious when these cases show up.
