### ISSUE TITLE
[Steam Deck] "Create Jak 1 Shortcut" does not work

### ISSUE THREAD

**Issue by RStokes43** [open-goal/jak-project#3303]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak1+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

After walking through the install of Decky as well as the OpenGOAL plugin successfully, I installed Jak 1. That installed without issue.

When Clicking the "Create Jak 1 Shortcut" button, I am told a restart is needed for the changes to take effect. I understand this is expected and click "Restart Now"

After the restart, Jak 1 does not appear in my library anywhere. I have reinstalled the OpenGOAL plugin as well as Decky in its entirety.

This happens on the stable and beta release of SteamOS and the Stable Release of Decky.

### How To Reproduce

Attempt to Create Jak 1 Shortcut in OpenGOAL Decky plugin

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

When I click the "Create Jak 1 Shortcut button and restart, the game should be added to my library"

### Environment Information

Steam Deck (Non-OLED). This happens on Stable and Beta release as of Jan 12 2024. OS Version 3.5.7.
Decky Version 2.10.10

### Game Version

PAL

### Have you set the game to something other than `60fps`?

No

**Comment by RStokes43** [comment]
This is an issue with Steam displaying the gmae and not with OpenGOAL adding it to steam. After attempting to create the shortcut about 20 times, I discovered it appeared in the desktop Steam app about 20 times. I removed them all until only one was left, then noticed it still didn't appear in Handheld mode. I went back to desktop mode, launched Jak 1 so it was in my recently played, closed it, then it appeared in handheld mode as expected

**Comment by dallmeyer** [comment]
iirc if you just reboot after adding it, then it will show up

**Comment by RStokes43** [comment]
> iirc if you just reboot after adding it, then it will show up

This was done as indicated in my original post. I found a solution. It doesn't automatically appear on the front page in handheld mode. You have to launch in Desktop mode from Steam first, or have an "Installed Locally" collection where you can find it in handheld mode.
