### ISSUE TITLE
DGO unpacking and font locating

### ISSUE THREAD

**Issue by efimandreev0** [open-goal/jak-project#3372]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak1+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Hi! I'm translate Jak and Daxter to Korean. I found font into the game, but i don't see it. I translated it on PS2 and PSV, and in the future I can port my translate to your project. I want your help, guys. I need .dgo unpacker\packer and texture editor. Can you help me? You - my last hope. Pls, help me, guys!
I trying to pay programmers, but it can't write an unpacker\packer for those... It only write tool to work with text-files. I really want help, guys...

### How To Reproduce

.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

.

### Environment Information

.

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

Yes

**Comment by ManDude** [comment]
The font is located in `gamefontnew/` if you set the decompiler to extract textures in `jak1_config.jsonc`.

Korean is unlikely to be supported for Jak 1 as the font does not have Hangul glyphs.

Korean is not supported for Jak 2 and 3 beyond what's in the original game because the format is a giant pain in the ass to figure out.

**Comment by efimandreev0** [comment]
I know what it located here. Where is it in the game? And can you give me tools to .dgo unpacking? As I think true, it located in .dgo-files...
