### ISSUE TITLE
Animations not correct

### ISSUE THREAD

**Issue by Chixutheengie** [open-goal/jak-project#3390]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak1+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

![Screenshot_1](https://github.com/open-goal/jak-project/assets/133466247/0f4aabf2-b276-44b4-9047-893db30e4a5f)
![Screenshot_2](https://github.com/open-goal/jak-project/assets/133466247/66a888e0-7ca6-450f-9dcb-d3e6fe1555d0)
![Screenshot_3](https://github.com/open-goal/jak-project/assets/133466247/e3418cb6-44d4-4f24-b397-673359e13c07)
![Screenshot_4](https://github.com/open-goal/jak-project/assets/133466247/5c4cef5a-6125-4db6-a127-35d08f0c5967)
i dont think these are the correct animations for daxter

### How To Reproduce

screenshot 1 no movement
screenshot 2 after running 
screenshot 3 crouching 
screenshot 4 crouch walking

### Does this problem occur on original hardware or PCSX2?

Not needed, bug is obvious

### Expected Behavior

i dont think daxter should be floating

### Environment Information

[opengoal-support-package.zip](https://github.com/open-goal/jak-project/files/14412346/opengoal-support-package.zip)

### Game Version

NTSC Greatest Hits version (red label)

### Have you set the game to something other than `60fps`?

No

**Comment by Zedb0T** [comment]
![image](https://github.com/open-goal/jak-project/assets/89345505/49ef018e-5a1c-4f9f-8e92-8f934c716e8f)
![image](https://github.com/open-goal/jak-project/assets/89345505/164b4d6c-0a4c-47ca-8c8f-b348e5e56112)
![image](https://github.com/open-goal/jak-project/assets/89345505/03791f67-f104-49b3-befa-d97b7dd72ef4)
![image](https://github.com/open-goal/jak-project/assets/89345505/189c68d1-90e7-4761-9778-25f8c4963d27)

All of these animations are consistent with the PS2 version of the game.
