### ISSUE TITLE
Keyboard rebinding labels options incorrectly with multiple monitors

### ISSUE THREAD

**Issue by katjustice97** [open-goal/jak-project#3393]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak1+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

The first _n_ entries of the rebind keys page list the monitor options from the Display settings page instead of the control being rebound after viewing the Display options with non-60FPS set. They still function as expected and rebind the control they should be labeled as; this glitch is visual only.

Controller Binds:
![image](https://github.com/open-goal/jak-project/assets/161988288/20b56cbb-7246-4e62-b573-14a13e7a552d)

Keyboard Binds:
![image](https://github.com/open-goal/jak-project/assets/161988288/3209177d-fb04-4cbc-b8c2-e13ed72c4085)

Mouse Binds:
![image](https://github.com/open-goal/jak-project/assets/161988288/0382328f-869b-4453-8614-71e648652ee7)

Display:
![image](https://github.com/open-goal/jak-project/assets/161988288/b2909c5d-b13b-48f2-8532-2543ff6e3fdc)

### How To Reproduce

View Graphic Options > Display, then navigate to Game Options > Input Options > Reassign Binds > Any

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

The reassign keybinds options should list which control is being changed, not the monitors available at the first viewing of the display options.

### Environment Information

CPU: AMD Ryzen 7 7735HS
GPU: NVIDIA GeForce RTX 4050 Laptop
OS: Windows 11 Home 64x
OpenGOAL: v0.2.7

### Game Version

NTSC Greatest Hits version (red label)

### Have you set the game to something other than `60fps`?

Yes

**Comment by xTVaser** [comment]
Is this problem unique to jak 1, or do you see similar issues on jak 2?

**Comment by katjustice97** [comment]
> Is this problem unique to jak 1, or do you see similar issues on jak 2?

Gimme a bit to dump Jak II and I'll let you know. Also, this only occurs when you view display settings with something other than 60fps set, but once it's triggered, it won't revert even if you change the fps back to 60. You have to restart the game to fix it.

**Comment by katjustice97** [comment]
Happy to report I encountered no such issue in Jak II. I tried everything i could think of to make it happen, but I think since the monitor selection setting doesn't change the submenu screen, whatever caused the issue in TPL isn't relevant here.
