### ISSUE TITLE
Bug graphiques

### ISSUE THREAD

**Issue by AsunaAsano** [open-goal/jak-project#3399]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

La qualité des graphismes ayant été améliorés cela est dommage, de ne pas améliorer aussi la qualité de l'image de la carte en bas à droite, ou de l'affichage en bas à gauche de la tête de Jak et de sa vie. Il y a aussi des bug de son lorsque l'on casses les boîtes ou qu'on tue les monstres, où lors d'utilisation de véhicules. Au niveau des sous-titres cela est dommage qu'il y est des fautes d'orthographe. Pour les yeux de Jak il arrive qu'il est des bug et mouvements étranges. Il peut aussi arriver que le jeu se ferme tout seul. Quelques petits détails encore à améliorer mais cela reste tout de mêmes mon jeux favoris. Signée une grande fan de Jak et Daxter.

### How To Reproduce

La qualité des graphismes ayant été améliorés cela est dommage, de ne pas améliorer aussi la qualité de l'image de la carte en bas à droite, ou de l'affichage en bas à gauche de la tête de Jak et de sa vie. Il y a aussi des bug de son lorsque l'on casses les boîtes ou qu'on tue les monstres, où lors d'utilisation de véhicules. Au niveau des sous-titres cela est dommage qu'il y est des fautes d'orthographe. Pour les yeux de Jak il arrive qu'il est des bug et mouvements étranges. Il peut aussi arriver que le jeu se ferme tout seul. Quelques petits détails encore à améliorer mais cela reste tout de mêmes mon jeux favoris. Signée une grande fan de Jak et Daxter.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

La qualité des graphismes ayant été améliorés cela est dommage, de ne pas améliorer aussi la qualité de l'image de la carte en bas à droite, ou de l'affichage en bas à gauche de la tête de Jak et de sa vie. Il y a aussi des bug de son lorsque l'on casses les boîtes ou qu'on tue les monstres, où lors d'utilisation de véhicules. Au niveau des sous-titres cela est dommage qu'il y est des fautes d'orthographe. Pour les yeux de Jak il arrive qu'il est des bug et mouvements étranges. Il peut aussi arriver que le jeu se ferme tout seul. Quelques petits détails encore à améliorer mais cela reste tout de mêmes mon jeux favoris. Signée une grande fan de Jak et Daxter.

### Environment Information

La qualité des graphismes ayant été améliorés cela est dommage, de ne pas améliorer aussi la qualité de l'image de la carte en bas à droite, ou de l'affichage en bas à gauche de la tête de Jak et de sa vie. Il y a aussi des bug de son lorsque l'on casses les boîtes ou qu'on tue les monstres, où lors d'utilisation de véhicules. Au niveau des sous-titres cela est dommage qu'il y est des fautes d'orthographe. Pour les yeux de Jak il arrive qu'il est des bug et mouvements étranges. Il peut aussi arriver que le jeu se ferme tout seul. Quelques petits détails encore à améliorer mais cela reste tout de mêmes mon jeux favoris. Signée une grande fan de Jak et Daxter.

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by xTVaser** [comment]
My french is horrible so forgive me if I misinterpreted this.  But it seems like you basically said the same thing as you did here https://github.com/open-goal/jak-project/issues/3398 but instead in french, and with the same response copy pasted to each input instead of providing actual details?

- Sounds bugs are well known https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+sound+label%3Ajak2 it is definitely the area that is still lacking the most polish

- Please be more specific about what graphical problems you are experiencing
  - Include screenshots, videos, logs.  Anything to indicate what the problem actually is.  Saying that there are bugs is not actionable or helpful.
  - Feel free to re-open with more information.
