### ISSUE TITLE
Small lines around icons inside the minimap

### ISSUE THREAD

**Issue by guiguiconqueror** [open-goal/jak-project#3402]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Hello,
I know jak 2 is still in beta but have you seen this little bug yet? 

I can see little lines around the icons in the minimap.
I checked on my ps3 version and on youtube videos of the ps2 version.

![Capture d'écran 2024-03-05 204415](https://github.com/open-goal/jak-project/assets/10706216/9e9eae93-20f8-4e7d-ab0b-061b61ab0bd3)
![Capture d'écran 2024-03-05 204503](https://github.com/open-goal/jak-project/assets/10706216/62e0c189-448d-49e5-9456-0a68955bba0b)
![Capture d'écran 2024-03-05 204740](https://github.com/open-goal/jak-project/assets/10706216/65ffaff8-e275-4592-85d4-dc8622d3fa16)

### How To Reproduce

For me nothing to do, just look at the minimap

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

No lines around the icons

### Environment Information

[opengoal-support-package.zip](https://github.com/open-goal/jak-project/files/14500840/opengoal-support-package.zip)

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by guiguiconqueror** [comment]
@xTVaser @ManDude @water111 @Hat-Kid Do you see these little lines too?

**Comment by ManDude** [comment]
Yes, everyone has this issue. We know about it. There is no ETA on a fix right now.

**Comment by NolanHewitt** [comment]
Lines make men cry

**Comment by ManDude** [comment]
Fixed in #3481
