### ISSUE TITLE
Jak 1 & 2 don't respond to DualShock3 controller

### ISSUE THREAD

**Issue by yodaxtah** [open-goal/jak-project#3415]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak1+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

I have always played with DualShock4 and it worked perfectly. Friends of mine claimed their 2 (old) DualShock3 controllers didn't work. I thus tried two of mine at home and they didn't respond. I'm very confident the ones at my home work. This means four DS3 controllers didn't work, all through cable connection, as that works for DS4. I did check the settings, and the game is able to detect the controller as shown in the screenshot when navigating to `Options` > `Game settings` > `Input settings` > `Controller options` > `Select controller`. (I am able to navigate there by force enabling keyboard feature! :D) I later tried jak II, and it didn't work either.

![image](https://github.com/open-goal/jak-project/assets/159531413/2186f604-d5b1-47f3-be93-26f22e0868e6)

### How To Reproduce

- Open the launcher
- Click "Play" on jak 1/2
- Plugin a DualShock3 controller
- (Wait for the instruction to hit start to appear)
- Hit start

### Does this problem occur on original hardware or PCSX2?

Not needed, bug is obvious

### Expected Behavior

When I hit start, the menu should open.

### Environment Information

This should be the same support package that I uploaded a month ago [here](https://github.com/open-goal/launcher/issues/436), in between I only updated the tooling and the launcher as I didn't have much time to play. <s>(Fun fact for whoever read that issue, I expected the games to be in my self set directory, but they were stored in AppData, so I accidentally removed those saves by removing all applications! x) It's ok.)</s>

[opengoal-support-package.zip](https://github.com/open-goal/jak-project/files/14547565/opengoal-support-package.zip)

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by xTVaser** [comment]
This means that SDL is successfully detecting the controller however it is seemingly not processing/receiving the inputs from it properly.

Someone with a DS3 on windows will need to debug this / refute this as a widespread problem -- I don't have one to test with.

**Comment by Zedb0T** [comment]
You need to build the project, make sure you select the release preset in visual studio (This assumes windows)

**Comment by yodaxtah** [comment]
Ah, I assume it's because the default is debug. I missed that with `Ctrl Shift B`.

![image](https://github.com/open-goal/jak-project/assets/159531413/931043ba-81af-4bf2-a4f1-dbcff0c7f952)

Apologies, I didn't give any information, but indeed, I'm on Windows 10. I will try again now.

**Comment by yodaxtah** [comment]
Thanks for the feedback so far. I've ran the game through `task boot-game` without problem. As expected DS3 didn't work and DS4 did. Can anyone point me towards the code that is required to use these controllers? As I have no knowledge on it myself, I'm just going to self document here.

Here are all occurrences of "DualShock" in the local jak-project copy. Half of them are third-party and not maintained by this project. I didn't find any bugs related to DualShock3 in [SDL's repo](https://github.com/libsdl-org/SDL/issues?q=dualshock3). Then, goal_src/jak2,3/engine/ps2 can be ignore as well. So basically, I'm guessing libpad.cpp and pad.gc are important here? I'm just not able to make a lot of sense of the code without context of the workings or a debugger.

![image](https://github.com/open-goal/jak-project/assets/159531413/346132dd-c371-40db-96b3-5bb496c792f8)

Any help is welcome! (I will now take a break from this search and come back to it now and then.)

**Comment by ManDude** [comment]
Do the controllers work in other games?

**Comment by yodaxtah** [comment]
Well, as described in the issue, DS3 doesn't work on Jak II either. Do you mean on the dev setup? I haven't tried that so far, since I assumed the result would be the same as for jak 1, and they were also the same on the non-dev setup.

**Comment by ManDude** [comment]
I mean games that aren't Jak.

**Comment by yodaxtah** [comment]
Ah, sorry, I don't have any other games. Do you happen to know where I can quickly test them? I'm very sure they work on the ps3. Also, the friend told me they had been playing Firewatch recently with those controllers on the pc, so their controllers should work with other non-jak games.

**Comment by Zedb0T** [comment]
Discord likely is a better platform for discussing this and investigating, You seem committed to looking into this so it would be sad if a phone number stopped you from joining the discord. If you Dm me on discord and send your discord ID I can try to bypass the filter for you.  I am `zedb0t` on discord or `178908133475876865` 

https://support.discord.com/hc/en-us/articles/206346498-Where-can-I-find-my-User-Server-Message-ID

**Comment by yodaxtah** [comment]
Well then, I've tried to reach out to you, but my messages don't come through, thus I've sent you a friend request!

![image](https://github.com/open-goal/jak-project/assets/159531413/7162b698-82ee-48c9-8809-d83b4f4363ca)

I'll just assume the security implications of putting my ID on the directly accessible web isn't that much of a security risk :-) It's `474316216283037697`

**Comment by Hat-Kid** [comment]
I manually verified you, you should be able to send messages now.

**Comment by yodaxtah** [comment]
As it turns out, this game is not the only one where DS4 works, but DS3 doesn't. I've tested the controllers on Fall Guys through Epic Games, and again, the game only seemed to respond to inputs from the DS4. The developers think it's a driver issue. Having nothing to install for DS4 doesn't mean that the DS3 doesn't require additional drivers.

I'm interested in hearing if anyone with a DS3 controller has made it work for OpenGOAL, or other games, such as Firewatch. And also, if applicable, what additional software has been installed to make it work? In case it works without software, I'd like to investigate why Firewatch works out of the box --- are they using something other than [SDL2](https://github.com/libsdl-org/SDL)? This could mean SDL could be patched perhaps. In case software was needed for DS3, it perhaps could be included in the documentation, or the documentation could link against a tutorial on how to setup up the DS3 controller to be used, since there are a lot of controllers, I suppose.

I will close the issue for now, since it's clear it's not an OpenGOAL issue, but let us know here about the DS3 experience, or in the Discussion on Discord: https://discord.com/channels/756287461377703987/1216298574330204161
