### ISSUE TITLE
CI: Intermittent macOS CI test failures due to `Illegal instruction`

### ISSUE THREAD

**Issue by xTVaser** [open-goal/jak-project#3439]
This appears to be because not every macOS runner is guaranteed to have AVX2. Narrowing down what is depending on this would eliminate the flakiness -- this problem will likely continue to get worse as modern macOS machines do not support AVX2.

**Comment by water111** [comment]
maybe it's the build cache being shared between avx2-compatible and non-avx2 compatible machines?

Seems very weird that there are systems without AVX2 since intel cpus in macs have had it since like 2013.

**Comment by xTVaser** [comment]
It's not guaranteed across the board https://github.com/actions/runner-images/issues/5609 but especially in macOS it kinda makes sense...since apple silicon AVX2 support was dropped so perhaps they are preferentially using older azure instances since there's no point?

The cache theory is a good one though, should be "easy" enough to involve the architecture into the cache-key.

**Comment by MaddTheSane** [comment]
It's less that Apple Silicon "dropped" AVX2 and more that Rosetta 2 never had an AVX2 translator (it tops off at SSE 4.1). This might change when Macs get M4s, but it's not guaranteed.

**Comment by xTVaser** [comment]
I would be surprised if they did, my understand for why Rosetta 2 stopped at SSE4.1 was because that was the lowest common denominator in the actively supported intel macs at the time Apple Silicon launched.

I would be surprised if Apple expended effort to _increase_ x86 backwards compatibility, when their usual strategy is to push developers towards the modern path (ie. dropping 32bit support).  

Given that reality, my main point was just that having AVX+ on these runners will become less and less of a priority as times goes on, so it shouldn't come as a surprise when errors like this increase in frequency.

**Comment by xTVaser** [comment]
https://github.com/open-goal/jak-project/pull/3502 seems to have resolved this, i havn't seen an intermittent failure in a long time (for this reason).
