### ISSUE TITLE
drill-bridge-shot in drill-eggs doesnt break/tilt

### ISSUE THREAD

**Issue by Zedb0T** [open-goal/jak-project#3463]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

On the way to the second turret a dude is supposed to break the bridge and it doesnt happen.

This needs more reports and investigation/comparison. Did happen for Josh or me

### How To Reproduce

Well the problem is actually that it isnt even produced let alone reproduce.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

Bridge breaks or tilts or something

### Environment Information

Latest release

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by ManDude** [comment]
Works for me.

![image](https://github.com/open-goal/jak-project/assets/7569514/1e26a880-ce6b-4c1a-a9af-fc3a95922080)

**Comment by Zedb0T** [comment]
Replicated it 3 times, then realized I was on 0.2.8... 

Updated to 0.2.10 and it worked first time Issue can be closed.
