### ISSUE TITLE
Hovercar and Hoverboard BUG

### ISSUE THREAD

**Issue by JankyBeats** [open-goal/jak-project#3493]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Whenever I ride in hover vehicles the (R2) button- to change hover level happens without me hitting the button. It happens very frequently. 

Whenever I ride the hover board, it automatically just kicks me off regardless of what I do. 

### How To Reproduce

It happens whenever I interact with vehicles or my hoverboard.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

To be able to control my height in a hover vehicle and stay on my hover board. 

### Environment Information

Other than these bugs, it runs great. 

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by ManDude** [comment]
Your controller has issues.

**Comment by xTVaser** [comment]
Duplicate https://github.com/open-goal/jak-project/issues/3289#issuecomment-1987016387
