### ISSUE TITLE
Stuck at the top of Citadel 

### ISSUE THREAD

**Issue by DJMezzy** [open-goal/jak-project#3510]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak1+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

After completing the final boss, watching the credits, and cutscenes, I was placed back on top of the Citadel. The boss music is playing. I want to return to the main area to get all the precursor orbs needed to open the final door. Unable to do so because I am not given a way down. If I get on the blue eco platform it takes me to the empty boss stage and back to the citadel. The elevator brings me back into the citadel. 

### How To Reproduce

I quit the game and come back. I am unsure why this is happening. 

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

No way to get down from citadel. When I jump off and die I just spawn back at the top. 

### Environment Information

[opengoal-support-package.zip](https://github.com/open-goal/jak-project/files/15259182/opengoal-support-package.zip)

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by dallmeyer** [comment]
> The elevator brings me back into the citadel.

... So then leave citadel through the main entrance
