### ISSUE TITLE
Bug no Launcher

### ISSUE THREAD

**Issue by ALEXDSN01** [open-goal/jak-project#3525]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak1+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Hello devs, my launcher is not opening and is generating a log file
[og-launcher-crash.log](https://github.com/open-goal/jak-project/files/15369793/og-launcher-crash.log)

### How To Reproduce

Ao clilcar em abrir o launcher

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

.

### Environment Information

.

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by abctheing** [comment]
Having exactly the same issue, same error code. Launcher just instantly closes

**Comment by ManDude** [comment]
Make sure Microsoft Edge is installed.

**Comment by abctheing** [comment]
> Make sure Microsoft Edge is installed.

Thanks, it works. Really enjoying the game!
