### ISSUE TITLE
game not opening

### ISSUE THREAD

**Issue by noob3445** [open-goal/jak-project#3544]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/launcher/issues?q=is%3Aissue+is%3Aopen+label%3Abug+sort%3Aupdated-desc) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game
- [X] If possible, I've attached the support package zip file to the issue [see how here](https://github.com/open-goal/launcher#asking-for-help)

### Attach Support Package / Log Files (drag and drop)

[jak1.2024-06-02T12-33-08.log](https://github.com/user-attachments/files/15524839/jak1.2024-06-02T12-33-08.log)
[jak1.2024-06-02T12-33-26.log](https://github.com/user-attachments/files/15524840/jak1.2024-06-02T12-33-26.log)
[jak1.2024-06-02T12-35-25.log](https://github.com/user-attachments/files/15524841/jak1.2024-06-02T12-35-25.log)
[jak1.2024-06-02T12-35-29.log](https://github.com/user-attachments/files/15524842/jak1.2024-06-02T12-35-29.log)
[jak1.2024-06-02T12-35-30.log](https://github.com/user-attachments/files/15524843/jak1.2024-06-02T12-35-30.log)
[jak1.2024-06-02T12-35-31.log](https://github.com/user-attachments/files/15524844/jak1.2024-06-02T12-35-31.log)
[jak1.2024-06-02T12-35-32.log](https://github.com/user-attachments/files/15524845/jak1.2024-06-02T12-35-32.log)
[jak1.2024-06-02T12-35-36.log](https://github.com/user-attachments/files/15524846/jak1.2024-06-02T12-35-36.log)
[jak1.2024-06-02T12-35-37.log](https://github.com/user-attachments/files/15524847/jak1.2024-06-02T12-35-37.log)
[extractor.2024-06-02T12-27-46.log](https://github.com/user-attachments/files/15524848/extractor.2024-06-02T12-27-46.log)
[extractor.2024-06-02T12-28-02.log](https://github.com/user-attachments/files/15524849/extractor.2024-06-02T12-28-02.log)
[extractor.2024-06-02T12-28-24.log](https://github.com/user-attachments/files/15524850/extractor.2024-06-02T12-28-24.log)

### Describe the Bug

hello so i go to open jak 1 and its not opening what i can do?

### How To Reproduce

i click play and its not opening

### Operating System

windows 11

### Launcher Version

v2.4.6

### Tooling Version

v0.2.13

**Comment by ManDude** [comment]
Send your support package.

**Comment by xTVaser** [comment]
Judging by how it took 60seconds to install the game, I assume you have a fairly underpowered computer.  In the past, some people's environments have taken many seconds, even minutes to startup the game's resources (initializing the controller library, etc).

I'm not 100% sure that is your problem but atleast in those situations, there was nothing we could do and it was the fault of that person's setup.

**Comment by xTVaser** [comment]
Re-open with more information / context if this persists.  This does not appear to be a wide-spread problem.

**Comment by EdCampion** [comment]
> Re-open with more information / context if this persists. This does not appear to be a wide-spread problem.

Have been struggling with this issue yesterday evening and for a chunk of today. It does appear to be user-system related. Reenabling my integrated graphics allowed Jak 1 to boot. Same failure as OP (after gl init) with just my 2070.
