### ISSUE TITLE
Speedrunner mode not resetting `ps2-actor-vis` properly

### ISSUE THREAD

**Issue by dallmeyer** [open-goal/jak-project#3552]
Josh did a run today on vanilla opengoal after playing teamruns (which turns off `ps2-actor-vis`), and speedrunner mode didn't make sure it was turned back on

**Comment by ManDude** [comment]
Did he restart the game midrun?

**Comment by dallmeyer** [comment]
> Did he restart the game midrun?

He used the speedrunner quick reset menu to start a new run after warming up, not sure if that answers your question

**Comment by xTVaser** [comment]
I see you already self-assigned so I won't ask you a bunch of questions (im sure you'll figure it out).  But looking at the code I'm interested to find out why -- as long as `start-speedrun` is called, the setting should be set.  Granted im not as familiar with jak 1's speedrunner menu as I am with jak 2's (which is what im assuming josh was playing).

**Comment by xTVaser** [comment]
Resolved in https://github.com/open-goal/jak-project/pull/3553
