### ISSUE TITLE
Mouse controlled camera does not work above 60fps

### ISSUE THREAD

**Issue by ElCrepers** [open-goal/jak-project#3558]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

When I activate the "Track Camera" option in Mouse Settings, it doesn't seem to work at all.

### How To Reproduce

Open Game config, Input Settings, Enable Mouse, Mouse Settings, Track Camera-Enabled

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

When I enable "Track Camera", the camera should follow the mouse (right?)

### Environment Information

[opengoal-support-package.zip](https://github.com/user-attachments/files/15905051/opengoal-support-package.zip)

### Game Version

PAL

### Have you set the game to something other than `60fps`?

Yes

**Comment by ElCrepers** [comment]
Set the game to 60 fps and solved it

**Comment by xTVaser** [comment]
I can't reproduce this in jak 1 (@150fps) or jak 2 (@144 fps).  The camera moves faster but, it still definitely moves along with the mouse.
