### ISSUE TITLE
Failure to launch

### ISSUE THREAD

**Issue by RonaldF9521** [open-goal/jak-project#3562]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak1+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

ISO loaded and jak is installed on steam deck. After hitting play button, it loads for about a second then kicks back to the menu. Tried restarting steam deck multiple times, but hasn’t fixed it. Any advice would be appreciated
![image](https://github.com/open-goal/jak-project/assets/173578857/74d15fcb-4b6f-401d-abb8-9813652f3755)

### How To Reproduce

ISO loaded. Dropped it into open goal iso folder. Installed on steam deck. 

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

When hitting play I expected game to load no problem. Just keeps booting back to the steam library

### Environment Information

Open goal version

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by RonaldF9521** [comment]
After going to game info. It says “jak 1 is unavailable because it is a non steam game, or mod. Steam will still manage launching the game for you and in most cases the in game overlay will be available”

**Comment by xTVaser** [comment]
Share the logs from `~/OpenGOAL/games/jak1/data/logs`.  It is likely the game did not actually successfully install, and therefore does not run.

**Comment by RonaldF9521** [comment]
> Share the logs from `~/OpenGOAL/games/jak1/data/logs`. It is likely the game did not actually successfully install, and therefore does not run.

Is there a way to fix the issue?

**Comment by xTVaser** [comment]
I was hoping the logs would help identify what the issue is, right now all I know is the game doesn't launch -- that could be for a variety of reasons.

If you don't want to share the logs, then I would suggest trying:
- Uninstalling and reinstalling the game via the plugin
- Try launching `gk` inside `~/OpenGOAL/games/jak1` in desktop mode via terminal so you can see any errors that appear

**Comment by 545u** [comment]
@RonaldF9521 Did you use the extractor tool before launching the game or did you just add the iso file to the iso_data folder? The extractor tool needs to be used before launching the game for it to work.

**Comment by xTVaser** [comment]
No response for a month, re-open with more information if the issue persists.
