### ISSUE TITLE
Black screen right on launch 

### ISSUE THREAD

**Issue by ItsModern** [open-goal/jak-project#3563]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Just as the title described, I have the game, I click launch and its just a black screen. I can hear the game and can hear im moving the menu but thats it. I tried debug mode, also doesnt work. Tried going in window mode, doesnt work. It does work on PCSX2 but not open goal. 

### How To Reproduce

Launch the game, boom black screen. 

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

When I load the game... I should see the game. 

### Environment Information

[opengoal-support-package.zip](https://github.com/user-attachments/files/15942550/opengoal-support-package.zip)
Windows 10, Nvidia 3070, Core i7 processor 10700

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by xTVaser** [comment]
Is your problem related to this https://github.com/open-goal/jak-project/issues/3279#issuecomment-1975011557

This has not been able to be traced back to anything in our code as of yet, and we havn't had reports of it in months.

**Comment by ItsModern** [comment]
> Is your problem related to this [#3279 (comment)](https://github.com/open-goal/jak-project/issues/3279#issuecomment-1975011557)
> 
> This has not been able to be traced back to anything in our code as of yet, and we havn't had reports of it in months.
> 
> > [31:29] [error] [end] OpenGL error 0x502 S8246 T824C: GL_INVALID_OPERATION error generated. Source and destination dimensions must be identical with the current filtering modes.
> 
> from logs appears relevant.

Just checked, neither of those are in my services sadly. So i dont know what else can be causing it, Jak 1 runs perfectly fine

**Comment by xTVaser** [comment]
Odd, as that error is both in your jak1 and jak2 logs.

I'd try the following, open the `pc-settings.gc` file in notepad.  You can find it by clicking on the following in the jak 2 menu:
![image](https://github.com/open-goal/jak-project/assets/13153231/a713f313-cac6-49b4-af01-9d9e8de4f953)

- Try replacing `(display-mode borderless)` with `(display-mode fullscreen)`
- Try replacing `(game-size 3620 2036)` with `(game-size 2560 1440)`

Try saving the file and launching the game after trying each of those and let me know if one (or none) solve the black screen problem.  That resolution is really odd, and is different from your jak1 setting (2560x1440 at fullscreen).

If things do suddenly work after that, what is the native resolution of your monitor (i assume 2560x1440) and are you running at a non-100% display scale?

**Comment by ItsModern** [comment]
> Odd, as that error is both in your jak1 and jak2 logs.
> 
> I'd try the following, open the `pc-settings.gc` file in notepad. You can find it by clicking on the following in the jak 2 menu: ![image](https://private-user-images.githubusercontent.com/13153231/342024709-a713f313-cac6-49b4-af01-9d9e8de4f953.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTkxNTAwMzIsIm5iZiI6MTcxOTE0OTczMiwicGF0aCI6Ii8xMzE1MzIzMS8zNDIwMjQ3MDktYTcxM2YzMTMtY2FjNi00OWI0LWFmMDEtOWQ5ZThkZTRmOTUzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjIzVDEzMzUzMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM0Yzc2Y2I5YWNiM2ZhMmI0YmM3MGJmZmU5NTE1ZTBkMThkZDRhMGIwODQxNWYxNTA2NDJmMDVhYzYwMGE4NGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.M6zNyKR8I37nCCZYYfUx1bv6bjzw3TFQpPk47J1wsg4)
> 
> * Try replacing `(display-mode borderless)` with `(display-mode fullscreen)`
> * Try replacing `(game-size 3620 2036)` with `(game-size 2560 1440)`
> 
> Try saving the file and launching the game after changing each of those and let me know if one (or none) solve the black screen problem. That resolution is really odd, and is different from your jak1 setting (2560x1440 at fullscreen).
> 
> If things do suddenly work after that, what is the native resolution of your monitor (i assume 2560x1440) and are you running at a non-100% display scale?

The displaymode didnt fix it, but the game size did! Thank you so much. My monitor is indeed 2560 x 1440 and my scale/layout is just 100%

**Comment by xTVaser** [comment]
kk good to know, I have some changes in-progress that should help prevent this problem.  I'll leave this issue open until those are merged.
