### ISSUE TITLE
Button Inputs sometimes don't work  while doing Combo Moves 

### ISSUE THREAD

**Issue by MotorMcAl** [open-goal/jak-project#3570]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

As i started the game it kinda felt off in the controls but i didn't pay any attention because it ran smoother than the emulated versions and its also looked crisper but as i was roaming around the edges of haven city i realized something the button sometimes don't work maybe its an issue with xinput but its the same thing with the keyboard controls and its only happens on combo moves for example lets say you wanna do a punching uppercut after a spin so i press B to Spin then Press X + A to do an uppercut sometimes the game registers the input sometimes it doesn't its the same if you try to do a super jump of a long jump  

### How To Reproduce

Go near Krew's HQ or near the Gun Course and then try to do a jumping uppercut after a spin or do a high jump after a long jump

### Does this problem occur on original hardware or PCSX2?

No

### Expected Behavior

pressing X+A after a spin Jak should do a punching uppercut and after you do a long jump pressing LB + A and then mash A repeatedly Jak Should do a high Jump following the long jump.

### Environment Information

CPU - AMD Ryzen 5 4800H 
GPU - GTX 1650 
OS - Windows 11
OpenGOAL v2.4.8

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by Zedb0T** [comment]
There are timing windows on present on all versions of the games. If you preform the inputs within the timing window you should get the desired output. Note that the game uses a 3 frame input window and this does not scale with the experimental higher FPS modes, so you may experience dropped inputs on fps values higher than 60.

Closing for now, feel free to reopen if you can provide a video of the issue along with an input display.

**Comment by Hat-Kid** [comment]
> Note that the game uses a 3 frame input window and this does not scale with the experimental higher FPS modes, so you may experience dropped inputs on fps values higher than 60.

It does scale properly for Jak 2 as of #3178.
