### ISSUE TITLE
[BUG] Game wont load other levels after collecting scout fly.

### ISSUE THREAD

**Issue by trupp1x** [open-goal/jak-project#3572]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak1+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

For some reason whenever i try to collect the scout fly next to the farm near the yakows in sandover village one of the farmer's dialogues get triggered the game gets soft locked and the game will only make you hear the farmer variant of the sandover village music, no sound effects at all. Whenever i try to go into a new area it wont load and it'll make jak continuosly fall down making it impossible to move. If you try to load another fail or exit the game wont let you do that. I tried replicating it 4 times and it worked 2/4 times. Both of the two times the same dialogue got triggered.

### How To Reproduce

I was trying to look for a way to get up to the scout fly without having to go up the tower by down uppercutting (don't know how to call it, it's the x + square move) after i failed i tried going up to collect the scout fly manually and collected it by down uppercutting once again.

### Does this problem occur on original hardware or PCSX2?

Didn't check

### Expected Behavior

When i collect the scout fly, one of the farmer's dialogues will get triggered, the game's sounds except for the music will stop working and the other areas wont load. Loading and saving wont work.

### Environment Information

Launcher 2.4.8 Game 0.2.14: CPU I3 10100F GPU RX 580 OS WINDOWS 10.

### Game Version

PAL

### Have you set the game to something other than `60fps`?

No

**Comment by ManDude** [comment]
Please attach a video.

**Comment by xTVaser** [comment]
Re-open if you have more detail, ideally a video as requested.
