### ISSUE TITLE
Bug scenarios

### ISSUE THREAD

**Issue by JackGamer2005** [open-goal/jak-project#3598]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Some scenarios take time to load when entering or exiting a part of the map.  It should be clarified that this error occurs with this version of the game I have because there is no problem with another version of the game obtained in another way

### How To Reproduce

![Captura de pantalla 2024-07-20 213809](https://github.com/user-attachments/assets/2c8f897a-082f-43ab-be4c-82386654380c)
![image](https://github.com/user-attachments/assets/8b3956a7-65bb-4fc5-9146-3827dae7b334)
![image](https://github.com/user-attachments/assets/99ed6283-9171-4e13-9a3d-fc3fe07778c3)

### Does this problem occur on original hardware or PCSX2?

Didn't check

### Expected Behavior

When a door is opened, it usually happens that the stage behind the door has not been loaded

### Environment Information

[opengoal-support-package.zip](https://github.com/user-attachments/files/16322784/opengoal-support-package.zip)

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by JackGamer2005** [comment]
![image](https://github.com/user-attachments/assets/6a2923c3-c1fc-459d-b3b7-ee6d74fa781f)
![image](https://github.com/user-attachments/assets/40bbfa1b-5b49-4dbd-952a-2149fff7ff1e)
![image](https://github.com/user-attachments/assets/7ab891cc-6f5e-468c-87ba-826322d30329)

**Comment by ManDude** [comment]
Does it eventually pop in?

**Comment by JackGamer2005** [comment]
> ¿Finalmente aparece?

Yes, after one or two seconds

**Comment by ManDude** [comment]
This is to be expected, then. The visuals are loaded separately and tend to load in slower than the actual level.

**Comment by JackGamer2005** [comment]
> Esto es de esperarse, pues los elementos visuales se cargan por separado y tienden a cargarse más lentamente que el nivel real.

Traducir texto con la cámara
Shouldn't it be synchronized? or preload?

**Comment by ManDude** [comment]
No.
