### ISSUE TITLE
Input folder doesn't have a DGO folder

### ISSUE THREAD

**Issue by JJerome67** [open-goal/jak-project#3602]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak1+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

When I try to Install via ISO, it fails during the Extract and Verify phase. In the logs, the failure message is "input folder doesn't have a DGO folder. Is this the right input?".

![image](https://github.com/user-attachments/assets/3d0990e1-85af-485e-aba0-adb89abf68a2)

### How To Reproduce

1. Click "Install via ISO".
2. Select ISO file.
3. Wait.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

It should install correctly.

### Environment Information

[opengoal-support-package.zip](https://github.com/user-attachments/files/16356726/opengoal-support-package.zip)

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by Zedb0T** [comment]
https://github.com/open-goal/jak-project?tab=readme-ov-file#running-the-decompiler

Must use a Ps2 iso
