### ISSUE TITLE
Jak runs slightly faster in Pumping Station section

### ISSUE THREAD

**Issue by bradical-1** [open-goal/jak-project#3636]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Noticed that while running on this pipe, only going a certain direction, that Jak runs slightly faster.

[OpenGOAL - Work in Progress - Jak 2 - v0.2.15 2024-08-12 21-57-09.zip](https://github.com/user-attachments/files/16593890/OpenGOAL.-.Work.in.Progress.-.Jak.2.-.v0.2.15.2024-08-12.21-57-09.zip)

### How To Reproduce

First time noticing it, so I'm not sure if it happens every run or not. Was just playing the game normally.

### Does this problem occur on original hardware or PCSX2?

Didn't check

### Expected Behavior

When I run across this pipe, Jak is not expected to speed up.

### Environment Information

[opengoal-support-package.zip](https://github.com/user-attachments/files/16593907/opengoal-support-package.zip)

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

Yes

**Comment by Hat-Kid** [comment]
This is normal, that particular platform is actually an extremely subtle downward incline.

**Comment by bradical-1** [comment]
> This is normal, that particular platform is actually an extremely subtle downward incline.

My bad! Never noticed it, sorry for the false report

**Comment by Zedb0T** [comment]
https://github.com/user-attachments/assets/7bfacaf8-0a11-4106-b85b-fb414f17a10a

Quite hard to notice no worries happens. 

Uploaded the video for future people who might run into the same thing and think its an issue

**Comment by ManDude** [comment]
Please do not waste our time by not checking if it also happens in the original game.

**Comment by pengouin8140** [comment]
do not waste your time? oh i'm sorry should we roll out the red carpet for you developers?
talk about being entitled lmao furry

**Comment by ManDude** [comment]
I do believe we, as people who work on this in our free time, are entitled to having the people attempting to report bugs put enough effort to respond to the questions in the bug report template.
