### ISSUE TITLE
Weird freeze glitch

### ISSUE THREAD

**Issue by LooeyG** [open-goal/jak-project#3637]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

In pumping station if I punch with my gun out the Jak freezes and this happened to me 6 times in a row

### How To Reproduce

go to pumping station after protect sig, take out scatter gun and start killing enemies. After time, Jak will completley freeze and you will be softlocked. Hitting "Restart Mission" does nothing, you will have to quit game and reload save file, but that doesn't do anything either

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

When you trigger a punch animation with scatter gun out, you might freeze in place and have to restart the whole game, even if you exit back to the launcher and reenter the game, it won't do anything. 

### Environment Information

[opengoal-support-package.zip](https://github.com/user-attachments/files/16630904/opengoal-support-package.zip)

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by dallmeyer** [comment]
please attach a video

**Comment by LooeyG** [comment]
okee

**Comment by LooeyG** [comment]
https://youtube.com/shorts/ERUdOARPYx4?si=3hRKiv-hZzK0mrM6

I couldn't get it to happen to me again but I found this video on yt showing that it happened to them too

**Comment by Zedb0T** [comment]
Not enough information in this video, but it looks like maybe you gave yourself the carry feature?

This feature isnt fully implemented in the  original game so you turn into a drawable error

**Comment by ManDude** [comment]
So, "even if you exit back to the launcher and reenter the game, it won't do anything" but you can't get it to happen again...? Anyway, were you in debug mode when this happen?

**Comment by LooeyG** [comment]
When I was backing out of the launcher and trying again it wasn't doing anything until after I wrote this thread, I was in debug mode, Idk if I had the carry feature on but I'll check next time, and sorry about the lack of information in the video, it was all I could find. Sorry abt this

**Comment by LooeyG** [comment]
I found out it was the "carry" feature, thank you for the help. I'll try to play around with it more next time I have an issue before writing a bug report next time, thank you guys for the help tho

**Comment by ManDude** [comment]
Thank you for double checking. I'll close for now since it seems to be from messing with the debug feaatures.
