### ISSUE TITLE
Hub 2 100% warp gate cutscene bug

### ISSUE THREAD

**Issue by sasqunjico** [open-goal/jak-project#3644]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak1+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

When i reset the hub 2 100% category extension using speedrun options menu from precursor basin, the cutscene trigger around the blue sage hut stays active after the reset as if the button is pressed and the cutscene hasn't played yet. 

### How To Reproduce

Start a hub 2 100% category extension run from the speedrun options menu
Press the warp gate button
Go to Precursor Basin 
Reset current speedrun
Approach the blue sage hut

This bug does not occur from anywhere else in hub 2 as far as i know. I do have a video of this but the file size is too large to attach here. I can be contacted on discord @sasqunjico for the video. 

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

When i reset, the warp gate should also reset.

### Environment Information

[opengoal-support-package.zip](https://github.com/user-attachments/files/16736638/opengoal-support-package.zip)

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by Zedb0T** [comment]
I tried to replicate the issue and was unable to, can you upload the video so I try to replicate it more accurately?

https://8mb.video

**Comment by sasqunjico** [comment]
https://github.com/user-attachments/assets/e238d9ec-66dd-4b7a-a9a4-8dc797304068

i sped up most of the stuff in between resets to make the video a little shorter. quality is not amazing but i did the standard no lts route through basin with plant deload. missed the pause at the end and reset. got the cutscene as i approached the hut, skipped the cutscene, still outside the hut

**Comment by Zedb0T** [comment]
Ok I can replicate.

**Comment by dallmeyer** [comment]
I think this is "NG+ glitch"? We've seen it with scout flies too
