### ISSUE TITLE
Jak II subtitle settings do not persist after game shutdown

### ISSUE THREAD

**Issue by MrWheyne** [open-goal/jak-project#3663]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

The Subtitles toggle under Game Options does not persist after reloading a game session. This forces the user (who wants to play with them enabled) to always have to go back to the menus and re-enable them. Tested using my rip of the Greatest Hits version.

### How To Reproduce

Start Game > Options > Game Options > Turn Subtitles On > Save > Close Game > Start Game > Options > Game Options > Check Subtitles (They're turned off)

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

Subtitles should persist between game sessions.

### Environment Information

[opengoal-support-package.zip](https://github.com/user-attachments/files/16964189/opengoal-support-package.zip)

### Game Version

NTSC Greatest Hits version (red label)

### Have you set the game to something other than `60fps`?

No

**Comment by ManDude** [comment]
Load your savefile first?

**Comment by xTVaser** [comment]
This is how the original game worked (the setting was stored in the savefile) but is something I recently changed https://github.com/open-goal/jak-project/pull/3612 so that you wouldn't be forced to load a savefile everytime you launch the game.

So sounds like a bug i need to investigate.

**Comment by MrWheyne** [comment]
It happens on Save Load, perhaps I should have explained it better. That's precisely how I noticed it happening in the first place.
