### ISSUE TITLE
Cant use my controller anymore 

### ISSUE THREAD

**Issue by kxngrage** [open-goal/jak-project#3668]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak1+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

I cant use my controller anymore. its a turtlebeach 360 controller which was working fine but since today it just doesnt work. it works fine in every other game

### How To Reproduce

retart the game, same resolt

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

Should be working since it was working fine yesterday

### Environment Information

.

### Game Version

PAL

### Have you set the game to something other than `60fps`?

No

**Comment by kxngrage** [comment]
only my L2 is working

**Comment by kxngrage** [comment]
So im wondering what was it? it is working again?

**Comment by Zedb0T** [comment]
https://github.com/open-goal/jak-project/releases/tag/v0.2.16

The last release was 3 weeks ago. Its cool its working but there was not a change on openGOAL's side that made it work.
