### ISSUE TITLE
Performance issues 

### ISSUE THREAD

**Issue by FKAMinty** [open-goal/jak-project#3673]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak1+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Unstable performance/stuttering/hitching.  Doesn't seem to be a hardware issue.  Not something I run into on other games or applications.  My Laptop should be able to run this very easily  RTX4060 Laptop GPU, 32GB RAM, i7-14650HX.
Also, kind of a minor thing, but the logo on the start screen displays incorrectly. The grey outline is opaque when it should be transparent and there's pink lines around the TM

### How To Reproduce

Occurs during general play.  Sentinel Beach was generally better but still had issues.  Played all of Sentinel Beach, Jungle, and just started Misty Island

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

It should run consistently

### Environment Information

[opengoal-support-package.zip](https://github.com/user-attachments/files/17085037/opengoal-support-package.zip)

### Game Version

PAL

### Have you set the game to something other than `60fps`?

No

**Comment by water111** [comment]
The pink outline on the TM is actually like this in the original game, it's just hard to see at the original resolution.

I'm not sure about the performance. That laptop should be able to play the game at 60fps with no issue. Can you make sure it's using the nvidia gpu instead of integrated graphics? Make sure the laptop is plugged in?

You could also trying changing graphics settings to turn down MSAA, or enable/disable vsync?

**Comment by FKAMinty** [comment]
> The pink outline on the TM is actually like this in the original game, it's just hard to see at the original resolution.
> 
> I'm not sure about the performance. That laptop should be able to play the game at 60fps with no issue. Can you make sure it's using the nvidia gpu instead of integrated graphics? Make sure the laptop is plugged in?
> 
> You could also trying changing graphics settings to turn down MSAA, or enable/disable vsync?

Laptop is plugged in,  It is using my Nvidia GPU, albeit the utilisation seems pretty low.  MSAA is at the default (x2).  Disabling vsync causes awful screen tearing

I've reinstalled the application, tried different ISOs, checked all my drivers are up to date, green checks across the board when I check system health through Lenovo Vantage

Really stumped
