### ISSUE TITLE
Installation has Failed! Unexpected error occurred with code -1073740791

### ISSUE THREAD

**Issue by Matty2024** [open-goal/jak-project#3695]
### Acknowledgements

- [X] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak1+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [X] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Good day everyone, hope you are all doing well.

I'll start with the basics regarding the installation of Jak 1: The Precursor Legacy
Tooling Version: 0.2.16 - Working normally
Tooling Version: 0.2.17 - Error with the above description.

A little bit of background on this to potentially help finding a solution.
When the previous update launched and allowed mods to be installed within the app (Fantastic!)
I naturally tried installing a favourite of mine "The Orb Hunt" but encounter the error string above.

Due to the disclaimer within the App. I followed up with a message to the original Dev: Dallmeyer (Barg).
Our conversation can be found [here](https://github.com/dallmeyer/OG-OrbHunt/issues/9) which I copied some of the logs. 
"

> If you run into a problem with the mod you will likely have to reach out to it's author and not the OpenGOAL team

."

I get the following issue when installing "Orb Hunt" 
- Build failed on custom_assets/jak1/levels/test-zone/test-zone.jsonc

I get the following issue when installing "Jack UP" 
- Build failed on custom_assets/jak1/levels/ju-train/ju-train.jsonc

I get the following issue when installing "River to Water" 
- Build failed on custom_assets/jak1/levels/afoniddwr/afoniddwr.jsonc

These issue continue with all mods for Jak 1: The Precursor Legacy **and now** just installing the vanilla version of the game too.
I have discussed many possible causes for this issue with Barg but unfortunately can't find a solution. 
I have 300GB of storage space free, I have updated my C++ library to the latest version. I have 12GB RAM installed.
I currently have the latest stable build of Windows 11.

It must also be noted that the following occurs.
ALL mods for Jak 2: Renegade work perfectly on Tooling v0.2.17 & 0.2.16
Installation of vanilla Jak 2: Renegade works perfectly on Tooling v0.2.16 & v0.2.17

If you need any further assistance from me, I'm here to help. :) 

### How To Reproduce

As mentioned above.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

Installation should be successful. 

### Environment Information

[opengoal-support-package.zip](https://github.com/user-attachments/files/17229402/opengoal-support-package.zip)

### Game Version

PAL

### Have you set the game to something other than `60fps`?

No

**Comment by trippjoe** [comment]
I might be making a bit of a leap here, but, if you have the decompiler settings enabled in the launcher please try disabling them. After disabling, try installing the mods again. After trying this, please send a new support package. Thank you.

**Comment by Matty2024** [comment]
> I might be making a bit of a leap here, but, if you have the decompiler settings enabled in the launcher please try disabling them. After disabling, try installing the mods again. After trying this, please send a new support package. Thank you.

Hello @trippjoe , hope you are doing well.

Thanks very much for the message and providing a possible solution to this error.
I have a golden rule of, if I don't know what something is / does, I don't touch it. Haha.

The Decompiler page I never open as I don't know what it does.
However, just for complete clarity, here are two screenshots from the main page & Decomplier. 
Again, the previous Tooling version 0.2.16 works perfectly for loading the vanilla game but the new version crashes.![Image](https://github.com/user-attachments/assets/e1ef6048-e1d1-48a9-9608-9e8069197650)
![Image](https://github.com/user-attachments/assets/d58be223-4685-4068-8ce1-865a0794d7a7)

**Comment by trippjoe** [comment]
On latest version:
cog wheel icon in the bottom right of the window then uninstall.
this will clean up a file that we suspect is causing the issue.
then reinstall using the iso, and then try the mods again.

**Comment by Matty2024** [comment]
> On latest version: cog wheel icon in the bottom right of the window then uninstall. this will clean up a file that we suspect is causing the issue. then reinstall using the iso, and then try the mods again.

Hi @trippjoe 

Thanks very much again for yours & everyone else's help who seems to be in on this. Your time is highly appreciated.
Please see attached screenshots of the game uninstalled and then observing the same install error (while still uninstalled with grey colour tint).
I made sure to have the latest version installed of Tooling & Launcher.

Reminder, this error is only occurring on the latest version, so I'm freely able to "Downgrade" and continue playing the game.
Thus, its not an urgent issue and can be attended to any any time. I need sleep now, otherwise will be even more useless at work tomorrow haha!

Have a great day further and will assist again with all questions when possible.

![Image](https://github.com/user-attachments/assets/61af4546-598c-473c-ae07-70dacbfc6c6f)
![Image](https://github.com/user-attachments/assets/f48b6215-a24e-4647-825d-878cf1f521c3)

**Comment by Matty2024** [comment]
Updated to the new Launcher. Looks really nice with all the percentages while installing. :)

![Image](https://github.com/user-attachments/assets/160cd61d-c3d8-4954-8803-64225489457c)

Hopefully this helps in some way.

![Image](https://github.com/user-attachments/assets/7656dfe3-3c14-4f75-8d7a-b395ea16e09f)

**Comment by Matty2024** [comment]
@xTVaser @trippjoe 

Good day xTVaser & Trippjoe, hope you are both doing well.

Thank you very much for all your assistance with this bug I've been having.
I can happily say that after updating to Launcher v2.5.2 - ALL IS WORKING AGAIN! 💯 
I highly appreciate your time resolving this and so grateful to the dedicated team here!

Have an awesome day further and week ahead. 🥇
