### ISSUE TITLE
French and English dialogs at the same time

### ISSUE THREAD

**Issue by Cousin-Freddo** [open-goal/jak-project#3712]
### Acknowledgements

- [x] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [x] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

when i lunch the game, the audio soundtrack is in french and in english at the same time. 

### How To Reproduce

i just launched the game and it happened immidietly with samos speech in both languages

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

i clic new game and let the oppening sequence play

### Environment Information

i dont know

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by ManDude** [comment]
Are you sure you did not boot up the game twice? It is not possible for the engine to play two streamed audio files at the same time, let alone in different languages.

**Comment by Cousin-Freddo** [comment]
Hi Alex,

Indeed my mousse just got this issue of double clicking everytime...

Sorry for the inconvénients.

I also have this issue : my game is in slow motion. I think i saw another
post with this issue but not exactly. It saud "sometimes" where my issue is
that the game is always slow.

Should i do another post for this or do you already have a solution ?

**Comment by Zedb0T** [comment]
Lower the msaa setting to the lowest setting and let me know if that resolves the issue

**Comment by Cousin-Freddo** [comment]
The anti-aliasing was on ×2, i turned it off completly and it didnt résolve
the issue.

BR

**Comment by ManDude** [comment]
Explore the various graphics settings to see what runs the best for you. Alternatively, use a better computer.

**Comment by Cousin-Freddo** [comment]
I've reduced every setting to the lowest and its still slow.

I have a MSI GP76 Leopard with intel core I7 and nvidia RTX. I didnt
thought Jak 2 would be an issue to run.

Should I create a post then ?

**Comment by ManDude** [comment]
No.

**Comment by Cousin-Freddo** [comment]
Okay....

Thanks Alex. Have a nice week-end
