### ISSUE TITLE
No input in Jak 2

### ISSUE THREAD

**Issue by Walbangerbw** [open-goal/jak-project#3727]
### Acknowledgements

- [x] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [x] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

For some reason im not getting any input for jak 2. my keyboard wont do anything, my controller, nothing. Super weird considering it works perfectly fine with jak and daxter.

### How To Reproduce

Restarting launcher and game.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

No inputs work on jak 2. not even in debug mode

### Environment Information

[opengoal-support-package.zip](https://github.com/user-attachments/files/17467487/opengoal-support-package.zip)

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by xTVaser** [comment]
From your logs:
> [19:02] [info] Found 2 controllers

It's likely that you have two devices that SDL is picking up as a controller, and the first one is not the one you are hoping it'll pick by default.

Press Alt to open the top-bar, and enable the keyboard:
![Image](https://github.com/user-attachments/assets/43897c81-d2f9-4a30-a3e0-fb4e9697b76c)

This will allow you to go into the game's settings menu and select your actual controller.

Alternatively, figure out what this second device is.

**Comment by Walbangerbw** [comment]
that worked, thanks so much! coffees on me
