### ISSUE TITLE
[jak3] Error while doing "task boot-game" or "task boot-game-retail"

### ISSUE THREAD

**Issue by oscoreggiato** [open-goal/jak-project#3728]
Hi, yesterday i installed Jak 3 from the [tutorial](https://www.youtube.com/watch?v=-a-8cpBH1z0) and all was succesful. But today as now i'm writing this, when i try to boot from task "boot-game-retail" or "task boot-game" i get this error: "Failed to open 255common.TXT for RPC STR" [here](https://www.mediafire.com/file/gjc3ze64hajwezw/jak3.2024-10-22T14-08-21.log/file) is the full log if you want to read it all.

**Comment by oscoreggiato** [comment]
> Open your `pc-settings.gc` file for Jak 3 and set the `game-language` to 0.

Thx for the fast reply @Hat-Kid . Where i can find that file?

**Comment by Hat-Kid** [comment]
`%appdata%/OpenGOAL/jak3` on Windows.
