### ISSUE TITLE
Compilation fails on `test-zone.jsonc`

### ISSUE THREAD

**Issue by Matty2024** [open-goal/jak-project#3748]
### Acknowledgements

- [x] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak1+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [x] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Good day everyone, hope you are all doing well!

Sorry to bother everyone again with this, but I'm having the same issue as it did [PREVIOUSLY](https://github.com/open-goal/jak-project/issues/3695).

Currently using Tooling Version 0.2.18 & Launcher Version 2.5.4
I have uninstalled and reinstalled **JAK 1** just to be 100% sure and still encountering the same issue.
Luckily, this was fixed previously with a new Launcher update so I presume its related to something very similar. 

I have **not** changed any settings (OpenGOAL App or Windows) or installed any new applications for that matter.
Hopefully this can be resolved very easily again this time. 

P.S @dallmeyer - Maybe this fix mechanic can be used to solve my problem with the Mods as well.
@xTVaser  @trippjoe - Thank you so very much for assisting last time and fixing the problem.
Please let me know if there is anything I can do to prevent this reoccurring in the further. 

### How To Reproduce

Can't Install.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

Failed successfully.

### Environment Information

Support Package Linked [Here](https://github.com/open-goal/jak-project/issues/3695)

### Game Version

PAL

### Have you set the game to something other than `60fps`?

No

**Comment by Matty2024** [comment]
![Image](https://github.com/user-attachments/assets/fda7a200-d8b8-40bf-a241-8f065c542d03)

**Comment by xTVaser** [comment]
Can you reupload the package?  The old one isn't relevant since ideally we'd want to see the latest logs. 
I'm wondering if it has the same error as last time:
```
[39:47] [warn] Error when reading DGOs: File C:\Game\active\jak1\data\iso_data\jak1\CGO\WATER-AN.CGO cannot be opened: does not exist. on C:\Game\active\jak1\data\iso_data\jak1\CGO\WATER-AN.CGO
```

**Comment by Matty2024** [comment]
Good Day @xTVaser Thanks very much for the reply. 
Ps - I look forward to the monthly progress updates with MUCH excitement. Thank you for all your work! 

Please see attached Support Packed as requested. I hope this provides some clarity.[opengoal-support-package.zip](https://github.com/user-attachments/files/17622291/opengoal-support-package.zip)

Regarding the title being changed to "Compilation fails on "Test-zone.jsonc". 
I don't believe there is anything wrong with my file as I shared my Test-zone.jsonc file with Barg and it was identical.
However, if this is something different and just making it easier for you, please ignore the above and my apologies.  

While installing Mods for Jak 1. The builds usually fail on any of the "special files".
For example "Jack UP" - Build failed on custom_assets/jak1/levels/ju-train/ju-train.jsonc

**Comment by xTVaser** [comment]
One thing that stands out to me is that you still have the above mentioned error.

When I look closely at your output, your logs say:
```
[10:09] [[38;2;144;238;144minfo[0m] Extracting WATER_AN.CGO...
```

Where-as mine say:
```
[33:41] [info] Extracting WATER-AN.CGO...
```

Why does your `WATER-AN.CGO` file have an underscore instead of a hyphen -- this is how the file is named on the original disc?  The extractor verifies the contents of the files, but the not the names (oversight on our part in hindsight) so that's why it can't find the file, which perhaps is what leads to the later error/crash.

If that's not it, then I'm not sure, I can't reproduce using a PAL ISO file.

**Comment by Matty2024** [comment]
> One thing that stands out to me is that you still have the above mentioned error.
> 
> When I look closely at your output, your logs say:
> 
> ```
> [10:09] [�[38;2;144;238;144minfo�[0m] Extracting WATER_AN.CGO...
> ```
> 
> Where-as mine say:
> 
> ```
> [33:41] [info] Extracting WATER-AN.CGO...
> ```
> 
> Why does your `WATER-AN.CGO` file have an underscore instead of a hyphen -- this is how the file is named on the original disc? The extractor verifies the contents of the files, but the not the names (oversight on our part in hindsight) so that's why it can't find the file, which perhaps is what leads to the later error/crash.
> 
> If that's not it, then I'm not sure, I can't reproduce using a PAL ISO file.

Hello @xTVaser ,

Thanks very much for your assistance and reply. Always highly appreciated.
The file in question regarding the underscore vs hyphen naming convention is exactly how it was on my original CD.
I have never changed any file names and purely created an ISO file directly from the CD folders. 

The question remains though, how does the ISO successfully install with any previous OpenGOAL Tooling Version and/or Launcher version but crashes only with the latest one? Has something changed in the latest update that could break this file? Seems weird.

However, I will alter this file's name for you and report back once I'm home from work. If it doesn't work, I'll simply "downgrade" to the previous tooling version to continue playing as a temporary "fix". I prefer work to continue with Jak 3 than be concerned with my issue.

Have a great day! :)

**Comment by Matty2024** [comment]
> One thing that stands out to me is that you still have the above mentioned error.
> 
> When I look closely at your output, your logs say:
> 
> ```
> [10:09] [�[38;2;144;238;144minfo�[0m] Extracting WATER_AN.CGO...
> ```
> 
> Where-as mine say:
> 
> ```
> [33:41] [info] Extracting WATER-AN.CGO...
> ```
> 
> Why does your `WATER-AN.CGO` file have an underscore instead of a hyphen -- this is how the file is named on the original disc? The extractor verifies the contents of the files, but the not the names (oversight on our part in hindsight) so that's why it can't find the file, which perhaps is what leads to the later error/crash.
> 
> If that's not it, then I'm not sure, I can't reproduce using a PAL ISO file.

Hello @xTVaser ,

To avoid any confusion, I have deleted my previous comment.
Thanks very much for your assistance and reply. Always highly appreciated.

-----------------------------------------------------------------------------------------------------
The file in question regarding the underscore vs hyphen naming convention looks like something weird is going on there.
I have never changed any file names and purely created an ISO file directly from the CD folders.

I checked my CD this evening and it has a HYPHEN with the file called "Water-an.CGO" and does not have an underscore. 
Which I presume is the correct naming convention with this. 

However, when I check my "C:\Game\active\jak1\data\iso_data\jak1\CGO" folder location, it has "Water_an.CGO". (Underscore)
Its almost like when the game is being compiled or something, the file name is being changed somewhere? Is that possible?

When I change the file name to have the recommended hyphen in that folder, it gets changed back to a underscore again.. weird.
I can create another ISO file but seeing as everything was working perfectly on the previous Tooling version, I'm not sure it will help.

Let me know if there is anything else I can try.

**Comment by xTVaser** [comment]
I'm going to go out on a limb then and say that it has something to do with your ISO authoring program, we've seen odd behaviour in the past.

How it worked on later versions? No idea, it's clearly blowing up on a specific part of the code, somewhere in the custom level building, but without running it with a C++ debugger and getting a line number, it's too hard to guess.  The fact that it can't be reproduced implies it's probably something strange on your end.

**Comment by Matty2024** [comment]
> I'm going to go out on a limb then and say that it has something to do with your ISO authoring program, we've seen odd behaviour in the past.
> 
> How it worked on earlier versions? No idea, it's clearly blowing up on a specific part of the code, somewhere in the custom level building, but without running it with a C++ debugger and getting a line number, it's too hard to guess. Some things around this code did change between last month, but I suspect it's your odd ISO causing these edge cases to manifest. The fact that it can't be reproduced implies it's probably something strange on your end.

All Good. Thanks very much for the assistance @xTVaser . I currently use the program "ImgBurn" to create all my ISO files.
I will have a look for an alternative over the weekend and see if I can create another ISO file which doesn't decide to behave badly. Haha.

Thanks again for your help. Your time is really appreciated. 
Have a great day!
