### ISSUE TITLE
Some problems in the latest version

### ISSUE THREAD

**Issue by OliverMiguez** [open-goal/jak-project#3772]
### Acknowledgements

- [x] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak1+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [x] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

When I tried to play in the latest version of the launcher, the game image did not appear, only the audio played, only a black screen appeared, however when I changed the version to a slightly older one it worked for me.

### How To Reproduce

Simply with the game already set to version 18 (the latest available), when you started it, you could only hear the audio and see a black screen

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

When I started the game, the bug occurred directly

### Environment Information

The computer has more than the necessary capacity to work with opengoal

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by Zedb0T** [comment]
![Image](https://github.com/user-attachments/assets/88680d13-6787-4700-928d-7eaeabeba69e)

Can you attach your support package please
