### ISSUE TITLE
[Build Actor] Animations cause artefacts/jitters on 180 degree rotations

### ISSUE THREAD

**Issue by Grateful-Forest** [open-goal/jak-project#3786]
### Acknowledgements

- [x] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak1+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [x] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

Important issue as it affects the majority of animations and collision meshes.
Occurs as any bone passes a rotation of 180 degrees, and messes with the collision mesh functionality for a single frame as well as a large visual stutter.
Will happen on rotations travelling on either axis, and isn't related to interpolation or not, as you can manually assign animation frames and still get the artefact.
The movement and moment of the artefact looks like the following:
![Image](https://github.com/user-attachments/assets/4ad0d986-3cc5-4da9-b337-7443e29a632f)
This means you cannot have a spinning object (completing a full rotation) without an artefact, it also affects gameplay as the collision mesh will break in that moment, making spinning objects for gameplay purposes unfeasible.

### How To Reproduce

Set the rotation of a bone in an armature (on the panel on the right hand side of the 3D view) to move past the number "180" and record a movement past this number by recording the rotation to a keyframe.

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

Viewing the animation either in Blender or a GLB file viewer does not contain the artefact.
Also messes up Jak's movement as it affects the collision mesh rotation as well.

### Environment Information

Blender 4.0

### Game Version

NTSC 1.0 (black label)

### Have you set the game to something other than `60fps`?

No

**Comment by water111** [comment]
I think this is fixed now by https://github.com/open-goal/jak-project/pull/3794, thanks for the detailed report of the issue.
