### ISSUE TITLE
gk can't run jak 2

### ISSUE THREAD

**Issue by powerpuffboysz** [open-goal/jak-project#3811]
### Acknowledgements

- [x] I have [searched](https://github.com/open-goal/jak-project/issues?q=is%3Aissue+is%3Aopen+label%3Abug+label%3Ajak2+sort%3Aupdated-desc+) for duplicate or closed bug reports
- [x] I understand that I am supposed to provide my own legitimately obtained copy of the game

### Describe the Bug

i installed jak 1 manually using extractor and gk binaries and was able to launch and play just fine. however trying to install jak 2 the same way keeps spitting out an error saying it can't find files for jak 1. when running through the launcher it runs fine but my setup would benefit from being able to run directly through gk![Image](https://github.com/user-attachments/assets/56ac4272-33b9-4c43-a35a-f53d85ebb14a)
[jak1.2024-12-23T22-53-40.log](https://github.com/user-attachments/files/18235578/jak1.2024-12-23T22-53-40.log)

### How To Reproduce

use standalone extractor 0.2.20 to build the files for jak 2

### Does this problem occur on original hardware or PCSX2?

Yes, it's unique to OpenGOAL

### Expected Behavior

install jak 2 using extractor and play via gk

### Environment Information

OS: EndeavourOS
Kernel: 6.12.6-arch1-1
Desktop: KDE Plasma 6.2.4
Session: Wayland
CPU: Ryzen 9 5900X
RAM: 32GB
GPU: NVIDIA 1080 TI Founders Edition
GPU Driver: Proprietary 565.77

### Game Version

NTSC Greatest Hits version (red label)

### Have you set the game to something other than `60fps`?

No

**Comment by Hat-Kid** [comment]
You need to run `gk` with the `--game` argument when not running Jak 1: `gk --game jak2 -- -boot -fakeiso`

**Comment by xTVaser** [comment]
Reopen or open a help thread in the discord if the above does not set you on the right path.
