### ISSUE TITLE
[decompiler] `dotimes` detection breaks if its iteration variable shares name with other variables

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#521]

**Comment by water111** [comment]
This usually works (for example https://github.com/water111/jak-project/blob/master/test/decompiler/reference/engine/dma/dma-disasm_REF.gc#L396).  Is there a specific place where this fails?

**Comment by ManDude** [comment]
Yeah, with these options
```
  "(method 20 res-lump)": {
    "args": ["obj", "time", "result", "data-offset"],
    "vars": {
      "t0-2": "tag-lo",
      "t1-2": "tag-hi",
      "v1-6": "elt-count",
      "t0-9": "i",
      "t0-10": "i",
      "t0-11": "i",
      "t0-12": "i",
      "t0-13": "i",
      "t0-14": "i",
      "t0-15": "i",
      "t0-17": "i",
      "t0-19": "i",
      "t0-21": "i"
    }
  },
```

**Comment by water111** [comment]
I did not think ahead when writing the variable thing and it doesn't support a function have multiple variables with the same name.  I do want to fix this eventually but it will probably be a while before I get to it.

**Comment by water111** [comment]
variables with the same name are explicitly not supported in the decompiler
