### ISSUE TITLE
[offline tests] Test is starting to take a while

### ISSUE THREAD

**Issue by water111** [open-goal/jak-project#542]
The test takes 14 seconds on my computer, which is starting to get annoying.  Right now I build the decompiler in debug mode for faster iteration. If I switch that to an optimized build, it takes 4 seconds, but I'd like to avoid this for now.

I looked at the timing:
![image](https://user-images.githubusercontent.com/48171810/120128398-def4c780-c18f-11eb-9135-8a0e5f355e7e.png)

There are a few surprising parts:
- Expressions (14%) I'm surprised this isn't much more! This does a lot.
- Register Use / Variables (5%, 6%)  We can use bitsets for registers to speed this up, but it's already pretty fast.
- Store Temp (4.6%) this can just be left out entirely.
- Type Analysis (32.5%) This could probably be much faster.  I could probably ditch the map and switch to an array. Making the type states copy-on-write would also help a lot.

**Comment by xTVaser** [comment]
Perhaps with https://github.com/open-goal/jak-project/issues/1126 we can run offline-tests concurrently using the dependency tree?
