### ISSUE TITLE
[repl] newlines in input eat previous output

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#722]
It looks kinda funny when it happens.
![image](https://user-images.githubusercontent.com/7569514/127064018-c13f6942-9ad0-4336-8cbe-75255ff8dfe9.png)

**Comment by water111** [comment]
Does this still happen?

**Comment by ManDude** [comment]
Yes.

**Comment by xTVaser** [comment]
I did some investigation on this a while ago, it's a pain in the ass to fix but possible https://discord.com/channels/756287461377703987/756287461830688810/968320141836296192

**Comment by ManDude** [comment]
Still happens.

![image](https://github.com/open-goal/jak-project/assets/7569514/7262030c-bc89-4835-a782-3bb9cd2a659b)
![image](https://github.com/open-goal/jak-project/assets/7569514/31917b14-ccf2-4663-9735-01f98019f1e2)

**Comment by xTVaser** [comment]
I know it still happens...i explained in the issue that this is a problem with windows terminals and powershell.  It isn't something that we are going to feasibly fix.  There are upstream issues to fix powershell and such properly.
