### ISSUE TITLE
Slow build/test times

### ISSUE THREAD

**Issue by water111** [open-goal/jak-project#79]
https://github.com/water111/jak-project/actions/runs/303333253
https://github.com/water111/jak-project/actions/runs/303333251

Windows is over 6 minutes and Linux is over 5.

**Comment by water111** [comment]
Here's a breakdown of build times per cmake target:
![image](https://user-images.githubusercontent.com/48171810/97644589-1a27f000-1a21-11eb-813a-80d02b40cb77.png)

**Comment by water111** [comment]
And average build time per file, broken down into cmake targets:
![image](https://user-images.githubusercontent.com/48171810/97644839-c1a52280-1a21-11eb-8fb3-d49863bdec43.png)
Most of the time is spent in gtest_main, compiler, decompiler, runtime, and goos.
Both goos and gtest_main have really long compile times per file.

**Comment by water111** [comment]
This was made better in https://github.com/water111/jak-project/pull/106, which took off a little over 1 minute off of the linux/windows build times.

**Comment by xTVaser** [comment]
https://github.com/water111/jak-project/pull/828 build improved significantly via caching

**Comment by water111** [comment]
CI times no longer an issue, but local build times are still not great.

**Comment by water111** [comment]
I kinda think this is just how things are with big c++ projects and our build times are terrible given how much code we have.
