### ISSUE TITLE
[goalc] output _could_ be nicer around `find-parent-method`s with the right casts, but has compiler issues

### ISSUE THREAD

**Issue by xTVaser** [open-goal/jak-project#862]
`citadel-obs` with all method `21`s and `citb-battlecontroller's 27`

```lisp
(defmethod synchonize! citb-arm ((obj citb-arm))
  ((find-parent-method citb-arm 21) obj)
...
```

> This function call has unknown argument and return types and cannot be called.
Form:
((find-parent-method citb-arm 21) obj)

The decompiler simplifies the form because with the type-casts, it knows the signature.  However the compiler does not -- it still expects `find-parent-method` to return a plain `function`.

**Comment by water111** [comment]
duplicate (kinda) of https://github.com/open-goal/jak-project/issues/805 - there's probably some nicer way to write this that doesn't involve having the method number and a bunch of casts.
