### ISSUE TITLE
[game] Out of memory

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#975]
We have ran out of memory on the global heap.

![image](https://user-images.githubusercontent.com/7569514/142048626-c57ba0c6-07e2-40f8-8bc8-21d66f54be07.png)

We can expand it, but it is unknown if it could break any code. By doubling the size we can see that we're using a few K more than we should. Related to #967, one cause could be because our code ends up being larger, and the global heap has much more code than individual levels. One cheap way to save some code space would be getting rid of some of the inspect methods for the smaller bitfield types. I think we generate an inspect for all of the types in `gs.gc` (which the original game didn't) which is a *lot* of types. We can add a `:no-inspect` property to `deftype` that skips generating an inspect?

We also allocate a few extra things on the global heap, like the scratchpad ram. Also right now we allocate it twice, once for the stack and a second time for general purpose data. We can probably merge the two?

**Comment by ManDude** [comment]
Getting rid of the inspects for most of the GS types and `control-info` and merging the two scratchpads reduced usage by... ~16k. Not as much as I'd like and we still need more space.

**Comment by water111** [comment]
A temporary solution is to remove `eichar` from the DGO. It uses like 1.3 MB and nothing uses it yet. Of course that won't last forever.

There are a few big things that we can't change, and we can ignore:
- the two level heaps
- `display` (allocates DMA buffers)
- `eichar` and `sidekick`
- `gkernel` (allocates actor heap)

if we remove these, there is about 3.7 MB left. There is 139 kB used before loading anything (64kB is the symbol table, not sure about the rest) and 11 kB used after loading everything (random init stuff).  The rest is all from loading (and allocations) from object files:
![image](https://user-images.githubusercontent.com/48171810/142087240-5d412fb7-e4cd-4ef5-8a1a-9a1399928659.png)

The suspicious things are:
- `default-menu` - should be debug only
- `cam-layout` - should be debug only
- `anim-tester` - should be debug only
- `gstring` - uses 41kB?

The rest all seems like our code is just bigger in general.  The three "debug" files use ~300k in total, so it's probably worth going after those.

**Comment by water111** [comment]
```
sparticle					341504
sprite					308224
tpage-1032					263356
default-menu					182120
mood-tables					84116
game-info					83680
level					83371
cam-layout					71824
progress					69252
cam-states					67936
ocean-frames					65573
crate					63445
mood					58444
ocean-tables					56990
load-boundary-data					52148
anim-tester					45015
text					44864
sparticle-launcher					44536
task-control					43669
collide-mesh-h					41616
gstring					41401
collide-shape-h					41280
generic-obs					40469
collide-cache-h					39808
collectables-part					39671
nav-enemy					37485
logic-target					37346
level-info					36133
texture					36032
hud-classes					35497
target-part					35038
progress-draw					33543
gsound					32985
font					32922
cam-master					32448
entity					30864
load-boundary					30828
matrix					30549
camera					29465
progress-part					26300
game-save					25296
projectiles					24133
process-taskable					23571
speaker					22848
ambient					22820
target-util					22030
fuel-cell					21294
geometry					21152
main					20391
effect-control					20103
```

**Comment by ManDude** [comment]
I think it *might* be fine to keep it expanded to ~64M for now, especially if we want to make changes to the games or do some fixes, but we should still be wary of memory usage, specially if these debug files are getting put on the global heap. I haven't ran into any issues that I could track down to the new 64M heap yet, but we'll see.

> `gstring` - uses 41kB?

I checked and `gstring` allocates the two console buffers `*stdcon0*` and `*stdcon1*` which are 16K each. I think console 1 is used when the game/kernel is paused?

**Comment by ManDude** [comment]
We've been using the ~64MB global heap for a few months now and there have been zero issues related to it, so I'm just gonna close this. Reducing the memory usage down to 32MB is kind of a lost cause at this point - our code is too large, and we might want to add random debug things to the `suspend` macro for example which would bloat the size considerably as well. Plus we're fighting against that memory usage there by adding new features, anyway.

**Comment by ManDude** [comment]
Booted up the game (PAL version but whatever) and went to every level and then checked the status of the global heap... 30848 bytes remaining - that's 30.125K.

There was never any chance of us only using 30 extra kilobytes LOL.
