### ISSUE TITLE
[kernel] better GOAL/runtime interoperability for user config & OS interaction

### ISSUE THREAD

**Issue by ManDude** [open-goal/jak-project#983]
Right now there's no way for the GOAL engine to fetch any information about OS-side things that we will want to read and write back and forth without creating a janky amount of "kernel def" functions (see: stuff for newpad and the debug pc pad mapping) which still take up memory and probably fill the symbol table much faster. These are things like the size of the window, the position of the window, display resolution, CPUID/device information, OS information, display information, game settings such as resolution, gfx devices, input devices, sound devices, and so on and so forth. It might be worth doing something like `pskernel.gc` and adding a `pckernel.gc` (see what i did there?) file that has a few types that we can store this information in along with a few helper functions or anything else we might deem necessary so that we can use all of this information in GOAL code directly. For example, by having the game or display resolution easily accessible we could make resolution-independent text so that we can fit more things onscreen. Could also have a better-made controller mapping menu and the ability to select input devices, or selecting audio devices or fullscreen displays, etc

**Comment by water111** [comment]
agreed, this sounds like a good idea.  I like the idea of putting it in a separate file like `pckernel.gc` so it's clear what we're adding.
